### ISSUE TITLE
Baskets... What, why, how?

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#100]
For catalogs, a basket column is required.
Then we have basket columns everywhere and we need to specify a value for it because there is a NOT NULL constraint on this column.

Proposal: Create by default a standard basket by default and use that as default value.

Or: Check if we can specify a default basket on database level (really?)

Or better: Ask Stefan Ziegler

**Comment by romefi** [comment]
Peter explained the handling with basekts (https://freedcamp.com/Romedis_Projects_w07/Projektgenerato_wW74/todos/12487488/#comment-5895534).

So:
- If a new model is generated without any data, a standard basket should be created and used
- If data are imported and edited, the basked id should be defined somehow and used for the basket column. In first step as project variable as discussed in the last meeting? And later on as second priority as drop down list of the available basekts, where the user can choose in which basket he wants to edit?

**Comment by m-kuhn** [comment]
Add option in advanced options to control the flag `--createBasketCol`
