### ISSUE TITLE
Intuitive relation editing interface

### ISSUE THREAD

**Issue by uncoyote** [opengisch/QgisModelBaker#108]
As promised I looked into relationships (n:m in particular).

A common way to display n:m and 1:n relationships is by having two adjacent list boxes as shown in the attached sample picture. Example: driver an car in a carsharing szenario.
The sample picture shows the situation for **one specific driver**, Matthias. The left list box shows all car's in the carsharing pool, usually with a quick filter possibility (many cars in the pool). The right list box shows the car's that are available for booking for Matthias.

The arrow buttons move selected cars or all cars from one side to the other (from bookable for Matthias to non bookable). This gui pattern is implemented in many applications - I think it is a intuitive way to implement n:m (and 1:n) relationships in a gui.

Opinions...?

![nzumgenerisch](https://user-images.githubusercontent.com/24891004/30698224-9589b512-9ee1-11e7-84f8-078c9fa4d149.png)

**Comment by m-kuhn** [comment]
This is very useful for managing lists with easily identifiable titles indeed.
Do you think this could totally replace the current widget? Or is this a dialog that can be opened from the current widget or will it be a configurable alternative?

What I like about the current approach is, that it's very easy to see attributes of children, say "which material is a cover of this wastewater structure made from". But maybe it's also ok to just have this information available with an extra click on one of the list entries?

Which scenarios are you using this in?

**Comment by m-kuhn** [comment]
Forgot to say: I think this is a very important topic, user experience in this area currently is definitely not great and having a good approach here will greatly enhance this features usability!

**Comment by m-kuhn** [comment]
Decision:
Implement the proposed interface as an alternative to the current one. Can be configured/changed in the relation configuration.

**Comment by m-kuhn** [comment]
Tractanded for the next sitting.
