### ISSUE TITLE
Problem with t_id in geopackage

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#120]
Just tested the Interlis-model PlanerischerGewaesserschutz_LV95_V1_1. Could collect some data, all works fine. But when i export the xtf, i get this message:

> Error: line 0: PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSAreal: tid 1: OID 1 of object PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSAreal already exists in CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Status.

> Info: PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSZone...

> Error: line 0: PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSZone: tid 1: OID 1 of object PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.GWSZone already exists in CLASS PlanerischerGewaesserschutz_LV95_V1_1.GWSZonen.Status.

In PostGIS the t_id is a global sequence and over all tables unique. In Geopackage the t_id starts in every table with value 1, which causes the failed export. If I import an xtf in Geopackage, all t_id are globally unique, so ili2gpgk seems to handle that somehow. Should also be handled with collecting data.

**Comment by m-kuhn** [comment]
@gacarrillor I remember you did some investigation w.r.t this already.

**Comment by gacarrillor** [comment]
Right @m-kuhn , I asked @claeis about this issue, well described by @romefi. Indeed, a way to handle global identifiers in GeoPackage databases generated via ili2gpkg is yet to be done. 

Claude says there is a table `t_key_object` that should be filled by the application used to capture data, in a way that the latest id introduced can be queried, and such value (incremented by 1) can be used as the id of the next record in the database. 

As far as I know SQLITE has no global sequences, so I think we could make use of triggers to fill the `t_key_object` table. 

Can you think about a better solution?


----
@romefi, when you import an XTF using ili2gpkg, it depends on whether the data into the XTF has global ids. For instance, it could come from PostGIS, which handles global ids well.

**Comment by claeis** [comment]
https://github.com/claeis/ili2db/issues/145
