### ISSUE TITLE
Deleting N:M Objects

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#121]
When deleting an object that forms part of a N:M relation, the entries on the linking table should be deleted without any further user interaction.

E.g. ON DELETE CASCADE on the database.

ili2db?

**Comment by m-kuhn** [comment]
A new (default) mode for N:M relations:

 * only one delete button
 * deletes link entry
 * checks if it was the last link entry
 * if it was, it asks to also delete the linked object

**Comment by romefi** [comment]
Solved with https://github.com/opengisch/QgisModelBaker/pull/422
