### ISSUE TITLE
Cascade deletion of objects in compositions

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#122]
When deleting the parent in a composition, the children need to be deleted along.

Possible approach: ON DELETE CASCADE
If not, some fancy way in QGIS to detect and react.

**Comment by m-kuhn** [comment]
Tractanded for the next sitting

**Comment by signedav** [comment]
This would be  the implementation of the relation strength, right?

The cascade delete on QGIS is supported, but Modelbaker does not create "composition" relations yet.

**Comment by m-kuhn** [comment]
Correct
