### ISSUE TITLE
Layer Styling - reference qml in ilidata.xml

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#132]
Approaches to (semi-)automatically apply layer styling

 * Use a formalized styling model (Darstellungsmodell) <- Possible?
 * Use meta attributes to define style-relevant attributes
 * Use meta attributes to link .qml or .sld files to layer styles

**Comment by m-kuhn** [comment]
This is currently under discussion here https://github.com/qgis/QGIS-Enhancement-Proposals/issues/125

I think it's also possible to manually strip some sections from the xml inside a qml as a workaround until this is implemented.

**Comment by gacarrillor** [comment]
Awesome!

**Comment by romefi** [comment]
Issue will be solved with UsabILIty Hub
