### ISSUE TITLE
Combobox for t_type

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#134]
Smart inheritance mapping generates t_type fields in class tables. t_type holds the sqlname of the applied model class which is not feasible.
t_type should be a combobox holding ilinames of the table t_ili2db_classname.

[ili2db-projectgenerator-and-smart-mapping.pdf](https://github.com/opengisch/projectgenerator/files/1625314/ili2db-projectgenerator-and-smart-mapping.pdf)

**Comment by m-kuhn** [comment]
Might be related to https://github.com/qgis/QGIS-Enhancement-Proposals/issues/79 (for which an offer is currently prepared).

@3nids can you evaluate if this is covered or need more info to figure out?

**Comment by 3nids** [comment]
@m-kuhn I don't see the link with the QEP. At the end isn't it just building a value map field with (sqlname, t_ili2db_classname) and use it for the widget field type?

**Comment by m-kuhn** [comment]
The thinking was that the term "classname" indicates, that the combobox holds names of other tables and hence a "dynamic relation" might apply. But I don't have any evidence to back up this theory.

@zigertiger Would be great to have an example model (or database dump) that demonstrates what this looks like in reality.

**Comment by zigertiger** [comment]
I'd propose «GL_Nutzungsplanung_V1» -- http://models.geo.gl.ch/DBU/GL_Nutzungsplanung_V1.ili

(implemented using Smart1Inheritance to avoid getting too much useless base class tables that do not need to be edited in the QGIS project)

**Comment by zigertiger** [comment]
...and here come dump, project file and input data (zone types list)
[_nupla.zip](https://github.com/opengisch/projectgenerator/files/1645799/_nupla.zip)

**Comment by m-kuhn** [comment]
@zigertiger thanks for the dump. Just had a look at it

The relevant structure is this from what I can see:

```
CREATE TABLE _nupla.grundnutzung_zonenflaeche
(
  t_id bigint NOT NULL DEFAULT nextval('_nupla.t_ili2db_seq'::regclass),
  t_type character varying(60) NOT NULL,
  t_ili_tid uuid DEFAULT uuid_generate_v4(),
  publiziertab date NOT NULL, -- @iliname publiziertAb
  rechtsstatus character varying(255) NOT NULL, -- @iliname Rechtsstatus
  bemerkungen text, -- @iliname Bemerkungen
  typ bigint,
  geometrie geometry(Polygon,2056), -- @iliname Geometrie
  CONSTRAINT grundnutzung_zonenflaeche_pkey PRIMARY KEY (t_id),
  CONSTRAINT grundnutzung_zonenflaeche_typ_fkey FOREIGN KEY (typ)
      REFERENCES _nupla.typ (t_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
)
```

`t_type` is a text field without any constraints

 * Is there a reason not to introduce a foreign key constraint on t_ili2db_classname
 * Should all classes from `t_ili2db_classname` be offered or is only a subset of them actually valid?

**Comment by zigertiger** [comment]
* no since the (qualified) class name of the relevant object class must be written to t_type
* methinks, all classes have to be offered... (w/o too much thinking about this...)

**Comment by zigertiger** [comment]
add: I don't see how only "relevant" class names could be extracted from t_ili2db_classname...

cetero censeo there must not be metaattribute galore ;-)

**Comment by zigertiger** [comment]
ὀλοφύρομαι

:-)

**Comment by m-kuhn** [comment]
Should be filled with possible values based on `t_ili2db_inheritance`.
@claeis, what do you think about adding a foreign key constraint on `t_type` fields so it only allows classnames from `t_ili2db_inheritance`?

**Comment by claeis** [comment]
I think it's to complicated to evaluate. What do you think about a value in t_ili2db_column_prop with the possible values and/or a CHECK constraint on the column?

**Comment by m-kuhn** [comment]
> What do you think about a value in t_ili2db_column_prop with the possible values

Wouldn't that be redundant with information already available in `t_ili2db_inheritance` (just easier to query)?

> a CHECK constraint on the column

like `CHECK (t_type IN ('A', 'B', 'C'))` or based on a select from another table? Would that be the same for geopackage?

**Comment by claeis** [comment]
yes, like ```CHECK (t_type IN ('A', 'B', 'C'))```

```t_ili2db_inheritance``` would not be enough.  You would also have to query ```t_ili2db_classname``` and ```t_ili2db_trfo```.
