### ISSUE TITLE
Handling Interlis-DataType BLACKBOX BINARY

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#167]
Interlis2 allows the Datatype BLACKBOX BINARY. ili2pg generates an attribute with type "bytea". A Interlis2-model as example is attached.
It should be possible to load a file in the formular at the concerning attribute and the file stored in the database als binary.

**Comment by m-kuhn** [comment]
What functionality do we need regarding such fields?

 - Upload files
 - Download files
 - Show files in an integrated viewer (images etc.)
   - Do we need special mimetype handling there?

**Comment by romefi** [comment]
Think thats it. Priority would be:

1. Upload files is the most . So we can add the files and export them in Interlis2 as the model requires.
2. Second priority is to show files. Quite important for controlling if the right document was added or simply use as a viewer to get the information. Think no special mimetype handling is needed, as the type can basically be anything (images, pdf, doc(x), xls(x) etc.)
3. Download files would be a nice ad-on for now. Sooner or later it will be required, so for me it's part of the scope

**Comment by m-kuhn** [comment]
Wait for a real world use case (Solothurn?)

**Comment by m-kuhn** [comment]
QGIS should (as far as I know) support bytea meanwhile.
It's possible that this issue is already implemented in newer QGIS versions.
Do we have a model to test?

**Comment by romefi** [comment]
Example http://[models.geo.sz.ch/AWN/replaced/SZ_Schutzbauten_AWN_2018-01-09.ili](http://models.geo.sz.ch/AWN/replaced/SZ_Schutzbauten_AWN_2018-01-09.ili)

**Comment by signedav** [comment]
Meanwhile supported. See 3.22 here:
Data type:
![image](https://user-images.githubusercontent.com/28384354/164177831-da7fc107-9312-4c25-a931-dd504afb84ce.png)

Widget:
![image](https://user-images.githubusercontent.com/28384354/164178142-9dba2931-3872-4c9f-a271-be1c341f0c15.png)

![image](https://user-images.githubusercontent.com/28384354/164178053-5c11c96a-cd89-4f06-a1b9-db353a027e41.png)

And quick test:
```
INTERLIS 2.3;

MODEL Backtoblack (en)
AT "mailto:U80863546@localhost"
VERSION "2021-12-15"  =
  TOPIC Black =
    CLASS Datei =
      Name   : TEXT;
      Inhalt : BLACKBOX BINARY;
    END Datei;
  END Black;
END Backtoblack. 

```

Added file with content: "Hi there!"

Export:
```
<?xml version="1.0" encoding="UTF-8"?><TRANSFER xmlns="http://www.interlis.ch/INTERLIS2.3">
<HEADERSECTION SENDER="ili2gpkg-4.6.1-63db90def1260a503f0f2d4cb846686cd4851184" VERSION="2.3"><MODELS><MODEL NAME="Backtoblack" VERSION="2021-12-15" URI="mailto:U80863546@localhost"></MODEL></MODELS></HEADERSECTION>
<DATASECTION>
<Backtoblack.Black BID="Backtoblack.Black">
<Backtoblack.Black.Datei TID="1"><Name>Test Binary</Name><Inhalt><BINBLBOX>SGkgdGhlcmUh</BINBLBOX></Inhalt></Backtoblack.Black.Datei>
</Backtoblack.Black>
</DATASECTION>
</TRANSFER>
```
