### ISSUE TITLE
Unterschiedlicher User für Schemaerzeugung und QGIS Projekt

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#170]
Vor allem, weil das Passwort im speziellen für diesen Superuser nicht im Projekt abgelegt werden soll.

**Comment by m-kuhn** [comment]
Pro Projekt zu konfigurieren

**Comment by signedav** [comment]
Means it should look like this:
![project_login_mockup1](https://user-images.githubusercontent.com/28384354/46603602-d093a200-caf3-11e8-9cc1-3a38befe2faf.png)
and this:
![projectlogin_mockup2](https://user-images.githubusercontent.com/28384354/46603608-d5585600-caf3-11e8-8d4a-b4fe6e173582.gif)
And it usually takes the hochwind login for creating db stuff and stored in the project, except it's changed in the Generate Project GUI.

Btw. this should be in export / import as well, correct?

**Comment by pramisters** [comment]
Die Umsetzung müsste aus meiner Sicht von der Logik her umgekehrt sein. Da ich den Feature Request verbrochen habe, kurz der Hintergrund dazu:

Der 2. DB user (Superuser) mit mehr Rechten (für die Schemaerzeugung) ist nur für die Schemaerzeugung von Bedeutung, wenn man nicht zuerst von Hand in der DB das Schema erzeugen will. Für den Datenimport und -export braucht es ihn nicht, da hier keine zusätzlichen Rechte erforderlich sind.
Da der normale User in der Regel projektabhängig ist (bei uns hat jedes Produktionsschema einen eigenen (gleichlautenden) User), macht es keinen Sinn diese Login-Daten in den Settings abzulegen. 

Ich stelle mir die Umsetzung etwa so vor:

- User/Password-Felder (für den projektspezifischen User, der im Projekt gespeichert wird) IMMER sichtbar (wie bisher).
- optional (durch Klick auf eine Checkbox) wird ein weiteres User/Password-Felderpaar sichtbar und der Superuser kann angegeben werden, für den Fall, dass das leere DB-Schema vorgängig noch nicht erzeugt wurde und der projektspezifische User nicht genug Rechte für die Schemaerzeugung hat.
- Da der Superuser i.d.R. immer gleich lautet, könnte man sich überlegen diesen in den Settings zu speichern (sofern er dann nirgends sichtbar ist bzw. abgefischt werden kann).

**Comment by signedav** [comment]
Grundsätzlich im Hintergrund aber gilt: Per default wird dem Login das Schema erstellt und es wird auch fürs Projekt verwendet. Wenn man aber etwas zusätzliches eingestellt (zBs. checkbox), erstellt man mit dem einen Login das Schema (Superuser Login) und für das Projekt wird das andere (normale) genommen.

Gemäss deiner Beschreibung @pramisters hätte man in den **Generate Project** GUI nicht das Superuser Login, sondern das Projektuser Login und mit spezieller Einstellung (zBs. checkbox) könnte man dort ein Superuser Login eintragen oder zumindest anwählen, dass es verwendet wird.

Entweder indem die Eingabefelder sichtbar werden, oder indem es die Superuser Werte aus den Settings nimmt. 
(Oder beides, was ich aber nicht machen würde, da man dann an zwei Orten Konfigurationsmöglichkeiten von demselben hat, was verwirrlich sein könnte.)

Stimmt das? Und was wird hierbei bevorzugt (Settings vs. sichbarwerdende Eingabefelder)?

**Comment by pramisters** [comment]
Deine Funktionsbeschreibung im ersten Abschnitt ist doch genau das, was ich auch beschreibe, nicht?
D.h. was die Funktion im Hintergrund betrifft, sind wir uns einig. 

Die Frage ist doch nur:
Warum muss das normale Projekt-Login, dass bei uns immer ändert,  bei deinem Realisierungsvorschlag zuerst mühsam in den Settings eingestellt werden und nur das Superuser-Login, das i.d.R. nie ändert, ist im "Generate Project"-GUI "eingebbar"?

Du hast meinen Vorschlag für die Eingabe der beiden Logins richtig verstanden. D.h. man müsste nur die Orte der Eingabe der beiden Logins vertauschen. Das Superuser-Login in die Settings (und nur da) und das normale Login (für das Projekt), wie bisher, immer sichtbar im "Generate Project"-GUI.

D.h. mit dem Ankreuzen der check box (Beschriftungsvorschlag: "Use different login from settings for schema generation) käme dann zusätzlich der Superuser zum Zug. Am GUI würde sich mit dem Ankreuzen der check box nichts ändern.

**Comment by signedav** [comment]
> Deine Funktionsbeschreibung im ersten Abschnitt ist doch genau das, was ich auch beschreibe, nicht? 
Genau. Es war nochmals wiederholt um sicher zu gehen.

Okay, danke für deinen Input. Dann wär es eine Checkbox unterhalb der Eingabefelder für das normale Login. Wenn diese aktiviert ist, wird für das erstellen der Superuser-Login aus dem Setting genommen. 

Ich schau das voraussichtlich noch diese Woche an.

**Comment by signedav** [comment]
Ich habe einen PR gemacht #253

Habe aber noch eine Frage:
Wenn der Superuser ein Schema erstellt, hat der Projectuser denn die Rechte auf Zugriff? Oder müssen ihm die Leserechte noch vergeben werden. Da ich bisher Permissions nur auf existierende Schemas vergeben habe, bin ich mir nicht sicher, ob das funktioniert (Recht auf zukünftig erstellte Schemas). 
Aber ich nehme an, ihr habt schon existierende Users @pramisters - wie sieht es dort aus?

**Comment by signedav** [comment]
Da das Schema bisher in ili2pg erstellt wird und nicht im Projektgenerator sehe ich zwei Wege das zu lösen:
1. Schema mit SU erstellen, ili2pg mit PU (Projektuser) ausführen, mit PU auf Projekt verbinden
2. ili2pg mit SU ausführen, Schema ownership auf PU übertragen, mit PU auf Projekt verbinden

Ich tendiere die zweite Möglichkeit zu nehmen, falls in Zukunft weiteres im ili2pg dazukommen würde, wo es den SU braucht. Siehst du ein Problem damit @pramisters ?

**Comment by pramisters** [comment]
Mir wäre die erste Variante lieber. Ist eleganter, weil der SU nur dort zum Zug kommt, wo er wirklich benötigt wird und man keine Rechte bzw. Ownerships vergeben muss. Das würde auch genau dem jetzigen Vorgehen bei der Nutzung des Projektgenerators entsprechen, wenn man nicht will, dass das SU-Login im Projekt gespeichert wird. Neu würde dann einfach der Projektgenerator das Anlegen des DB-Schemas (per SU) übernehmen. 
Die zweiten Variante funktioniert so nicht! Es müsste auch die Ownership an den erzeugten Tabellen auf den PU übertragen werden, nicht nur die die Ownership am Schema selbst. Sonst sind die Tabellen für den PU nicht sichtbar.

**Comment by signedav** [comment]
> mit PU auf Projekt verbinden

dies würde verhindern, dass der SU im Projekt gespeichert ist. Und das Ownership müsste dann natürlich ebenfalls auf die Tables gehen.

Aber das erste Verhalten ist auch okay für mich.

**Comment by pramisters** [comment]
Bei der ersten Variante erhalten die Tables automatisch die Ownership des PU, weil der PU vor der Ausführung von ili2pg bereits Owner des Schemas ist (siehe CREATE-SCHEMA-Beispiel weiter oben) und die Ownership beim Anlegen der Tables vom Schema nach unten propagiert wird.

**Comment by signedav** [comment]
Okay, ist jetzt so implementiert, wie @pramisters vorgeschlagen:
![screenshot from 2018-10-10 08-44-28](https://user-images.githubusercontent.com/28384354/46717575-bb8c4f80-cc68-11e8-9ffa-e13587c0bdf8.png)
1. Wenn checkbox angewählt erstellt es bevor es den ili2pg command macht mit dem superuser (aus den settings - hier "postgres") das schema und gibt die rechte dem projectuser (aus gui - hier "hochwind"). 
2. Führt ili2pg mit projectuser (hochwind) aus
3. Erstellt Projekt für projectuser (hochwind)

Dies ist nun für Generate Project implementiert. Ich denke, es soll auch für den Import implementiert werden, richtig @pramisters ?

**Comment by pramisters** [comment]
Nicht zwingend.
Das Anlegen der Tabellen und den Import der Daten in einem Schritt wird von ili2pg zwar angeboten (Fall 3 in der Doku), für den Projektgenerator könnte man sich aber auch auf den Standpunkt stellen, dass der User das in 2 Schritten machen muss, d.h. Schemaerstellung mit "Generate" (entspricht Fall 2 in der Doku) und Datenimport mit "Import INTERLIS Transfer File" (entspricht Fall 4 in der Doku). Denn meiner Meinung nach ist es eher selten, dass man importieren will, aber noch kein DB-Schema vorhanden ist.
