### ISSUE TITLE
path

### ISSUE THREAD

**Issue by aweb777** [opengisch/QgisModelBaker#176]
The java path was not found on my machine. I set the path to e.g. "C:/ProgramData/Oracle/Java/javapath" which didn't work either. Then I set the path to "C:/ProgramData/Oracle/Java/javapath/java.exe" which worked fine (including "/java.exe"). Maybe the annotation "Java Path" in the setting dialog could have a hint/example "C:/ProgramData/Oracle/Java/javapath/java.exe".

**Comment by m-kuhn** [comment]
The placeholder text in the widget can be improved for this.

In general, we would like to make the tool work with 0 configuration. Could you open a python console in your QGIS installation and run the following script, so we can check if/why it is not working without any configuration:

```
import os
print('Path: {}'.format(os.environ['PATH']))
print('Java Home: {}'.format(os.environ['JAVA_HOME']))
p = QProcess()
p.readyReadStandardOutput.connect(lambda: print('{}: {}'.format(proc, p.readAllStandardOutput())))
p.readyReadStandardError.connect(lambda: print('{}: {}'.format(proc, p.readAllStandardError())))
for proc in ['C:/ProgramData/Oracle/Java/javapath/java.exe', 'java', 'java.exe', 'gugus']:
    print('')
    print('-----------')
    p.start(proc, ['-version'])
    print('{} started: {}'.format(proc, p.waitForStarted(3000)))
    p.waitForFinished(3000)
    print('{} exited with {}'.format(proc, p.exitCode()))
```

**Comment by aweb777** [comment]
Does this help?
Python Konsole 
QGIS-API ist über iface zu benutzen. Geben Sie help(iface) ein, um mehr Informationen zu erhalten
import os
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\code.py", line 64, in runsource
    code = self.compile(source, filename, symbol)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\codeop.py", line 99, in _maybe_compile
    raise err1
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\codeop.py", line 87, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 8
    import os
    ^
SyntaxError: invalid syntax
print('Path: {}'.format(os.environ['PATH']))
Path: C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\numpy\core;C:\PROGRA~1\QGIS3~1.0\apps\qgis\bin;C:\PROGRA~1\QGIS3~1.0\apps\Python36;C:\PROGRA~1\QGIS3~1.0\apps\Python36\Scripts;C:\PROGRA~1\QGIS3~1.0\apps\qt5\bin;C:\PROGRA~1\QGIS3~1.0\apps\Python27\Scripts;C:\PROGRA~1\QGIS3~1.0\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem
print('Java Home: {}'.format(os.environ['JAVA_HOME']))
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'JAVA_HOME'
p = QProcess()
p.readyReadStandardOutput.connect(lambda: print('{}: {}'.format(proc, p.readAllStandardOutput())))
p.readyReadStandardError.connect(lambda: print('{}: {}'.format(proc, p.readAllStandardError())))
for proc in ['C:/ProgramData/Oracle/Java/javapath/java.exe', 'java', 'java.exe', 'gugus']:
    print('')
    print('-----------')
    p.start(proc, ['-version'])
    print('{} started: {}'.format(proc, p.waitForStarted(3000)))
    p.waitForFinished(3000)
![sshot-1](https://user-images.githubusercontent.com/24860761/38729273-bb1167c2-3f12-11e8-8e21-3c1805f93350.png)

**Comment by m-kuhn** [comment]
It looks like you need to hit "Enter" once more at this point (the line at the bottom still was not executed unfortunately)

**Comment by m-kuhn** [comment]
Or even better, use the code editor ([check the qgis docs for how to open it](https://docs.qgis.org/2.18/en/docs/user_manual/plugins/python_console.html#console-editor)), paste the code there and click the blue play button on top

**Comment by aweb777** [comment]
I ran it with the code editor on both QGIS-Versions. You see the result here:
![sshot-1](https://user-images.githubusercontent.com/24860761/38851408-ef087754-4215-11e8-8aa0-f8d3e5da9715.png)
![sshot-2](https://user-images.githubusercontent.com/24860761/38851409-ef203b28-4215-11e8-875d-798ec835e765.png)

**Comment by m-kuhn** [comment]
Issue cleanup, let's reactivate this if required.
