### ISSUE TITLE
MetaAttribute for Catalogue URI

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#188]
It would be nice to have a meta attribute for catalogue uri's.
After importing a model (probably with a toml file), the projectgenerator should scan the meta attribute table in the database for catalogue uris and propose to the user to install these as well.

Question, on which interlis element does this meta-attribute make sense?

E.g.

```
    !!@ catalogueDataUri=http://models.geo.admin.ch/ASTRA/ExceptionalLoadsRoute_Catalogue_V1.xml
    CLASS TypeOfRoute                                                    
    EXTENDS CatalogueObjects_V1.Catalogues.Item =                               
      Type : MANDATORY TEXT*10;                                                 
      RoadWidth : 0.00 .. 100.00 [INTERLIS.m];                                  
      RoadClearance : 0.00 .. 100.00 [INTERLIS.m];                              
      TotalWeight : 0 .. 1000 [Units.t];                                        
      AxisLoad : 0 .. 1000 [Units.t];                                           
      UNIQUE Type;                                                              
    END TypeOfRoute;
```

**Comment by romefi** [comment]
Many of the ili-files contain a model for the catalogues, e.g. model ExceptionalLoadsCatalogues_V1 in [ExceptionalLoadsRoute_V1](http://models.geo.admin.ch/ASTRA/ExceptionalLoadsRoute_V1.ili). But there are also ili-files without a specific model for catalogue, e.g. [PlanerischerGewaesserschutz_V1_1](http://models.geo.admin.ch/BAFU/PlanerischerGewaesserschutz_V1_1.ili).

I would suggest at the top of the ili-file

```
INTERLIS 2.3;

!!@ technicalContact=mailto:gis@astra.admin.ch
!!@ IDGeoIV=184.1
!!@ furtherInformation=https://www.astra.admin.ch/
!!@ catalogueDataUri=http://models.geo.admin.ch/ASTRA/ExceptionalLoadsRoute_Catalogue_V1.xml
MODEL ExceptionalLoadsCatalogues_V1 (en)
AT "http://models.geo.admin.ch/ASTRA/"
VERSION "2017-02-08"  =
  IMPORTS CatalogueObjects_V1,Units;

  TOPIC TypeOfRouteCatalogue
  EXTENDS CatalogueObjects_V1.Catalogues =

    CLASS TypeOfRoute
    EXTENDS CatalogueObjects_V1.Catalogues.Item =
      Type : MANDATORY TEXT*10;
      RoadWidth : 0.00 .. 100.00 [INTERLIS.m];
      RoadClearance : 0.00 .. 100.00 [INTERLIS.m];
      TotalWeight : 0 .. 1000 [Units.t];
      AxisLoad : 0 .. 1000 [Units.t];
      UNIQUE Type;
    END TypeOfRoute;
...
```
What would the notation be, if more than one catalogue should be imported? E.g. ErgebnisseBodenbelastung [http://models.geo.admin.ch/BAFU/](http://models.geo.admin.ch/BAFU/) has 4 codelists.

**Comment by m-kuhn** [comment]
> But there are also ili-files without a specific model for catalogue, e.g. PlanerischerGewaesserschutz_V1_1.

Which class/table is filled from a catalogue in there?

> What would the notation be, if more than one catalogue should be imported? E.g. ErgebnisseBodenbelastung http://models.geo.admin.ch/BAFU/ has 4 codelists.

Interesting, they even provide more than one codelist per catalogue (one catalogue file per topic as far as I can see).

**Comment by romefi** [comment]
PlanerischerGewaesserschutz_V1_1 is a bad example. The catalogue isn't really related to the model as i see now. Maybe [InventarWasserentnahmen_V1](http://models.geo.admin.ch/BAFU/InventarWasserentnahmen_V1.ili) is better. The catalogue fills the topic "Catalogs", so it's not an own model for the catalogue. Was only trying to say there's not an interlis-rule that says how catalogues are to be handled in a model or ili-file. Basically everything is allowed. Maybe @zigertiger or @pramisters know better.

> Interesting, they even provide more than one codelist per catalogue (one catalogue file per topic as far as I can see).

Interesting is the right word. Quite everything is possible.

**Comment by m-kuhn** [comment]
Will there ever be more than one catalogue for a single table?

If we take the per-class proposal, we could just list the same uri repeatedly and filter duplicates in the projectgenerator

```
    !!=============================================                              
    !! Lookup Tabellen (Kataloge)
    !!=============================================                              

    !! @catalogueDataUri=http://models.geo.admin.ch/BAFU/InventarWasserentnahmen_Catalogues_V1.xml
    CLASS Art EXTENDS WasserBase_V1.Gewaesser.CatalogItem =
    !!=============================================                              
      !! z.B. Wehr, Talsperre                                              
    END Art;                                                             

    STRUCTURE ArtRef EXTENDS MandatoryCatalogueReference =               
      Reference (EXTENDED) :  MANDATORY REFERENCE TO (EXTERNAL) Art;     
    END ArtRef;                                                          


    !! @catalogueDataUri=http://models.geo.admin.ch/BAFU/InventarWasserentnahmen_Catalogues_V1.xml
    CLASS AufstiegTyp EXTENDS WasserBase_V1.Gewaesser.CatalogItem = 
    !!=============================================
      !! z.B. Beckenpass, Schlitzpass
    END AufstiegTyp;

    STRUCTURE AufstiegTypRef EXTENDS MandatoryCatalogueReference =
      Reference (EXTENDED) :  MANDATORY REFERENCE TO (EXTERNAL) AufstiegTyp;
    END AufstiegTypRef;


    !! @catalogueDataUri=http://models.geo.admin.ch/BAFU/InventarWasserentnahmen_Catalogues_V1.xml
    CLASS DatenQuelle EXTENDS WasserBase_V1.Gewaesser.CatalogItem = 
    !!=============================================
      !! z.B. Messstation, Schätzung
    END DatenQuelle;
```

**Comment by romefi** [comment]
A canton could extend a catalogue, but that would be a new ili-file referencing to different catalogue. So that shouldn't be a problem. Even if technically possible, I assume there won't be more than one catalogue per class. So you're approach uri per class should work in my eyes.

**Comment by pramisters** [comment]
PlanerischerGewaesserschutz_V1_1 has no catalogue definitions at all.
 I guess that still most of the models (85% ?) have no catalogues.

ErgebnisseBodenbelastung_Punktdaten_V1.ili has 3 catalogue/codelist definitions (=TOPICs), but 4 provided codelists where 2 of them supply one of the catalogues but are disjunct.

I still doubt that the catalogue handling can (or should) be done by the projectgenerator as the possible variants are huge. Although there's is a base model by KOGIS for a single catalogue object, the catalogues themselves are unfortunately defined differently even within a Bundesamt (i.e. BAFU).

**Comment by m-kuhn** [comment]
Is it necessary to support every exotic variant of catalogues?

Or is there also an added value if we have a good part of them automated (and promote this approach as *best practice*)?

**Comment by m-kuhn** [comment]
1. whatever works for us ;)
2. we've got meta information injection by toml coming in soon, so we've got that covered ;)

**Comment by m-kuhn** [comment]
# Proposed solution

1. Introduce meta-attribute for catalogues `@catalogueDataUri`
2. Upon schema-import, scan database for `@catalogueDataUri`
3. If "standard-compliant" [1] catalogues are available, open a new dialogue after the schema import with a list of catalogue URLs. Each of these catalogues can be
  * disabled (checkbox)
  * URL modified
  * (in the future potentially, a default basket id is supplied which can configured)
4. Import catalogues based on this configuration

[1] The term standard-compliant should be taken with a grain of salt, since catalogues are per-se not standardized. So our standard will be defined by the set of catalogue approaches that we support ;)

**Comment by m-kuhn** [comment]
On hold, might be a different approach based on discussions with @claeis yesterday

**Comment by claeis** [comment]
relates to claeis/ilivalidator#71

**Comment by romefi** [comment]
Closed as DatasetIdx16, also known as ilidata.xm,l is going to solve this issue. Is part of UsabILIty Hub
