### ISSUE TITLE
Feature request: Handling of MANDATORY CONSTRAINTS in ili

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#225]
Handling of MANDATORY CONSTRAINTS like i.e. [Grundwasseraustritte](http://models.geo.admin.ch/BAFU/Grundwasseraustritte_V1.ili)

```
   MANDATORY CONSTRAINT

      !! Bei gefassten und genutzten Quellen (Fassungsart=gefasst, Nutzungszustand=genutzt) muessen folgende Attribute definiert sein
      !! Trinkwasser

      ((Fassungsart != #ungefasst) AND (Nutzungszustand == #genutzt) AND (DEFINED(Trinkwasser)))
      OR
      (Fassungsart == #ungefasst)
      OR
      (Nutzungszustand != #genutzt);

```

**Comment by signedav** [comment]
Setting constraints in the QGIS form concerning such cases is not that simple to integrate. Would need kind of a constraint parser. 

But anyway with the integration of the ili validator this is currently not high prio anymore.

**Comment by signedav** [comment]
Feel free to reopen again.
