### ISSUE TITLE
Failed creating Geopackage HaltestellenOeV_LV95_V1_3 with option --createFk

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#252]
Not sure if it's already issued or if its an ili2gpgk iusse.

We tried to generate model for the model `HaltestellenOeV_LV95_V1_3` with geopackage. We failed with error: 
```
failed to read class-mapping-table T_ILI2DB_CLASSNAME
  [SQLITE_ERROR] SQL error or missing database (no such table: T_ILI2DB_CLASSNAME)
```
It seems as the option `--createFk` causes the crash. Anyone any idea why? Bug in ili2gpkg

**Comment by volaya** [comment]
Is this issue really fixed? I am seeing it with the current master, and I dont see any commit that fixes it.

Moreover, if the --createFk version is removed,  other issues to appear, which looks also related to the version of ili2gpkg used by the plugin (no errors in the coversion when using the latest release, version 4) . They seem to be linked to the smart mapping options. The plugin documentation indicates that there are 3 alternatives: "no smart mapping", "smart1inheritance" and "smart2inheritance", but only the two last ones are actually available. The "smart2inheritance" option is the default one, and it causes an error. By selecting the "smart1inheritance" option, the gpkg is created without any problem. 

Thanks!

**Comment by m-kuhn** [comment]
Thanks for the update @volaya . This was closed as "likely fixed, no one experienced it in a couple of months".

Do you have a possibility to test this with the current pre-release version too? This is a rather big change (also with respect to underlying libraries) expected to be released very, very soon!

We should probably remove no smart mapping from the docs, this shouldn't be allowed.

For the smart2inheritance, we'd better open a separate issue to deal with it.

**Comment by volaya** [comment]
I had seen the issue with the current release, and it seems to be still a problem with the current master.

In case it can be interesting, i tried changing the version number that is hardcoded in the plugin, so it downloads a most recent version. I found two issues in that case:

- The structured of the downloaded zip file is differetn 
- The plugin assumes the existence of a "owner" field, while ili2gpgkg v4 creates one named "ColOwner" instead, so references should be changed

I can make a PR with these changes once i do a bit more testing, in case you find it useful. I am just trying things at the moment

**Comment by m-kuhn** [comment]
> I had seen the issue with the current release, and it seems to be still a problem with the current master.

The beta is built from the ili2db4 branch

**Comment by volaya** [comment]
ah, cool. Let me try

**Comment by volaya** [comment]
Works like a charm :-)

**Comment by m-kuhn** [comment]
Good to know, I'll close this issue in this case.

What made you look into this plugin? I don't think Interlis it's widespread outside Switzerland yet ;)

**Comment by volaya** [comment]
Work for a swiss client :-)

**Comment by m-kuhn** [comment]
Dang.
I was hoping for the European Union :D

**Comment by gacarrillor** [comment]
> What made you look into this plugin? I don't think Interlis it's widespread outside Switzerland yet ;)

You don't... what? :)

**Comment by m-kuhn** [comment]
Sorry @gacarrillor
