### ISSUE TITLE
Clarify on support state for UUID for GeoPackage

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#264]
Clarify what's required (if anything) for UUID support for primary keys in GeoPackages

**Comment by signedav** [comment]
Importing the model from here: https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/tests/testdata/ilimodels/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.ili

**Postgres:**
``` 
    t_id bigint NOT NULL DEFAULT nextval('zg_naturschutz_und_erholungsinfrastruktur_v12.t_ili2db_seq'::regclass),
    t_ili_tid uuid DEFAULT uuid_generate_v4(),  
    [...]
    CONSTRAINT einzelbaum_pkey PRIMARY KEY (t_id),
```
Adding feature on "einzelbaum": `T_Id` is `71` and `T_Ili_Tid` is `8be262d3-8928-4756-9ec0-44342cceb4f0` and same after saving.
Adding feature on "einzelbaum": `T_Id` is `72` and `T_Ili_Tid` is `80d95b20-3ddf-4f1b-bbe2-9a28e175b325` and same after saving.


**Geopackage**
```
T_Id INTEGER NOT NULL PRIMARY_KEY, 
T_Ili_Tid TEXT (36) NULL,
```
Adding feature on "einzelbaum": `T_Id` is `0` and `T_Ili_Tid` is `NULL` and same after saving.
Adding feature on "einzelbaum": `T_Id` is `1` and `T_Ili_Tid` is `NULL` and same after saving.

**Comment by m-kuhn** [comment]
@signedav do you know if the information that it's uuid is present inside the gpkg meta tables?

**Comment by signedav** [comment]
Haven't found any information in the meta tables. Maybe we can get the size of the PK. It's 36 - what an UUID is (32 hexdecimals and 4 hyphens) - btw. there we have to be carefull when QGIS generates UUIDs with braces `{}`

**Comment by m-kuhn** [comment]
> Haven't found any information in the meta tables. Maybe we can get the size of the PK. It's 36 - what an UUID is (32 hexdecimals and 4 hyphens) - btw. there we have to be carefull when QGIS generates UUIDs with braces `{}`

That sounds a lot like :evergreen_tree: :axe: -method. I would prefer to have information about UUID available as meta information @claeis do you see this fit into a meta table?

**Comment by claeis** [comment]
fits into ```t_ili2db_column_prop```
