### ISSUE TITLE
ENUMs are not configured if inherited from another model

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#268]
If an ENUM/Domain is inherited from another model (e.g. extension of MGDMs), they are not configured by the projectgen:
- Project properties: relation is missing
- Attributes form: Widget type is "Text edit" instead of "Relation reference"

Example:
[ZG_Nutzungsplanung_V1_1.txt](https://github.com/opengisch/projectgenerator/files/2586173/ZG_Nutzungsplanung_V1_1.txt)
that extends the MGDM https://models.geo.admin.ch/ARE/Nutzungsplanung_V1_1.ili

**Comment by m-kuhn** [comment]
* test with ili2pg4 (does that change anything?)
* is there a foreign key set on domains from inherited models
* is there a foreign key set on domains not from inherited models (and how are those detected currently)

**Comment by romefi** [comment]
@andreasneumann please test if this still is an issue. Thanks.

**Comment by pramisters** [comment]
It works with ili2pg4 !
