### ISSUE TITLE
Handling of stored users in PostGIS connection settings

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#269]
Is the projectgenerator able to handle the "new" way of user authentification in the connections-settings of PostGIS?

![image](https://user-images.githubusercontent.com/26796989/48619208-0dc53c80-e99c-11e8-8bcb-260a22874086.png)

We plan to connect the PostGIS-users with our active directories from windows. That means the password shouldn't be stored as plain text in the .qgs-file. With the new way of authentificating, the password isn't store in plan text. But I'm not sure if (and if yes how) projectgenerator can handle this.

**Comment by m-kuhn** [comment]
The user needs to be able to choose a auth configuration. In the following example that's `authcfg=v3m8fbu`

```<datasource>dbname='k-agi0' host=sr-geo101 port=5432 sslmode=disable authcfg=v3m8fbu key='gm_id' srid=2056 type=Polygon table="store_up"."up_bauwerke" (geom) sql=</datasource>```

@romefi are you able to open the same project on different computers?

**Comment by romefi** [comment]
If I open the .qgz on a different computer or someone else opens it, the login-prompt appears, where the login from active directories can be filled out and the project. We sure have to make some further investigations what it needs, that a user with already stored password doesn't get the prompt.

**Comment by romefi** [comment]
- droplist with available users (authcfg) in settings
- when authcfg set, don't show user/pw in other dialogs

**Comment by m-kuhn** [comment]
- in this case make sure, administrator password is set (if it's not set, ask the user? or extract from authcfg?)
