### ISSUE TITLE
Update ili2pg  version to 3.12.2

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#277]
3.11.2 --> 3.12.2

**Comment by m-kuhn** [comment]
Basket id now has to start with a letter

**Comment by romefi** [comment]
Plus the export of PlanerischerGewaesserschutz_LV95_V1_1 seems to work with 3.12.2, which fails with 3.11.2, even though the data is correct.

**Comment by romefi** [comment]
One more reason: Model InventarWasserentnahmen_V1 with smart1Inheritance fails with 3.11.2, but works with 3.12.2

**Comment by m-kuhn** [comment]
Sorry for the delay, I tried before but it was not trivial because the path to the tools changed.

Pull request pending now.
