### ISSUE TITLE
UUIDOID in GeoPackage

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#281]
When having UUIDOID definition in geopackage, they are not (automatically) filled.
At export time, this results in

> Error: line 0: SO_Nutzungsplanung_20171118.Nutzungsplanung.Typ_Grundnutzung: Class SO_Nutzungsplanung_20171118.Nutzungsplanung.Typ_Grundnutzung has to have an OID

the following script adds UUIDs to existing projects:

```
for layer in QgsProject.instance().mapLayers().values():
    if 'T_Ili_Tid' in [field.name() for field in layer.fields()]:
        with edit(layer):
            exp = QgsExpression('substr(uuid(), 2, 36)')
            context = QgsExpressionContext(QgsExpressionContextUtils.globalProjectLayerScopes(layer))
            for f in layer.getFeatures():
                context.setFeature(f)
                f['T_Ili_Tid'] = exp.evaluate(context)
                layer.updateFeature(f)
```

We should probably have `substr(uuid(), 2, 36` as the default value expression on those layers?

Not sure how ili2pg deals with this.

CC @romefi

**Comment by romefi** [comment]
We did same manually on ili2pg with a field requiring an OID. The`uuid()` without the `{}`, exactly what the expression does.
