### ISSUE TITLE
Omit tables and fields that do not need to be manipulated (localised/multilingual text)

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#284]
There are several cases where ili2pg produces database tables (or fields within tables) that do not need to be manipulated at all. To see those tables and attributes in a QGIS project might be confusing.
1)
**Such tables shall be ignored by the ModelBaker. 
E.g. «multilingualtext» (multilingual texts are implemented directly within the respective object tables.**
2)
Such fields shall be ignored by the ModelBaker. 
E.g. A the actual field name from a multilingual text (there are fields added for every language in the case of the usage of LocalisationCH_V1). 
E.g. B the field name «multilingualtext_localisedtext» in the table «localisedtext».
3)
In the table «localisedtext», the field «t_type» gets a constant value of «localisationch_v1_localisedtext» (where LocalisationCH_V1 is implemented (see also Localisation_V1).

**Comment by m-kuhn** [comment]
Point 1:
Tables that should not be shown
- `multilingualtext` (because expandMultilingual)
- `multilingualmtext` (because expandMultilingual)
- `surfacestructure` (because colaesceMulti)
- `pointstructure` (because colaesceMulti)
- `linestructure` (because colaesceMulti)

**Comment by m-kuhn** [comment]
Check for the approach in here before hardcoding names: https://github.com/opengisch/QgisModelBaker/issues/409
