### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/ws/Holder

### ISSUE THREAD

**Issue by andischi** [opengisch/QgisModelBaker#291]
Hallo,
Der Vortrag auf der FossGIS hat mich sehr beeindruckt. Ich habe das dort gezeigte Beispiel ausprobiert, bekomme aber Fehlermeldungen (sh.: [Generate-Error.txt](https://github.com/opengisch/QgisModelBaker/files/2991383/Generate-Error.txt)):
"...Exception in thread "main" 
java.lang.NoClassDefFoundError: javax/xml/ws/Holder..."

QGIS 3.6, PostgreSQL 11.2, POSTGIS="2.5.1 r17027, java-11-openjdk, Linux arch 5.0.2

**Comment by m-kuhn** [comment]
Hallo,
vielen Dank für die Rückmeldung.
ili2db läuft momentan leider nur mit der [Java-Version 8 und noch nicht mit der Version 11](https://github.com/claeis/ili2db/issues/262). Java 8 sollte parallel installiert werden können und der Pfad in den Optionen angepasst.

**Comment by andischi** [comment]
Vielen Dank!

________________________________

**Comment by edigonzales** [comment]
Da ich auch plusminus über die gleiche Fehlermeldung im ilivalidator gestolpert bin: Die Klasse `javax.xml.ws.Holder ` wurde in iox-ili-1.20.5 ersetzt: https://github.com/claeis/iox-ili/blob/816d4f086d772175bcb884663df1b9ee9f65b76a/doc/CHANGES.txt#L87

In `Generate-Error.txt` sehe ich, dass eine ältere Version verwendet wird (abhängig halt von ili2pg):

```
Info: ili2pg-3.11.2-20180208
Info: ili2c-4.7.7-20180208
Info: iox-ili-1.20.2-b58e2371ea1155aa3e4f5ff0b86d2432824b151b
Info: java.version 11.0.2
```

ilivalidator-1.11.0 (iox-ili-1.20.10) flutscht bei mir auf Java 11 sauber durch.
