### ISSUE TITLE
Installation error Windows

### ISSUE THREAD

**Issue by sjib** [opengisch/QgisModelBaker#292]
Folgend Fehlermeldung bei der Installation Version 4.1.0
Erweiterungsdeinstallation schlug fehl: Nichts zu entfernen! Erweiterungsverzeichnis nicht vorhanden: C:/Users/stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins/projectgenerator

Pfad sollte wohl C:\Users\stefan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker sein

**Comment by sjib** [comment]
Workaround: Leeres Verzeichnis projectgenerator erstellen

**Comment by m-kuhn** [comment]
Ich konnte dieses Problem nicht reproduzieren auf einem neuen, leeren Nutzerprofil unter Windows.

Evtl. war vorher das Projektgenerator Plugin installiert und es wurde nicht sauber deinstalliert?

Sofern dieses Problem nicht von anderer Seite bestätigt wird oder mehr Informationen vorliegen würde ich vorschlagen, den Issue zu schliessen.
