### ISSUE TITLE
Exception when generating project from postgis

### ISSUE THREAD

**Issue by AsgerPetersen** [opengisch/QgisModelBaker#297]
I am trying to generate a project from all schemas in a postgis database using these settings:
![image](https://user-images.githubusercontent.com/1392735/56032973-c44b0480-5d23-11e9-966f-234e1ba56111.png)

This exception is thrown:
![image](https://user-images.githubusercontent.com/1392735/56032917-9cf43780-5d23-11e9-8bd3-73eb1a1382b1.png)

Using
QGIS Model Baker version 4.1.1
QGIS 3.6.0 on OSX from Lutra Consulting installer
PostgreSQL version 10.7

**Comment by m-kuhn** [comment]
Hi @AsgerPetersen 

This looks related to https://github.com/opengisch/QgisModelBaker/issues/199

Support for "all schemas" is still lacking a sponsor.

**Comment by AsgerPetersen** [comment]
Ah, sorry. I tried searching existing issues, but didn't find that one.

**Comment by m-kuhn** [comment]
Actually... Maybe it's something else.
Did you try with a different db name too (e.g. no dashes)
No worries :)

**Comment by AsgerPetersen** [comment]
It does not work with a db name without special chars in it. It seems like it quotes the schema name with two single quotes on each side.

**Comment by m-kuhn** [comment]
Yes, see the discussion in https://github.com/opengisch/QgisModelBaker/commit/d4e66064a5a3f37f3e49610b20ab47c5780f1f79 for more details.

**Comment by m-kuhn** [comment]
We are not sure how to follow up here exactly. Might have been solved already (?)
If this is still an issue, please reopen with steps to reproduce.
