### ISSUE TITLE
Invalid Basket ID (BID)

### ISSUE THREAD

**Issue by p1d1d1** [opengisch/QgisModelBaker#298]
1) Generate --> Source Interlis (use PostGIS)¨. Choose ZG_Naturschutz_und_Erholungsinfrastruktur_V1 as model
2) Add a point in layer "erholungsinfrastruktur_punktobjekt" and save
3) Export XTF

The basket <ZG_Naturschutz_und_Erholungsinfrastruktur_V1.Geodaten> has an invalid BID. It should be UUID according to the model definition

**Comment by m-kuhn** [comment]
- Did you activate the option to create a basket column in advanced options?
- How was the basket inserted/created in there?

**Comment by p1d1d1** [comment]
> Did you activate the option to create a basket column in advanced options?
No I didn't. Should I?

**Comment by m-kuhn** [comment]
Not unless you have a good reason for it :)

**Comment by p1d1d1** [comment]
This is tricky. As far as I can see, if I don't activate the basket column invalid BID are created in export.
If I activate the basket column, then I'm not able to define the BID (actually it should be automatically generated since should be an UUID as the TID) and I cannot add any feature while t_basket cannot be NULL

**Comment by m-kuhn** [comment]
Extensive discussions have preceded (partially visible in here: https://github.com/opengisch/QgisModelBaker/issues/100)

It would be good to improve the situation (always enable baskets, add a default basket, make it visible (configurable?) for a user into which basket is being digitized). But as you said, it's tricky, I'm happy to discuss this in more detail.

**Comment by p1d1d1** [comment]
Yes this need a discussion. IMHO both BID and TID are concerned and we should try to cover all use cases defined in the Interlis Reference Manual (cfr. https://www.interlis.ch/download/interlis2/ili2-refman_2006-04-13_d.pdf Ch. 2.8.9).
We'd need a mix of automatic generated identifiers (UUID) and used defined identifiers.

Currently an invalid transfer (invalid BID) will be generated for all ili models containing the following definition:

`BASKET OID AS UUIDOID;`

**Comment by signedav** [comment]
I think this should be supported by the current versions. See for BID format and creation #599
