### ISSUE TITLE
Fail to export valid xtf for model PlanerischerGewaesserschutz_LV95_V1_1

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#306]
We have this valid xtf of the planerischer Gewässerschutz: [test.zip](https://github.com/opengisch/QgisModelBaker/files/3201098/test.zip)

We import with QGIS Model Baker and export Model PlanerischerGewaesserschutz_LV95_V1_1 again without any changes. The export fails according to incompatible values ([log_modelbaker.txt](https://github.com/opengisch/QgisModelBaker/files/3201109/log_modelbaker.txt))

Guess it's an ili2pg-Issue? Anyone any idea?

**Comment by pramisters** [comment]
Try to export with ili2pg (latest Version 3.12.2) alone (via command line).
The problem could be that ModelBaker uses ili2pg version 3.11.2.

**Comment by romefi** [comment]
Thanks @pramisters, that solved the problem. Export works fine with 3.12.2. @m-kuhn is an update to ili2pg 3.12.2 in pipeline?

**Comment by m-kuhn** [comment]
See this open discussion here where I'm waiting for feedback:
https://github.com/opengisch/QgisModelBaker/pull/290#issuecomment-479876944

We could also skip and directly go to ili2db 4 which should not have the same troubles.

**Comment by romefi** [comment]
Good points. Well be part of the discussion on Thursday

**Comment by pramisters** [comment]
Yes, update to ili2db 4.x
