### ISSUE TITLE
Relation editing: Separate linking from deleting / Avoid nested Forms

### ISSUE THREAD

**Issue by uncoyote** [opengisch/QgisModelBaker#307]
In the currently generated UI, it is hard to not be lost in the amount of UI-elements to edit the relations (and the object behind the relation).

Optimizations (see attached mockup)
* In the form for an object, only its immediate relations are displayed
* In the UI-folder for one relation is displayed
** On the left hand side: The links (The content of the link table for the selected object "W3")
** On the right hand side: The (main) attributes of the selected linked object "Baureg 7". IMPORTANT: For the selected linked object, only attributes are displayed, and not its relations, ...

Buttons in mockup from left to right:
* Create new link to existing Object: Opens window to select object to be linked
* Remove existing link: Removes the link of "W3" to "Baureg 7".
* Create new linked object: Opens window / workflow to create new object. After save, the new object will be linked to "W3".
* "Open": This button opens the selected linked object "Baureg. 7" in an new window. In this new window, the object can be deleted, it's relations can be edited, ...
![ghimage](https://user-images.githubusercontent.com/28384354/123695076-69e1e400-d85a-11eb-93e7-2afe8d3c35ce.jpeg)

**Comment by signedav** [comment]
I'm not sure if I understand this request. It's about:
- Not having relation editors in the child feature's form
- Not having the delete button
Correct?

**Comment by uncoyote** [comment]
@signedav A lot easier to answer your questions by phone - tomorrow would be good for me - tel 032 627 75 92

**Comment by signedav** [comment]
So it's mainly about separating the "dangerous" buttons like delete from the others, since there are a lot of buttons where the user could get confused. 

The other situation is with "endless" nesting of relation editor widgets, when there is a many to many relation where you need to be able to add referencing from "both sides".

**Comment by signedav** [comment]
Considering the endless nesting might make it a widget option "don't display in embedded forms".

**Comment by signedav** [comment]
This is actually already implemented. When having a "recursion" in the nested relation editors you see that there no relation editor displayed but only the information, that there would be one.

![image](https://user-images.githubusercontent.com/28384354/125432726-b2acd5c0-0777-4a86-9d18-64d02ef5ef31.png)

**Comment by signedav** [comment]
@uncoyote After those information is there still a request to have an "open" button?

**Comment by signedav** [comment]
@uncoyote feel free to reopen if it's still an issue.
