### ISSUE TITLE
Relation editing: Cascading delete link table entries

### ISSUE THREAD

**Issue by uncoyote** [opengisch/QgisModelBaker#308]
For a INTERLIS n:m relation, automatically delete the entries in the link tables when the "n" or "m" object is deleted. When an "m" remains without relations to "other n's" after deleting, show the user a list of the m's for subsequent cleanup.

Note: Deleting the m's without relation is probably difficult, as those m's could stand for "themselves" and or have other relations to take into consideration --> need's user brain

**Comment by romefi** [comment]
@signedav is this done?

**Comment by signedav** [comment]
Yes. But you have to define the signal strength properly.

```
  !! Komposition
    ASSOCIATION comp1 =
      comp1_a -<#> {0..1} ClassA1;
      comp1_b -- {0..*} ClassB1;
    END comp1;
    
  !! Aggregation
    ASSOCIATION agg1 =
      agg1_a -<> {0..1} ClassA1;
      agg1_b -- {0..*} ClassB1;
    END agg1;
    
  !! Assoziation
    ASSOCIATION assoc1 =
      assoc1_a -- {0..1} ClassA1;
      assoc1_b -- {0..*} ClassB1;
    END assoc1;
```

While the aggregation and the association is handled the same way in QGIS (association), the children are deleted on a composition. The signal strength is integrated here #422

Is the use of the strength intended in this request? If so, then go for closing it.

Thanks.

**Comment by romefi** [comment]
Thanks. 

In my understanding the relation strength is defined by the ili-model according to https://github.com/opengisch/QgisModelBaker/pull/422. I'll close this issue.
