### ISSUE TITLE
Relation editing: Show confirmation dialog for deleted children

### ISSUE THREAD

**Issue by uncoyote** [opengisch/QgisModelBaker#309]
In 1:n relations, show a confirmation dialog to confirm the deletion of the parent with it's children.

In the dialog, show a representative text for each relation/child that will be deleted.

"stupid" example: Deleting a car

Deleting this car will also delete it's related children
(Relation tyres)
* front left tyre
* front right tyre
* rear left tyre
* rear right tyre

(Relation swipers)
* front window swipers
* rear window swipers

**Comment by uncoyote** [comment]
What do we do with cascades?

If a tyre has a 1:n relation to it's screws. Do we delete the screws without asking?

**Comment by signedav** [comment]
Hi @uncoyote 
Does this solve the issue? 
https://github.com/qgis/QGIS/pull/36285
