### ISSUE TITLE
Relation editing: Select children to link on the map

### ISSUE THREAD

**Issue by uncoyote** [opengisch/QgisModelBaker#311]
Create a easy functionality to link several map objects to another (non geometric) object.

Ideas:
* Button in form "select linked geometries in map"
* Select geometries in map --> Link those throug dialog / context menu / ... to the (non geometric) object.

**Comment by m-kuhn** [comment]
This should work for 1:N relations with multi edit already. Is this approach not good enough (or not good enough documented) or is this for N:M relations=

**Comment by signedav** [comment]
@uncoyote I guess this is in the relation editor widget on "link existing child features", right?
Then this dialog opens: 
![image](https://user-images.githubusercontent.com/28384354/123684841-41ec8380-d84e-11eb-835c-d8d79f10170c.png)
Here you request to have a button "select geometries on the map"?

So #506 might be connected.

**Comment by signedav** [comment]
Input is considered in #506
