### ISSUE TITLE
Modal window problems

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#314]
Ein kleiner Verbesserungsvorschlag für Model Baker / QGIS: Wenn ein Fenster von Model Baker offen ist, das aber unter offenen Fenster von anderen Programmen vergraben ist, und man klickt auf das Haupt-QGIS-Fenster, dann springt der Fokus nicht zurück ins QGIS, sondern man muss zuerst das Model Baker Fenster «ausgraben» und drauf klicken. Erst dann ist der Fokus wieder im QGIS >> das wäre praktisch, wenn ein Klick aufs Haupt-QGIS-Fenster reichen würde….

**Comment by m-kuhn** [comment]
See how the attribute form of QGIS, measure tool etc. do that. (IIRC a window flag like `Qt::Dialog` or `Qt::Window`)

**Comment by signedav** [comment]
Das Fenster vom Modelbaker soll zwar offen bleiben, aber QGIS soll bedienbar sein, richtig?

**Comment by signedav** [comment]
Was ist denn das Hauptproblem? Dass wenn man QGIS zurück holt, das Modelbaker Fenster noch immer hinter anderen Fenster ist? 

PS. Ja, bei Ubuntu springt das Modelbaker Fenster in den Vordergrund, wenn QGIS fokusiert wird (wenn auch hier Verwirrung bestehen kann, wenn man es auf einem anderen Screen hat und QGIS nicht mehr bedienbar ist).

**Comment by m-kuhn** [comment]
> Was ist denn das Hauptproblem? Dass wenn man QGIS zurück holt, das Modelbaker Fenster noch immer hinter anderen Fenster ist ...

... und es darum nicht intuitiv ersichtlich ist, dass ein noch nicht abgeschlossener Workflow mit QGIS Model Baker besteht, wodurch QGIS blockiert ist.

**Comment by signedav** [comment]
Okay, alles klar.

Wobei ich von meinem anderen Input noch nicht überzeugt bin. Sollte man an QGIS weiterarbeiten können, wenn Modelbaker noch geöffnet ist. Das ist bei den meisten anderen Plugins der Fall (QFieldSync zBs.) - aber ist es nicht auch schön, wenn man den ModelBaker zuerst schliessen soll? Bin unschlüssig diesbezüglich.

**Comment by romefi** [comment]
Aus User-Sicht wäre es schön, wenn mit QGIS weiter gearbeitet werden kann, wenn Modelbaker offen ist. Oder kann das zu Konflikten führen, wenn an QGIS manipuliert wird, wenn gleichzeitig ein Modelbaker Prozess läuft?

**Comment by signedav** [comment]
Ich denke, dass wenn die Datenbank modifiziert würde (zBs. über den DB Manager gelöscht), die zuvor im Model Baker erkannt wird, dann könnte das zu Fehler führen. Aber ich denke das ist vergleichbar, wie wenn jemand von ausserhalb an der Datenbank modifiziert.

**Comment by romefi** [comment]
Denke dieses Risiko ist überschaubar, dann würde ich das so umsetzen, d.h. QGIS bleibt aktiv wenn Modelbaker offen ist.

**Comment by signedav** [comment]
Was soll passieren, wenn ein Model Baker Fenster zum Projektgenerieren, Exportieren oder Importieren offen ist, dann der Benutzer aber ein neues öffnen möchte (auf einen Icon klickt):
- Soll das alte Fenster geschlossen werden und das neue geöffnet? (e.g. ...)
- Sollen die Icons währenddem ein Fenster offen ist disabled sein? (e.g. QFieldSync) 
- Soll bei einem erneuten Öffnen ein Fenster aufgehen "A Model Baker window is already open"? (e.g. Lizmap plugin)

**Comment by m-kuhn** [comment]
oder

- Soll das alte Fenster in den Vordergrund gehoben werden

**Comment by signedav** [comment]
Es ist sowieso immer im Vordergrund wenn QGIS aktiv ist (nach dieser Implementierung), aber vielleicht auf einem anderen Screen @m-kuhn 

Aber eine weitere Funktion könnte sein:

- es passiert nichts (dann merkt der User, dass noch etwas offen ist)

**Comment by m-kuhn** [comment]
In diesem Fall

- toolbutton bleibt gedrückt (activated) solange das Fenster sichtbar ist

**Comment by signedav** [comment]
Oben 2. Möglichkeit wie beim QFieldSync... ja das fänd ich auch gut.
