### ISSUE TITLE
AssertionError while generating project

### ISSUE THREAD

**Issue by tschuettenberg** [opengisch/QgisModelBaker#316]
When loading from a certain PostGIS database I get the following python error:

```AssertionError 
Traceback (most recent call last):
  File "C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 318, in accepted
    project.create(None, qgis_project)
  File "C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dataobjects\project.py", line 106, in create
    assert rel.isValid()
AssertionError

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.4.8-Madeira Madeira, 04ee8e0761 

Python-Pfad:
C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python/plugins\gml_application_schema_toolbox\extlibs
C:/GEOSER~1/OSGEO4~1/apps/qgis-ltr/./python
C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python
C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python/plugins
C:/GEOSER~1/OSGEO4~1/apps/qgis-ltr/./python/plugins
C:\GEOSER~1\OSGEO4~1\bin\python37.zip
C:\GEOSER~1\OSGEO4~1\apps\Python37\DLLs
C:\GEOSER~1\OSGEO4~1\apps\Python37\lib
C:\GEOSER~1\OSGEO4~1\bin
C:\GEOSER~1\OSGEO4~1\apps\Python37
C:\GEOSER~1\OSGEO4~1\apps\Python37\lib\site-packages
C:\GEOSER~1\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\GEOSER~1\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\GEOSER~1\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python
C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default\python\plugins
```
Although reading the schema seems ok, as the model baker states
```Obtaining available layers from the database…
Obtaining relations from the database…
Arranging layers into groups…
Configuring forms and widgets…
Generating QGIS project…

90%...
```
I can not rule out, that there is something wrong with the schema (which I did not made myself). The model baker works on other databases/schemas though.
A similar looking (old) issue is #46, where layers were created more than once(?).

So, any ideas, what aspects of my schema I should check?

**Comment by m-kuhn** [comment]
Looks like it's something with relations between layers, but there's not much to go by yet. Maybe there is a relation with more than one schema involved? But that's really just a random guess.

**Comment by tschuettenberg** [comment]
hm, there is only one schema: public. 
It seems silly, but throughout the whole schema there are no geometrytypes or srids assigned to the geometry columns.
The assignment of the layer srid seems also to happen during the "Generating QGIS project…"-step and the SRS QGIS window comes up for every column. After serveral manual srs assignments the above error occures before finishing (could not catch the exact table yet).

**Comment by m-kuhn** [comment]
We have never tested with the schema public and I always discourage people from using it for their data. It's home for many system table which don't have any "real" project data and which shouldn't be managed by the user directly.

**Comment by tschuettenberg** [comment]
I agree, but can't avoid it in this case. The application generating the db/schema is not configurable in that way. - On the other hand I had no problems with other db's public-schemas so far.
Are there any known breaking points for model baker related to a schema configuration? What about size/complexity or number of db objects? (well, I don't think my schema is more complex than interlis ;-) )

**Comment by m-kuhn** [comment]
Nothing that I know of...

What you could do is edit this file:

  File "C:\Users\b4406621\AppData\Roaming\QGIS\geoservice\qgis-ltr\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dataobjects\project.py", line 106, in create

And output some more details about the failing relation.

    assert rel.isValid(), 'Referenced Layer {} Referencing Layer {}'.format(rel.referencedLayerId(), rel.referencingLayerId())

**Comment by tschuettenberg** [comment]
Thanks! now we get:
AssertionError: Referenced Layer baabentwaesserungsgebiet_958ce9de_4423_451e_917e_e7a046954bf9 Referencing Layer baabentwaesserungsgeb_ag_94c2b621_9c7e_45d6_be3c_70572852ddb8

baabentwaesserungsgeb_ag is empty and also has a self referencing foreign key. Maybe this is something, that makes the model baker choke on?

**Comment by tschuettenberg** [comment]
The problem seem to be caused by an empty referencing layer. I can reproduce the error in a fresh db consisting only of a referenced table/layer with some rows and an empty (i.e. no rows) referencing table with fk constraint.
(a self referencing fk constraint is not involved)

**Comment by m-kuhn** [comment]
That's surprising, when we generate interlis models, there are a lot of referencing layers and all these tables are always empty and I don't remember seeing that issue before.

**Comment by tschuettenberg** [comment]
just out of curiosity I just deleted (all) the geometry columns on the tested (and still empty) referencing table (to mimic a simple look up attribute tabel) and model baker worked.

**Comment by m-kuhn** [comment]
Do I read it correct that there were multiple geometry columns on the self-referencing table? That also might be a hint for the issue.

**Comment by tschuettenberg** [comment]
No self-reference here.
Even multiple geometry columns on the referencing table are ok, as long as all of them have a explicit geometry type! -> https://postgis.net/docs/using_postgis_dbmanagement.html#geometry_columns

If one column is of type "GEOMETRY" only, it breaks. This holds true even if the referencing table is NOT empty. 

Clearly this is the fault of the model, not the baker. - Unfortunatly this is what happens everywhere in the model/schema I wanted to 'bake' in the first place.  :-(

**Comment by m-kuhn** [comment]
> If one column is of type "GEOMETRY" only, it breaks.

So this is the culprit? Good analysis!

**Comment by tschuettenberg** [comment]
yes, I think so. 
Dont't know if model baker could or even should compensate that. - 99% of the time one knows the applicable geometrytype to register, right?
Thanks for your help. Cheers!

**Comment by m-kuhn** [comment]
Yes, it could compensate for that.
But only if it's important enough for someone to invest into the bugfix.
