### ISSUE TITLE
Import erroneous data

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#318]
Sometimes it would be helpful to be able to import erroneous data (xtf).

This is a collection of ideas:

- Remove `--createNumChecks` (schemaimport)
- Specify `--sqlEnableNull` (schemaimport)
- Specify `--disableValidation` (import)
- Remove `--createFkIdx` (or `--createFk`?) (schemaimport)
- Remove `--createUnique` (schemaimport)

Open questions, how to detect when this is required, define workflow.

**Comment by m-kuhn** [comment]
Partially implemented (only the options which are available at import/export, not yet those that affect the schema creation)

**Comment by romefi** [comment]
- New option "disable all constraints"
- Option always disabled at start Model Baker
- Warning message box when option ist enabled and schema generation ist started

**Comment by signedav** [comment]
In this PR #424 we have  the "Import without validation" and "Export without validation" option already available before the normal import/export failed. 

1. Question: Besides there is the flag `--disableValidation` active, does something else be done to have an import/export without validation?

2. Question: Should there be a "Create without validation" option in the schema import containing `--sqlEnableNull` and not containing `--createNumChecks`, `--createFkIdx` / `--createFk`, `--createUnique`

Whgat do you think @m-kuhn ?

**Comment by m-kuhn** [comment]
> 1. Question: Should there be a "Create without validation" option in the schema import containing --sqlEnableNull and not containing --createNumChecks, --createFkIdx / --createFk, --createUnique
I am not aware of anything

> 2. Question: Should there be a "Create without validation" option in the schema import containing `--sqlEnableNull` and not containing `--createNumChecks`, `--createFkIdx` / `--createFk`, `--createUnique`

That sounds very interesting!
I would open a new issue for this.
And a second (follow up) one "if a schema has been created without constraints" (or however you want to call that) --> we should still allow to show constraints to be able to help the user fix the data in the unconstrained schema. But the constraints in qgis are not shown because they are read from the database.

**Comment by signedav** [comment]
So you suggest to make an issue, with implementation: "Import schema without validation" as a follow up of #424

And one for the problems when this has been done "Handling constraints when they are not defined in the DB"

And close this one? Or does this includes other things?

**Comment by signedav** [comment]
Closing it because opened new issues #427 and #428
