### ISSUE TITLE
Cannot export from gpkg

### ISSUE THREAD

**Issue by p1d1d1** [opengisch/QgisModelBaker#321]
Error: Object 1: failed to convert surface/area
Error:   com.vividsolutions.jts.io.ParseException: Unknown WKB type 235
Error:     Unknown WKB type 235
Error: line 0: swissBOUNDARIES3D_ili1_LV95_V1_3.TLM_GRENZEN.TLM_KANTONSGEBIET: tid 1: Attribute Shape requires a value
Info: swissBOUNDARIES3D_ili1_LV95_V1_3.TLM_GRENZEN.TLM_LANDESGEBIET...
Info: second validation pass...
...export failed
Finished (1)

**Comment by m-kuhn** [comment]
It's hard to say what exactly went wrong here.
We would need to have a look at the data itself.

**Comment by p1d1d1** [comment]
1. Generate a project with this model: swissBOUNDARIES3D_ili2_LV95_V1_3
2. Add a record into the layer tlm_landesgebiet
3. Try to export
4. I get:
`
C:\Program Files (x86)\Java\jre8\bin\java -jar C:\Users\U80822104\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libili2db\bin\ili2gpkg-3.11.3\ili2gpkg.jar --dbfile //adb.intra.admin.ch/UserHome$/..../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/sb3d.gpkg --export --exportModels swissBOUNDARIES3D_ili2_LV95_V1_3 --proxy ... --models swissBOUNDARIES3D_ili2_LV95_V1_3 //adb.intra.admin.ch/UserHome$/...../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/INTERLIS_2_LV95_LN02/export.xtf
Info: dburl <jdbc:sqlite://adb.intra.admin.ch/UserHome$/..../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/sb3d.gpkg>
Info: dbusr <>
Info: ili2gpkg-3.11.3-20180413
Info: ili2c-4.7.7-20180208
Info: iox-ili-1.20.2-b58e2371ea1155aa3e4f5ff0b86d2432824b151b
Info: java.version 1.8.0_211
Info: user.name <user>
Info: maxMemory 253440 KB
Info: currentTime 2019-07-17 15:46:32
Info: dburl <jdbc:sqlite://adb.intra.admin.ch/UserHome$/..../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/sb3d.gpkg>
Info: dbusr <>
Info: databaseProduct <SQLite>
Info: databaseVersion <3.8.11>
Info: driverName <SQLiteJDBC>
Info: driverVersion <native>
Info: compile models...
Info: httpProxyHost <proxy-bvcol.admin.ch>
Info: httpProxyPort <8080>
Info: lookup model <swissBOUNDARIES3D_ili2_LV95_V1_3> in repository <jdbc:sqlite://adb.intra.admin.ch/UserHome$/..../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/sb3d.gpkg>
Info: lookup model <CoordSys> 2.3 in repository <jdbc:sqlite://adb.intra.admin.ch/UserHome$/.../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/sb3d.gpkg>
Info: ilifile <C:\Users\U80822104\.ilicache\jdbc&003asqlite&003a\adb.intra.admin.ch\UserHome$\.\config\Desktop\TestINTERLIS1-QGIS\ModeBaker\sb3d.gpkg\CoordSys-20151124.ili>
Info: ilifile <C:\Users\U80822104\.ilicache\jdbc&003asqlite&003a\adb.intra.admin.ch\UserHome$\...\config\Desktop\TestINTERLIS1-QGIS\ModeBaker\sb3d.gpkg\swissBOUNDARIES3D_ili2_LV95_V1_3.ili>
Info: process data...
Info: data <//adb.intra.admin.ch/UserHome$/.../config/Desktop/TestINTERLIS1-QGIS/ModeBaker/INTERLIS_2_LV95_LN02/export.xtf>
Info: assume unknown/external objects
Info: first validation pass...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_HOHEITSGRENZE...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_HOHEITSGEBIET...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_BEZIRKSGEBIET...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_KANTONSGEBIET...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_LANDESGEBIET...
Error: Object 1: failed to convert surface/area
Error:   com.vividsolutions.jts.io.ParseException: Unknown WKB type 235
Error:     Unknown WKB type 235
Error: line 0: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_LANDESGEBIET: tid 1: Attribute Shape requires a value
Info: second validation pass...
...export failed
Finished (1)
`

**Comment by pramisters** [comment]
The problem could be the missing Z (height) values of the geometry attribute TLM_LANDESGEBIET.Shape (see model definition). You have to make sure that you enter and store the Z values when adding the geometry in QGIS.

**Comment by p1d1d1** [comment]
I don't see how

**Comment by m-kuhn** [comment]
Right click a vertex -> open vertex editor -> fill Z values.

**Comment by p1d1d1** [comment]
All Z values are set to 0, which is a valid value. By the way, changed those 0 to some values.
Same error message

**Comment by p1d1d1** [comment]
Did a quick test with the model "Alpenkonvention", which is quite simple. I could add a feature and export.

**Comment by m-kuhn** [comment]
Retested with the model `swissBOUNDARIES3D_ili2_LV95_V1_3`, QGIS 3.16.0 and QGIS model baker version 6.3. I couldn't reproduce any issue.

```
java -jar /home/mkuhn/dev/QgisModelBaker/QgisModelBaker/libili2db/bin/ili2gpkg-4.4.3/ili2gpkg-4.4.3.jar --dbfile /tmp/sbd.gpkg --export --models swissBOUNDARIES3D_ili2_LV95_V1_3 /tmp/abd.xtf
Info: dburl <jdbc:sqlite:/tmp/sbd.gpkg>
Info: dbusr <>
Info: ili2gpkg-4.4.3-658b7daf37ba45ed2330ca3e3a3c3d59c96e91fa
Info: ili2c-5.1.0-20200501

Info: iox-ili-1.21.0-731076775d8b9bd0599802cf5a0324bc3a1c21d8
Info: java.version 11.0.9
Info: user.name <mkuhn>
Info: maxMemory 4034560 KB
Info: currentTime 2020-11-24 17:56:25
Info: dburl <jdbc:sqlite:/tmp/sbd.gpkg>
Info: dbusr <>
Info: databaseProduct <SQLite>

Info: databaseVersion <3.8.11>
Info: driverName <SQLiteJDBC>
Info: driverVersion <native>
Info: compile models...
Info: lookup model <swissBOUNDARIES3D_ili2_LV95_V1_3> in repository <jdbc:sqlite:/tmp/sbd.gpkg/>
Info: lookup model <CoordSys> 2.3 in repository <jdbc:sqlite:/tmp/sbd.gpkg/>
Info: ilifile </home/mkuhn/.ilicache/jdbc&003asqlite&003a/tmp/sbd.gpkg/CoordSys-20151124.ili>
Info: ilifile </home/mkuhn/.ilicache/jdbc&003asqlite&003a/tmp/sbd.gpkg/swissBOUNDARIES3D_ili2_LV95_V1_3.ili>
Info: process data...

Info: data </tmp/abd.xtf>
Info: assume unknown external objects
Info: first validation pass...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN BID <swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN>...

Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_HOHEITSGRENZE...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_HOHEITSGEBIET...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_BEZIRKSGEBIET...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_KANTONSGEBIET...
Info: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_LANDESGEBIET...
Info: second validation pass...
Info: abd.xtf: swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN BID=swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN

Info:       1 objects in CLASS swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_KANTONSGEBIET

Info:       1 objects in CLASS swissBOUNDARIES3D_ili2_LV95_V1_3.TLM_GRENZEN.TLM_LANDESGEBIET
Info: ...export done
Finished (0)
```

@p1d1d1 does the issue persist for you? If yes, would you be able to attach the gpkg that you are exporting?

**Comment by p1d1d1** [comment]
Working also here. Thanks
