### ISSUE TITLE
AttributeError when starting Model Baker with QGIS 3.8

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#323]
Starting Model Baker with QGIS 3.8 gives this message:

![image](https://user-images.githubusercontent.com/26796989/61369208-ebb7ed00-a88f-11e9-8bd6-5df10ff4836e.png)

Seems to works properly after closing the window. Appears also in Beta 5.0.0.

**Comment by m-kuhn** [comment]
Also here... Started (very) recently. I guess it's a change in a repository.

**Comment by m-kuhn** [comment]
Seems to be http://models.geo.llv.li/ilimodels.xml

```
<IliRepository09.RepositoryIndex.ModelMetadata TID="1"><Name>DM01AVFLLV95V41</Name><SchemaLanguage>ili1</SchemaLanguage><File>ABI/DM01AVFLLV95V41.ili</File><Title>Datenmodell der AV</Title><md5>F449F88EAA545DBB9DDFA63E4E7B38B6</md5></IliRepository09.RepositoryIndex.ModelMetadata>
```

Model Baker is not prepared to find ModelMetadata without version
