### ISSUE TITLE
Cannot generate with version 4.3.1

### ISSUE THREAD

**Issue by p1d1d1** [opengisch/QgisModelBaker#325]
After updating to 4.3.1 cannot generate more than once.

1) Generate with source = Interlis (use GeoPackage) --> ok
2) Close QGIS --> Reopen
3) Launch the generate wizard --> choose a different model
4) It is not possible to save in a new gpkg file

**Comment by m-kuhn** [comment]
Works fine here. What exactly happens in "4. It is not possible to save in a new gpkg file"?

**Comment by p1d1d1** [comment]
It is not possible to save in a new gpkg. An "Open" button is showed instead of a "Save".
I'm on Windows 10

**Comment by pramisters** [comment]
Works fine here as well.
What are your exact steps in Point 4?

**Comment by p1d1d1** [comment]
I cannot save in a new gpkg. Cfr. the window title is "Open GeoPackage database file"

![immagine](https://user-images.githubusercontent.com/1533649/62206450-22166180-b392-11e9-9077-b7b63cf0d902.png)

**Comment by gacarrillor** [comment]
Confirmed! This happens following these steps:

1. Open the `Generate Project` dialog.
2. Choose `GeoPackage` source. (here the interlis_mode is set to False)
3. Choose `Interlis (use GeoPackage)` source. (here the interlis_mode is never set back to True)
5. Click on the `...` button along the `Database file` textbox.
