### ISSUE TITLE
Cannot connect to PostGIS

### ISSUE THREAD

**Issue by p1d1d1** [opengisch/QgisModelBaker#326]
Trying to generate via INTERLIS (PostGIS) cannot connect to DB.
I get the following error message:
[log.txt](https://github.com/opengisch/QgisModelBaker/files/3431801/log.txt)

With the same configuration I can connect without any problem via the PostGIS provider.
Could you please help debugging this?

**Comment by m-kuhn** [comment]
@p1d1d1 can I drop by tomorrow morning to have a look at some of the issues on site?

**Comment by pramisters** [comment]
This is not a ModelBaker issue.

From the log I see that you entered host/user/db.
These are not valid credentials of your database, are they?
At least "host" as host is missing in the pg_hba.conf (client authentication)

Could you paste (screenshot) what you entered in the "Generate Project" dialog?

**Comment by p1d1d1** [comment]
host/user/db have been "faked" in the log.
In the ModelBaker we use the same credential used for a normal connection to PotGIS via the PostGIS provider

**Comment by pramisters** [comment]
Whatever credentials you used. The error remains the same and is clear: The host name you provided is missing in the pg_hba.conf.

**Comment by m-kuhn** [comment]
This seems to be a server configuration issue (see https://dba.stackexchange.com/a/84002/170323)

@p1d1d1 can we close this?

**Comment by p1d1d1** [comment]
Ok, i'll do some more testing, but you can close it. thanks

**Comment by m-kuhn** [comment]
Please reopen if necessary
