### ISSUE TITLE
OID / t_ili_tid generated values depending on model definition

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#340]
Models (TOPICS) are allowed to define which kind of OID they use.

- STANDARDOID
- UUIDOID
- I32OID
- ANYOID

These values should be generated automatically when adding new objects.

TODO:

- [ ] Verify assumption about OID definition (topic based etc)
- [ ] Verify ili2db mapping of OID (OID / t_ili_tid are equivalent)
- [ ] Check how things work with different OID types in gpkg and pg
- [ ] Add configuration option for STANDARDOID prefix (on the database or in the frontend / QGIS)
- [ ] Create default values for different OID types either in QGIS or in the backend default value definition

References https://github.com/opengisch/QgisModelBaker/issues/281 (UUIDOID in gpkg) and https://github.com/opengisch/QgisModelBaker/issues/210 (STANDARDOID)

**Comment by m-kuhn** [comment]
A discuter

**Comment by signedav** [comment]
See https://gist.github.com/signedav/fd2426650230e2c4eabf3958aee14cc9
