### ISSUE TITLE
data in one column, instead of two, in the form

### ISSUE THREAD

**Issue by saeri-ims** [opengisch/QgisModelBaker#350]
Hello,

it is possible to modify the design of the form? For instance, it is possible to have all the elements within the form displayed in one column and not distributed into two? (see attached form which has two columns and that i would like to have in one). 
My question is based on several requests from people using model baker to enter their data and find very difficult to deal with the design of the form. (note there is no issue with the widgets, they really work well!). 
Thank you very much
![Screenshot from 2019-11-07 14-42-22](https://user-images.githubusercontent.com/42073830/68398556-d8959980-016c-11ea-8bfd-c8930e2e7347.png)

**Comment by m-kuhn** [comment]
This is not currently possible and will need manual changes in the QGIS project.

This could be done in different ways:

- Based on the number of attributes (see https://github.com/opengisch/QgisModelBaker/issues/196)
- Based on an Interlis meta attribute
- Through an InterlisPlus shared qml/meta attribute ini
- Through a global "default # of columns" setting, which will apply everywhere

Looking at your screenshot and assuming that you don't use Interlis, the last option would be your favorite?

**Comment by m-kuhn** [comment]
Status quo is: with less than 6 attributes it will be in one single column.
