### ISSUE TITLE
ili2db4 - BAG OF Value Relations not supported anymore

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#359]
With ili2pg4 the BAG_OF columns creating Value Relation Widgets are no longer suported.

How comes?
While with ili2db3 the `domain_relation_generator` creates the domain relations, with ili2db4 that's not needed anymore since the relations are created by ili2db. But the BAG_OF_ENUM list is not created, since this has been part of the `domain_relation_generator`. 
So first thing would be to bring the functionality back to get the BAG_OF_ENUM list.

If so, then there is another challenge. 
While the `domain_relation_generator` used the string-column `ilicode` as the key column in BAG_OF_ENUM (and then the Value Relation Widget) the column for the BAG_OF in ili2db4 is created is not a string-array anymore (`bigint[]` instead of `character varying(255)[]`). There is a suggestion to implement this column as a JSON-field, but not really cared about claeis/ili2db#218 Could we just use the `t_id` instead, or why we decided for `ilicode`? 
Using another key could lead to issues on data migration from ili2db3 schema to ili2db4 schema...

**Comment by gacarrillor** [comment]
Yes, this is missing in Model Baker with ili2db4. I think the required BAG OF details could be extracted by some queries. If we have a M:N relationship pointing to a Domain table, then we have a BAG OF. However, this could also be exposed by @claeis in a meta-attribute table (for instance, it might be great to access the optionality of the BAG OF easily, something I think we miss once is in PostgreSQL, see https://github.com/claeis/ili2db/issues/171). What do you think about it Claude?

Concerning the key column, right, we should go for the t_id when defining the Value Relation's key. When migrating, we could need to convert the ilicodes we store as PostgreSQL arrays to their corresponding t_ids. Does that make sense @m-kuhn?

Two things to keep in mind: 
 + If we don't find the ili2db.mapping=ARRAY tag-setting pair in the meta-attrs table for a particular attribute, we don't set the Value Relation.
 + If the schema import was run without the `--createEnumTabsWithId` option, then we won't have the foreign keys in the DB. In that case, the queries I mentioned above won't work. Should we still support BAG OF ENUMs in that case?

**Comment by signedav** [comment]
> If the schema import was run without the --createEnumTabsWithId option, then we won't have the foreign keys in the DB. In that case, the queries I mentioned above won't work. Should we still support BAG OF ENUMs in that case?

As I can see that you pass it in Modelbaker on version 4 per default. And we have no option to turn it off. If so, then I think it's fine not creating BAG OF ENUM, when it's missing.

**Comment by signedav** [comment]
I see the following behavior with ili2db 4 and Model Baker.

This example model: https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/tests/testdata/ilimodels/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.ili

We have this class with this attribute
```
		CLASS Erholungsinfrastruktur_Punktobjekt EXTENDS Punktobjekt = 
			!!@ili2db.mapping=ARRAY
			Typ: BAG {1..*} OF EI_Punkt_Typ;
```

What we have:
1. a table `Erholungsinfrastruktur_Punktobjekt` with a `bigint[]`-column called `Typ`
2. the table `t_ili2db_meta_attrs` with the value `ZG_Naturschutz_und_Erholungsinfrastruktur_V1.Geodaten.Erholungsinfrastruktur_Punktobjekt.Typ` in the column called `ilielement` and the information `ili2db.mapping` `ARRAY`
3. a relation called `ei_punkt_typ_ei_punkt_typen_fkey` with referencing layer `ei_punkt_typ` and referenced layer `ei_punkt_typen` and referenced field `t_id`

What we need:
On creating the widgets we should recognize the attribute `typ` on layer `Erholungsinfrastruktur_Punktobjekt` as a ValueRelation. We have to configure this ValueRelation with the referenced layer `ei_punkt_typen` and the value field `t_id` and key field static disp_value.

How we can do it:
1. Get the information if the field is a BAG OF from the table `t_ili2db_meta_attrs` (parse the field `ilielement`)
2. Get the information what is the correct relation *
3. Get the layer and the value field from this relation

* On 2 we need to know that the table we need is `ei_punkt_typ` according to `typ`. Is there a way to get this information from the database?

**Comment by signedav** [comment]
Just fount the table `t_ili2db_column_prop` with the columns:
"erholungsinfrastruktur_punktobjekt","typ","ch.ehi.ili2db.foreignKey","ei_punkt_typen"

With this information we actually have all we need :slightly_smiling_face:

**Comment by signedav** [comment]
So we will get the data from the meta tabels for:
- currentlayer
- attribute
- target_table

And we define the:
- key_field: t_id
- value_field: dispname

What we don't have is the cardinality.

Is there a case that a BAG OF with the mapping-attribute ARRAY is not a one-to-many relation?

**Comment by m-kuhn** [comment]
> Is there a case that a BAG OF with the mapping-attribute ARRAY is not a one-to-many relation?

I think it's safe to assume it always is for now. If not we will fix it down the road.

**Comment by signedav** [comment]
Arg. It can be a 0..* cardinality...

**Comment by gacarrillor** [comment]
> 
> What we don't have is the cardinality.
> 
> Is there a case that a BAG OF with the mapping-attribute ARRAY is not a one-to-many relation?

See https://github.com/claeis/ili2db/commit/58b5d44e54c7df66c8bb18f99ecc8c88e1204997

**Comment by signedav** [comment]
Great. Thanks @gacarrillor

**Comment by signedav** [comment]
Just wondering: 

Could it be possible that `0..*` has still never been used before for value relation widget configurations?

Because what is expected to be configured? 
Of course _allow null_ and _multi selection_. But on _multi selection_ there is no `NULL` value. It's an empty array (!=`NULL`).

So the _allow null_ is used when it's not a _multi selection_ (on `0..1`). But then I guess it's not an `ARRAY`. What means there is no value relation configured in model baker but a relation reference instead. Right?



Just wondering. What is the case when it's a 0..*? 
There is "no selection" allowed? If so, then how is this implemented in the QGIS configuration? I guess not yet implemented.
What is the "allow null"?`It's when null is allowed. But this is never allowed on multi selection in QGIS since the content is always a list with no values like `{}` or `[]`.
