### ISSUE TITLE
Import with delete existing data confusion

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#361]
On data import there is the nice possibility to delete or keep existing data controlled over the checkbox. I made the mistake by leaving it checked after I imported catalogue data and wanted to import my real data. I kind of assumed  that it would nod delete the catalogue data. My mistake, for sure, but still I think maybe we could improve something here.

At least add a tooltip. But another thing would be to have this option only when there is actually existing data. So the user knows that something will be deleted in fact.
And another step would be that there are options for "delete all data" / "delete catalogue data" / etc...

**Comment by romefi** [comment]
- add tooltip
- further specification later, as quite complex with baskets etc.
