### ISSUE TITLE
Implement ili2db-option --skipPolygonBuilding and --keepAreaRef for Interlis1-Export

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#364]
AREA-Geometries in Interlis 1-Models can't be exported without errors. It should be possible to set the options `--skipPolygonBuilding` and `--keepAreaRef` at export

**Comment by webrian** [comment]
Both options need to be included at generate (aka `--schemaimport`) and import as well

**Comment by claeis** [comment]
- ```--skipPolygonBuilding``` reads the ITF as it is (linetables and area refs; no polygons).
- ```--keepAreaRef``` is an addon to the normal import (that builds polygons) and reads in addition to the polygons the area refs (the area refs have no semantic according to the interlis specification; must not be the same at export time)

Using this two options together is wrong.

**Comment by m-kuhn** [comment]
Thanks for the clarification @claeis 
@webrian can you test the current beta version (based on ili2db 4.4): https://github.com/opengisch/QgisModelBaker/releases/tag/v5.0.0-rc1 -> install the plugin in qgis from zip file.

I imported and exported to/from gpkg without any errors.

**Comment by claeis** [comment]
There is an issue with ITF AREA export (claeis/ili2db#326)
