### ISSUE TITLE
Models can't be deselected at export

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#371]
In Model Baker 5 RC 1, when I want to export an XTF, it shows all models available in the schema. All models are selected. It's not possible to deselect a model. Nothing happens when I click on the checkbox.

![image](https://user-images.githubusercontent.com/26796989/73842460-e8c91d80-481c-11ea-8633-6bd3e5c9325f.png)

**Comment by m-kuhn** [comment]
Confirmed also on Model Baker 6-rc2
