### ISSUE TITLE
Model Baker 5 RC1 still on ili2db 3?

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#372]
Tried to generate a new schema with project based on model `planerischergewaesserschutz_lv95_v1_1` and noticed Model Baker 5 RC1 still works (only) with ili2db 3.

![image](https://user-images.githubusercontent.com/26796989/73844114-31cea100-4820-11ea-9e2a-56549284de87.png)

In Folder `C:\Users\rfill\AppData\Roaming\QGIS\QGIS3\profiles\modelbaker_5\python\plugins\QgisModelBaker\libili2db\bin` is no ili2pg 4, only ili2pg3.

![image](https://user-images.githubusercontent.com/26796989/73844321-a570ae00-4820-11ea-928f-1651f8436d1d.png)

Am I missing something?

**Comment by signedav** [comment]
I'm checking.

**Comment by m-kuhn** [comment]
Confirmed.
A new version Model Baker 6 RC 2 has been released.
We are very sorry for the inconvenience!
