### ISSUE TITLE
Model Baker 6 RC4: Can't import data

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#381]
Tried to import http://models.geo.admin.ch/BAFU/PlanerischerGewaesserschutz_Codetexte_V1_1.xml. Get this error:
![image](https://user-images.githubusercontent.com/26796989/74717899-7c451a00-5231-11ea-8280-3b65e11b9a90.png)

Any idea why?

**Comment by m-kuhn** [comment]
- Was the schema also created with this version of model baker? (i.e. ili2pg version 4)
- Are there other models in the same schema?

**Comment by romefi** [comment]
There was no schema created in advance. Shouldn't the schema be created while import, when schema don't exist already?

**Comment by m-kuhn** [comment]
With ili2db3 this was executed implicitly, with ili2db4 no longer. It's likely related to some missing implementation in model baker to compensate for this change in ili2db.

**Comment by m-kuhn** [comment]
Is this a blocker for a final release?

**Comment by romefi** [comment]
Hm, that's a pity ili2db 4 doesen't execute it anymore... Would it be possible to give an info when schema doesn't exist? To generate schema before importing data? If it was possible before, the user should get an information instead of the error now.

Is there a chance to put this into the final release? For the future we should discuss how we can solve this proper.

**Comment by gacarrillor** [comment]
Suggestion (perhaps not for the next release):

1. Make the Generate dialog able to receive a "models" parameter.
2. When importing data, check if the schema exists. 
3. If it doesn't. Read models from XTF and show a button to call Generate dialog passing the "models" parameter.

Optional:
4. After running a Generate successfully, show a button to call the Import Data dialog.

**Comment by romefi** [comment]
Thanks @gacarrillor, sounds good to me. Nr. 4 would also be very nice.

Still, are we able to set a information or warning if someone tries to import data without existing model?

**Comment by m-kuhn** [comment]
@gacarrillor good idea.

concerning number 2, while on it I think we better also check if the schema contains the correct datamodel / model version?

Concerning number 3 and 4, if both are implemented, there is a lot of inter-connection between generate and import. It opens up the question if they could be integrated (one dialog where model to generate and a list of files to import can be defined. The "generate schema" step should be optional (checkbox) and linked to the existence of this model in the chosen target schema, the idea still needs to be fleshed out completely.)

Concerning the warning, this needs to be implemented for each data source (pg, gpkg, mssql) separately. Let's postpone the release by one more week to get a solution for this!

**Comment by m-kuhn** [comment]
Actually, the import process is covered by unit tests.
I wonder if my first assumption is really true and why they did not detect this :thinking:

**Comment by romefi** [comment]
True, between generate and import is al lot of inter-connection. I would support the idea to integrate the import in generate, as it often needs both and the workflow now is not very smooth. Also the ability to import more than one file. Often it's a catalogue followed by the data which should be imported. 

It needs to be fleshed out, not sure if we can do that in one week. Let's discuss this on our call tomorrow.

**Comment by m-kuhn** [comment]
Workaround with a message proposed in #387 

I am not very happy with it, but it should be ok as a band aid.

Meeting with @romefi scheduled for end of March to come up with a better overall approach.
