### ISSUE TITLE
Export Interlis: Models not listed when choosing PostGIS as source

### ISSUE THREAD

**Issue by kingemir** [opengisch/QgisModelBaker#384]
I did some Interlis imports, both into Geopackage and Postgis. 
When I want to export interlis from Geopackage, some of the used models during the import are listed in the UI. Where does the plugin search for these models?
The problem is that when I want to export interlis from PostGIS, no models are listed.
![grafik](https://user-images.githubusercontent.com/19539230/75543827-f8eeaa00-5a22-11ea-9c46-68cc08df974b.png)

![grafik](https://user-images.githubusercontent.com/19539230/75543785-e6747080-5a22-11ea-863a-d284a5ae7cc5.png)

**Comment by m-kuhn** [comment]
Can you give it a try with the [latest release candidate](https://github.com/opengisch/QgisModelBaker/releases/tag/v6.0.0-rc4) (install the plugin from zip).

We have reworked this list recently.

**Comment by kingemir** [comment]
Thanks for the fast reply. I tested with the latest release candidate. The used ili model is now showing in the list. But my question remains: Which step needs to be undertaken exactly in order to let a ili model be showed in the list? Is it ModelBaker->Generate? Does this step save an entry about which models have been used somewhere?

**Comment by m-kuhn** [comment]
Yes, the generation step saves this information into meta tables in the database.
