### ISSUE TITLE
How does the definition of the srid work during import?

### ISSUE THREAD

**Issue by kingemir** [opengisch/QgisModelBaker#385]
When using the plugin for importing Interlis, the UI doesn't ask which srid should be used. How does the definition of the srid work during import? I encountered one case where a wrong srid has been used. 

- the AV data of the commune of Bettingen BS have been ordered from the cantonal geoportal: the corresponding ili model is delivered together with the interlis transfer file xtf
- an Interlis import into postgis has been done using the plugin ModelBaker (schema name: `bettingen_av_200227`)
- the tables in the postgis schema `bettingen_av_200227` are created without error
- the geometry tables in the postgis schema `bettingen_av_200227`  have all srid `21781`, but the srid should be `2056`

I can update the wrong entries using pgAdmin, but this is cumbersome since I have to run following SQL script for each table individually (the example below is for the table `liegenschaft`: 

`ALTER TABLE bettingen_av_200227.liegenschaft
  ALTER COLUMN geometrie
    TYPE geometry(polygon, 2056)
    USING ST_SetSRID(geometrie, 2056);`

**Comment by m-kuhn** [comment]
Use generate before import.

**Comment by kingemir** [comment]
Thanks. It worked.
