### ISSUE TITLE
Attribute mit Auswahllisten

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#39]
Bei  Attributen mit Auswahllisten (im Modell explizit als DOMAIN oder implizit definiert)  fehlt jegliche Verknüpfung mit den Auswahllisten (aktuell: Widget "Texteditor" im Formular). Sie sollen mit dem Widget "Wertbeziehung" definiert werden (Schlüsselspalte "itfcode"; Wertspalte "dispname"). Es stellt sich allerdings die Frage, wo in den ili2pg-Metadaten in der DB der Projektgenerator erkennen kann, welches Attribut überhaupt eine Auswahlliste hat und wie die entsprechende Tabelle heisst.  Diesbezüglich frage ich mich, warum ili2pg in der DB auf dem Attribut kein Fremdschlüssel auf die Auswahlliste definiert. Werden die Auswahllisten nicht als DOMAIN sondern als externe Kataloge modelliert, wird ein Fremdschlüssel erzeugt.

Attribute  mit Auswahllisten sollen immer als INTEGER modelliert werden. Dafür gibt es die Option --createEnumColAsItfCode in ili2pg

**Comment by m-kuhn** [comment]
> Bei Attributen mit Auswahllisten fehlt jegliche Verknüpfung mit den Auswahllisten (aktuell: Widget "Texteditor" im Formular). Sie sollen mit dem Widget "Wertbeziehung" definiert werden (Schlüsselspalte "itfcode"; Wertspalte "dispname").

Auf der Todoliste

> Attribute mit Auswahllisten sollen immer als INTEGER modelliert werden. Dafür gibt es die Option --createEnumColAsItfCode in ili2pg

Wenn ich mich mich richtig erinnere ist dies ein "Relikt" aus der Interlis 1 Zeit und es ist schwierig damit bei vererbten und erweiterten Wertelisten umzugehen.
Was ist der Vorteil von integer?

**Comment by pramisters** [comment]
Dass Auswahllisten über Integer-Werte referenziert werden, ist Standard bei vielen Fachschalen. Der wichtigste Grund ist: Wenn ein Auswahllistenwert ändert, muss nur an einer Stelle (in der Auswahlliste selbst) mutiert werden. Wenn die Auswahllistenwerte selbst (i.d.R. Text) in die Objekte geschrieben werden, muss jedes Objekt angefasst werden. 
Zumindest muss diese ili2pg-Option im Projektgenerator zur Verfügung stehen, ansonsten ist er für mich nur schon aus diesem Grund nicht brauchbar.
Ich denke, man wird nicht darum herumkommen, die meisten für die Schemaerstellung relevanten ili2pg-Optionen im Projektgenerator zur Verfügung zu stellen (z.B. mittels Optionsfenster, wo man die Optionen zusammenklicken kann).

**Comment by m-kuhn** [comment]
Wenn dies ein absolutes Muss ist und gute Gründe dafür sprechen, werden wir das einführen.

> Wenn ein Auswahllistenwert ändert, muss nur an einer Stelle (in der Auswahlliste selbst) mutiert werden.

Das sollte eigentlich genau gleich einfach oder schwierig sein, egal was für ein Datentyp der Primärschlüssel hat.

> Dass Auswahllisten über Integer-Werte referenziert werden, ist Standard bei vielen Fachschalen. 

Dann steht es diesen Fachschalen frei, ili2pg selbst zu integrieren. Und dem Nutzer, aus der daraus erzeugten Datenbank mit dem Projektgenerator ein Projekt zu erzeugen (mit der Option "postgis" anstatt "interlis")

> Ich denke, man wird nicht darum herumkommen, die meisten für die Schemaerstellung relevanten ili2pg-Optionen im Projektgenerator zur Verfügung zu stellen (z.B. mittels Optionsfenster, wo man die Optionen zusammenklicken kann).

Siehe auch #25
