### ISSUE TITLE
Project generation should offer to use authconfig

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#391]
We should avoid storing usernames/passwords in QGIS projects generated by Model Baker.

Model Baker should offer (by default) to use one of the existing authconfig configurations.

**Comment by m-kuhn** [comment]
Thanks @andreasneumann we will have a look at this next month.

I think we will have a global configuration option to specify the authid. If this is set, it will be used instead of username / password.
Is this a good way for you?

**Comment by andreasneumann** [comment]
Sounds good to me.

@schmandr - are you ok with this approach as well? Or do you have a better idea?

**Comment by schmandr** [comment]
Hm. I'd prefer a solution that is as close as possible to the PostGIS connection (and authentication) dialog of QGIS. Reason: If the user still sees the username/password fields at first, he is quite likely to enter these without being aware that they are going to be stored in the .qgs file.

Or at least the GUI should recommend the authconfig way and point out clearly that any credentials entered are going to be stored in plain text. (As does the PostGIS connection dialog, actually ...)

**Comment by m-kuhn** [comment]
@schmandr you are proposing to offer the choice between password and authentication config directly in the generate dialogs (and not only in the settings)?

We can also do that :+1: 

For the reasons why I did not propose that myself:

There is one problem I still see with encouraging people to use authentication configurations more widely: if you give a project with an auth config to someone he will need to enter his user credentials every time (or manually configure the authentication id), this is quite a high entry barrier.
In SO!GIS you have handled that by advising users to setup their configuration, but that's quite some effort for an organisation. My thinking was: if an organisation already does that they can also configure the authentication config in the settings. I'm happy to follow your lead.
