### ISSUE TITLE
Help link dead

### ISSUE THREAD

**Issue by ponceta** [opengisch/QgisModelBaker#397]
![image](https://user-images.githubusercontent.com/8614223/78217362-362fd700-74bc-11ea-9bfe-8c5f1d101852.png)

Goes to https://opengisch.github.io/projectgenerator/docs/index.html which is old documentation index.

**Comment by m-kuhn** [comment]
The link in QGIS Model Baker is correct. This issue refers to QgsProjectGenerator which is no longer maintained.
