### ISSUE TITLE
Error when following get_started procedure

### ISSUE THREAD

**Issue by ponceta** [opengisch/QgisModelBaker#398]
1. Install QGIS 3 with Osgeo4W
2. Install projectgeneration plugin using QGIS plugins browser  
3. Click generate

![image](https://user-images.githubusercontent.com/8614223/78217996-59a75180-74bd-11ea-8db9-3fb9abe669d0.png)

Win10 x64, QGIS 3.10.4

**Comment by m-kuhn** [comment]
This plugin was renamed and is superseded by "QGIS Model Baker". Projectgenerator is no longer supported.
I just updated the projectgenerator plugin to be deprecated and added a note about the fact that it is superseded.

**Comment by ponceta** [comment]
@m-kuhn thanks!
