### ISSUE TITLE
t_ili_id, required or not

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#403]
> In den Tabellen, die ModelBaker hinstellt, heisst die Id   t_id, die wird beim Import der Daten in die DB generiert.
> 
> Zusätzlich gibt es noch die Möglichkeit, eine Spalte t_ili_id generieren zu lassen. Dort werden bei einem Import von Interlis-Daten die Ids abgefüllt, die sie im xtf / itf hatten.
> 
>  
> 
> Bei «Generate, using Interlis» gibt es advanced options, wo man einstellen kann, ob man diese t_ili_id anlegen will.
> 
> Beim neuen ModelBaker wird die Spalte angelegt, auch wenn die Option «Create Import Tid» nicht angekreuzt ist.
> 
> Laut Tooltip bei dieser Option kann die Spalte, wenn es sie denn gibt, nicht leer sein, da sonst der Export nicht mehr funktioniert. Aber wir haben schon Daten exportiert und wieder importiert, wo diese t_ili_id leer war, und es hat funktioniert…
> 
> Das ist etwas verwirrend.
> 
> Entweder wird die t_ili_id fälschlicherweise immer erstellt, oder dann stimmt die Beschreibung im Tooltip nicht. Die  t_ili_id wird neu beim Setzen des Häkchens abgefüllt, ansonsten nicht. Aber das Attribut wird auf jeden Fall erstellt auf der Tabelle…
> 
>

**Comment by kingemir** [comment]
aus meiner Sicht ist das ein Bug. Wenn die Option Create Import Tid nicht angekreuzt ist, sollte die Spalte t_ili_id nicht generiert werden. 

Das nicht Ankreuzen der Option sollte ausserdem die Default-Einstellung sein. Ist die Spalte t_ili_id nämlich vorhanden, darf sie bei keinem Objekt leer sein, ansonsten fällt das exportierte xtf bei einer Validierung durch. Ausserdem muss in dieser Spalte der Attributwert eine uuid sein. Das heisst, im Falle des Vorhandenseins der Spalte t_ili_id muss der Attributwert mit dem Field Calculator und dem Ausdruck `regexp_replace(  uuid() , '[{}]', '')` generiert werden. Um sich diese ganze Mühe zu sparen, wird die Option gar nicht erst angekreuzt.

**Comment by pramisters** [comment]
Nein, das ist kein Bug (die Spalte wird ja nicht vom Model Baker sondern von ili2pg angelegt).
Und, nein, das Feld t_ili_tid muss NICHT in jedem Fall einen Wert enthalten.

Es gibt Fälle, wo ili2pg die Spalte t_ili_tid  implizit anlegt bzw. anlegen muss, auch wenn die explizite Option --CreateTidCol nicht verwendet wird. Das ist dann der Fall, wenn im Modell stabile Identifikatoren definiert worden sind (OID...), z.B.:

`OID AS INTERLIS.UUIDOID;`

In diesem Fall darf das Feld t_ili_tid nicht leer bleiben, weil es das Modell durch die Vorgabe der stabilen Indentifikatoren so verlangt. In diesem Fall definiert ili2pg in der Datenbank automatisch ein UUID-Generator-Funktion für den Default-Wert bei der entsprechenden Spalte:

`t_ili_tid uuid DEFAULT uuid_generate_v4()`

Umgekehrt ist es aber so, dass -mit der Option --CreateTidCol explizit eine Spalte für TIDs angelegt werden kann (wenn es ili2pg nicht schon automatisch durch die Modellvorgabe macht). Dann ist es aber NICHT Pflicht das Feld t_ili_tid zu befüllen:

`t_ili_tid character varying(200)`

D.h.  die ganze Sache ist zusätzlich modellabhängig und die Default-Einstellung könnte durchaus "angekreuzt" sein, es würde keine unnötige Erschwernis für den User bedeuten. Da es aber wohl einige User verwirrt, wäre die nicht-angekreuzte Default-Einstellung wohl besser.

Aber man sollte im GUI die Option(en) (es sind 2 verschiedene !) besser benennen:
- "Create TID column" (bei der Schemaerstellung für die Option --CreateTidCol) und 
- "Import TID" (beim Datenimport für die Option --importTid)
Bei Letzterer muss dann allerdings eine Prüfung erfolgen, ob die Spalte t_ili_tid auch existiert.

**Comment by romefi** [comment]
Was passiert, wenn t_ili_id immer angelegt wird? @pramisters testet Use Case ili-Modell verlangt OID nicht, t_ili_id anlegen, neue Daten erfassen, Daten exportieren.

**Comment by m-kuhn** [comment]
@signedav can you check if this issue is still valid?

**Comment by signedav** [comment]
Was momentan gemacht wird in den einzelnen Dialogfenstern:
- Bei der Schemaerstellung wird immer `--CreateTidCol` angegeben (die Konfiguration macht da keinen Unterschied)
- Beim Import kann man mit der Option "Create TID column" entscheiden, ob `--importTid` verwendet wird.
- Beim Export kann nichts gewählt werden und es wird **kein** `--exportTid` gemacht.

Das ist verwirrend und hat historische Gründe (weshalb ist hier erklärt: https://github.com/opengisch/QgisModelBaker/issues/601#issuecomment-984475776). 

Beim Wizard, wo wir gewisse "Altlasten" loswerden können hab ichs so gemacht, dass `--createTidCol` immer beim Schemaimport verwendet wird und, `--importTid`/`--exportTid` je nach dem ob das Schema mit `--createTidCol` angelgt wurde im import/export verwendet wird. So funktionierts nämlich stabil.

Die Frage wär nur noch: 
- Sollen wir auch bei den einzelnen Dialogen etwas fixen oder so lassen wie es alle schon kennen (mit der verwirrenden Logik, die oben beschrieben steht)?
- Soll im Wizard a. dem User die Option zur deaktivierung von `--createTidCol` gegeben werden oder stört es nicht?

**Comment by signedav** [comment]
Die einzelnen Dialogen werden entfernt. Deshalb wird das inkonsitente Verhalten damit verschwinden. Falls im Wizard irgendwann das `--createTidCol` manipuliert werden können soll, soll ein neuer Issue erstellt werden.

**Comment by sjib** [comment]
Finde ich gut so, dass `--createTidCol` immer verwendet wird.
Vielleicht ist ein Hinweis auf --exportTid in der ModelBaker Doku hilfreich - dann kann man nämlich wählen, in dem man das Skript manuell anpasst:

`--exportTid	Verwendet den Wert der Spalte T_Ili_Tid als Transferidentifikation (TID in der Transferdatei). (siehe Kapitel Abbildungsregeln/Tabellen). Bedingt beim Schema Import die Option --createTidCol.`
