### ISSUE TITLE
 ERROR: el valor es demasiado largo para el tipo character varying(1024) ?

### ISSUE THREAD

**Issue by D4nilov** [opengisch/QgisModelBaker#406]
Se ha presentado este error tanto en Qgis Model Baker como el Asistente, puede ser problema del plugin , de la estructura de datos o archivos .ili ?
![Captura de pantalla (12)](https://user-images.githubusercontent.com/64544560/80615882-de768400-8a05-11ea-912d-c105b89d6322.png)

**Comment by m-kuhn** [comment]
CC @gacarrillor where should we move this issue?

**Comment by gacarrillor** [comment]
It's OK if you move it here https://github.com/AgenciaImplementacion/Asistente-LADM-COL/issues/

**Comment by m-kuhn** [comment]
Done, thanks
