### ISSUE TITLE
Postgis connection dialog should allow service name

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#413]
Alternative to the Host/Port/DB combo allow definition of a service name:

![image](https://user-images.githubusercontent.com/884476/84069723-46d46000-a9cb-11ea-8672-93ac7ca9458c.png)

similar to the PG connection dialogue of QGIS:
![image](https://user-images.githubusercontent.com/884476/84069841-75523b00-a9cb-11ea-8bdb-c671fe99ca63.png)

**Comment by m-kuhn** [comment]
TODO: check if ili2pg supports pg_service.conf

**Comment by andreasneumann** [comment]
Wenn ili2pg keine Service-Konfig unterstützt, können wir immer noch folgendes machen:

Das ModelBaker Plugin liest die Service-Konfig aus dem pg_service.conf aus und übergibt die "übersetzten" host/port/db configs an ili2pg.

Beim Erstellen des QGIS-Projekts wird anstelle host/port/db der Service-Name ins Projekt geschrieben.

Das sollte doch technisch möglich sein?

**Comment by m-kuhn** [comment]
Das Parsen der Datei selbst sollte keine grösseren Probleme verursachen.
Das lokalisieren der Datei muss noch genau geprüft werden. (Standardmässiger Ort im Homeverzeichnis, Systemverzeichnis, Umgebungsvariablen).
Wenn das klappt können wir auch gleich eine Dropdown Liste für die Konfigration anbieten.

**Comment by andreasneumann** [comment]
@m-kuhn - ja eine Dropdown-Liste wäre natürlich sexy.

Richtig - das lokalisieren der Datei ist wahrscheinlich wirklich eine Kombination von mehreren Möglichkeiten. Ich persönlich verwende meist die Umgebungsvariable. Aber da gibt es auch 2 davon:

PGSYSCONFDIR und PGSERVICEFILE - siehe https://www.postgresql.org/docs/12/libpq-envars.html

**Comment by m-kuhn** [comment]
Options:

 - QGIS Model Baker parses the service file
 - ili2db parses the service file
 - jdbc parses the service file

**Comment by m-kuhn** [comment]
It was discussed recently. @andreasneumann do you have more information?

**Comment by signedav** [comment]
Will be in the next release #642
