### ISSUE TITLE
Domain values randomly fail to load for SQL Server

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/QgisModelBaker#420]
We've been experiencing random behaviors when using Relation Reference widgets to associate a domain value using SQL Server. 

Sometimes we can select domain values normally, but sometimes domain values do not appear in the combo box:

  ![Windows_modelbaker](https://user-images.githubusercontent.com/652785/87728385-90615900-c788-11ea-8475-1cf8d7cfd20b.gif)

Also, eventually, entering a letter makes the domain values appear as initially expected:

  ![Window_modelbaker2](https://user-images.githubusercontent.com/652785/87728462-bb4bad00-c788-11ea-93f3-3f5b0469859c.gif)

Note: On GNU/Linux (Mint), the behavior seems to be normal:
![Linux_modelbaker](https://user-images.githubusercontent.com/652785/87728506-cf8faa00-c788-11ea-872a-bbe3ecdf4cd7.gif)

It might be a problem in QGIS core.

-----------------
Windows environment: 
 + QGIS 3.10.2
 + Model Baker v6.2.0.
 + Driver for SQL Server: ODBC Driver 17 for SQL Server. 

Screencasts by @yesidpol

**Comment by yesidpol** [comment]
I tested in QGIS 3.15.0 and if we click a domain combo box, remove the text, and click elsewhere, the domain values disappear:

![test_3_15](https://user-images.githubusercontent.com/29440924/96013374-cd320000-0e0a-11eb-9fa1-ded482949148.gif)

QGIS version 3.15.0
QGIS code revision [5c8013df61](https://github.com/qgis/QGIS/commit/5c8013df61)

**Comment by domi4484** [comment]
Fixed in QGIS #https://github.com/qgis/QGIS/commit/cf37cb94f38230bee6d1066ad622c16f1bece8b5
