### ISSUE TITLE
Handling constraints when they are not defined in the DB

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#428]
As a follow up of #427 where the problem is described here https://github.com/opengisch/QgisModelBaker/issues/318#issuecomment-679146280

**Comment by m-kuhn** [comment]
Let me add some description:

It would be nice if we were able to help users fix b0rken data.
For this we'll need to import it into a database without constraints. And we should still be able to visualize the constraints.

Open question: where do we get the information about the constraints if they are not defined in the database?

  - Add them to the ili2db meta tables?
  - Parse the interlis model?

**Comment by signedav** [comment]
What are the affected constraints?
- not null
- unique
- numeric checks
- foreign keys

The numeric types we can find out I guess. But we don't know how the values of the check (as far as I know). Btw. in RoadsSimple we have this numeric check `CONSTRAINT streetnameposition_namori_check CHECK (namori >= 0.0 AND namori <= 359.9);`

Regarding the foreign keys. Part of the information is in the table `t_ili2db_column_prop`, but not everything. In e.g. the model RoadsSimple there are no foreign keys referring to LUTs created by in-line ENUMS (like roadsign_type of roadsign) only the regular references (like street of streetnameposition)...
