### ISSUE TITLE
Error message .Ili import (not.ili)

### ISSUE THREAD

**Issue by MoritzBrennecke** [opengisch/QgisModelBaker#442]
Model baker "projekt generator" recognises ili-files with the false extension .Ili (you can choose the file) but generates in error on import (model not found). Renaming the extension to .ili solves the problem. 
To be more user friendly, two options would be nice :
-  .Ili are not found when browsing, so the user would see the problem
-  Clear error message, for example: "Error: the extension of the interlis file has to be .ili).

**Comment by signedav** [comment]
As far as I know the `Ili` extension is found but not accepted. It says:
"Please set a valid INTERLIS file before creating the project."

But the issue you describe would happen exactly with `ILI` extension.
I think users might be confused when they cannot find their file in the browser. So I would prefer to have a bad validation with ILI (text field turns orange) and on pressing "Create" there should be a better warning like:
"Please set a valid INTERLIS file before creating the project. The file must be existing and have the extension '.ili'"
