### ISSUE TITLE
v6.3.0: Java 8 could not be found

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#444]
We tried to generate a project with v6.3.0. We always get the message "Java 8 could not be found". Even though the path is defined. On windows. Any suggestions? 

![image](https://user-images.githubusercontent.com/26796989/98247697-45a46080-1f74-11eb-968d-e892d0dc4307.png)

**Comment by romefi** [comment]
Still occurs on v6.3.1. Not able to generate anything, always says Java is missing. What am I doing wrong?

**Comment by signedav** [comment]
I cannot reproduce it. Can you try to run the ili2db command manually in the console (by selecting on the "create" button the drop down - edit command and copy paste)?

@yesidpol Do you have an idea what could be the issue here?

**Comment by romefi** [comment]
Think i found the problem. The ili2db command is:

`C:/Program Files/Java/jre1.8.0_271/bin/java.exe -jar C:\Users\romed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.4.4\ili2pg-4.4.4.jar --schemaimport --dbhost localhost --dbusr postgres --dbpwd ****** --dbdatabase modelbaker --dbschema nutzungsflaechen_lv95_v1_41 --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --defaultSrsCode 2056 --models Nutzungsflaechen_LV95_V1_4`

The path to the java.exe should bei in "" because of the space in `C:/Program Files` (acutally all pathes should be set in "", just in case there is a space in the path). So the ili2db-command should be:

`"C:/Program Files/Java/jre1.8.0_271/bin/java.exe" -jar "C:\Users\romed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.4.4\ili2pg-4.4.4.jar" --schemaimport --dbhost localhost --dbusr postgres --dbpwd ****** --dbdatabase modelbaker --dbschema nutzungsflaechen_lv95_v1_41 --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --defaultSrsCode 2056 --models Nutzungsflaechen_LV95_V1_4`

Hope that will do it.

**Comment by romefi** [comment]
In V6.2.0 the generating works, the command is also without "". If I copy/paste the command to cmd and execute, I got an error because the program "C:/Program" is not found.

So the command didn't change, but somehow it's not executable on Model Baker anymore. I would still recomend to put the "" to paths, so users would be able to copy/paste the command to cmd.

`C:/Program Files/Java/jre1.8.0_271/bin/java.exe -jar C:\Users\romed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.4.3\ili2pg-4.4.3.jar --schemaimport --dbhost localhost --dbusr postgres --dbpwd ****** --dbdatabase modelbaker --dbschema nutzungsflaechen_lv95_v1_41 --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --defaultSrsCode 2056 --models Nutzungsflaechen_LV95_V1_4`

**Comment by signedav** [comment]
Thanks @romefi I think it's because with this implementations #424 we pass the java-path in the command `QProcess::start` so we need to care for that. Fix will follow.

**Comment by signedav** [comment]
@romefi Maybe you find the time to have a look at https://github.com/opengisch/QgisModelBaker/releases/tag/v6.3.2

**Comment by romefi** [comment]
Works now, thanks!
