### ISSUE TITLE
Schemas without geometry class

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#446]
When there is no table containing a geometry, QGIS Model Baker cannot create a QGIS project (see attachment).

IHMO, also a schema without geometry classes shall yield a project containing only "tables".

![qmb-no-layers](https://user-images.githubusercontent.com/25387992/98816118-7bd85900-2428-11eb-8cce-a99ef2d0429b.PNG)

**Comment by zigertiger** [comment]
I think this has nothing to do whether the schema has geometries or not. It seems to be a general issue with release 6.3.0 (and QGIS 3.10 that I'm using).

**Comment by gacarrillor** [comment]
Does your database have baskets?

**Comment by zigertiger** [comment]
Yes it does (1 basket).
As I mentioned, there seems to be a general problem with version 6.3.0. After back-rolling to version 6.2.0, all works just fine.

**Comment by signedav** [comment]
Okay, it seems to be the bug I introduced there by omitting the related tables.
This should be fixed with this #445 Please test with 6.3.1 Thanks.

**Comment by signedav** [comment]
Hi @zigertiger It's uploaded now https://github.com/opengisch/QgisModelBaker/releases/tag/v6.3.1

**Comment by signedav** [comment]
@zigertiger Can we close this one?
