### ISSUE TITLE
Attributes' aliases and layers' names not translated 

### ISSUE THREAD

**Issue by romanoe** [opengisch/QgisModelBaker#459]
First of all, very useful plugin and thanks for your work ! 

**Environment:** 
- QGIS 3.16.2
- Windows 10

**Issue / New feature**
I'm trying to import several Interlis schemas in my Postgresql database with the QGISModelBaker plugin. Using the `--nameLang fr` parameter in the script, tables' and attributes' names are translated in the database but they keep the german names (aliases) in QGIS: 

| Postgres database  | QGIS |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/32194904/103016261-13f65180-4542-11eb-9114-c52dfc505c9c.JPG" width="100%"> | <img src="https://user-images.githubusercontent.com/32194904/103016664-aac30e00-4542-11eb-827e-fd819d416c3d.JPG" width="100%">  |

The customized ili2db command  (`--nameLang` added) in QGISModelBaker: 
`"C:/Program Files (x86)/Java/jre1.8.0_271/bin/java.exe" -jar C:\Users\SGCA0250\AppData\Roaming\QGIS\QGIS3\profiles\qgaz\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.4.4\ili2pg-4.4.4.jar --schemaimport --nameLang fr --dbhost localhost --dbport 5432 --dbusr postgres --dbpwd ****** --dbdatabase postgres --dbschema normat --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --createBasketCol --defaultSrsCode 2056 --models PlansDAffectation_MN95_V1_1`

Thanks in advance.

**Comment by signedav** [comment]
If no displayName meta-attribute is defined for a column (found in `t_ili2db_column_prop`), the field names are taken from the iliname (found in `t_ili2db_attrname`) and this is the one from the base model. 

I close this. See further discussions about this here: #402
