### ISSUE TITLE
When importing to temp folder it should set "without validation"

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#463]
When importing an XTF to a temp folder (like it does with drag'n'drop) it should set "without validation" as default.

**Comment by gacarrillor** [comment]
I'm not fan of this implicit behavior. 

I understand that while dropping the XTF we want to ensure success and not bother users with validation errors, but that's a very specific use case, so I can live with disabling validation. 

On the other hand, using the dialog, where I as a user have the whole control of the situation and configuration, I wouldn't like to see my settings overwritten.

Just my 2 cents, no big problem if you decide to implement it in the end. :+1:

**Comment by signedav** [comment]
It's currently not required.
