### ISSUE TITLE
Set "Allow NULL" to true at MANDATORY domain related attributes

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#467]
When a project is generated and a MANDATORY domain related is involved, the "Allow NULL" in the form is deactivated. This leads to the behavior, that the picklist in the form has already a value when a new object is added, the first value in the picklist. So the user is not forced to choose the propper value, may forgets it and saves the wrong value. If the "Allow NULL" is set to true, the user is forced to choose the propper value before he's able to save the form.

Example: Attribute `Datenherr` in https://models.geo.admin.ch/BAFU/Schutzbauten_V1.ili

**Suggestion**: If a domain related attribute is involved, set the "Allow NULL" property always to true.

**Now**:
![image](https://user-images.githubusercontent.com/26796989/106719692-e6053200-6602-11eb-8da6-8555198fbe45.png)

![image](https://user-images.githubusercontent.com/26796989/106719769-fb7a5c00-6602-11eb-8476-578b840a6c13.png)

**Goal**:
![image](https://user-images.githubusercontent.com/26796989/106721331-d25acb00-6604-11eb-9bb4-2d329a9867b8.png)

![image](https://user-images.githubusercontent.com/26796989/106721379-e0a8e700-6604-11eb-87ff-af8a963b6d59.png)

**Comment by m-kuhn** [comment]
Should we always enable NULL?

- When it's allowed (not mandatory) we want this option
- When it's not allowed (mandatory) we still want it to show up and we have constraints to "help" the user choose something

**Comment by romefi** [comment]
Right. As ist seems the help still would work if the "Allow NULL" is set to true at mandatory attributes. By editing a new object, the default value is NULL. If it's mandatory, you have to choose something, otherwise the "OK" button will keep inactive. In my point of view that's perfect. If attriute is mandatory:

- User is forced to choose a propper value in picklist
- User can't press "OK" until a value is chosen which is not equal to NULL

Or am I missing something?

**Comment by m-kuhn** [comment]
I completely agree

**Comment by romefi** [comment]
Thanks. Assume it's not a very big thing to change that? If so, I would label is at approved.
