### ISSUE TITLE
Sugg: sort "select multiple interlis models"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [opengisch/QgisModelBaker#471]
The list of the found models seem to be sorted by its path, not its name.
I think it could be nice when the list is (optional) sorted by name of the models.
![grafik](https://user-images.githubusercontent.com/13277944/107394922-a5268500-6afc-11eb-9cc6-e0850e5bbcf4.png)

**Comment by signedav** [comment]
Should they be sorted by the name only? 
Or by the name and the repo (grouped by repo)?
And should the repo be sorted as well (according to their name or according to the steps going through ilisite.xml)?

**Comment by Pierre-de-la-Verre** [comment]
I think that by name would be the minimum. 
A max solution would be a multiple-sortable table like Excel, but that's an overload ..
