### ISSUE TITLE
Model w/ "BAG OF" yields poor QGIS project

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#474]
Model: http://models.geo.gl.ch/ili/GL_Schutzwald_V2_2021-02-18.ili is a simple model w/ two "BAG OF" attributes defined via "STRUCTURE"s.

The Model Baker creates a project with no associations whatsoever although being expected to do so. 

- I need to configure the two associations by hand
- I need to configure the type enumerations by hand ("Wertebeziehung" in German)
- As a consequence, I need to add the two associated STRUCTUREs to the form of the main class "Schutzwald" by hand

I use the latest Model Basker release and QGIS LTR 3.10

I provide the UML model as an illustation:

![gl_schutzwald](https://user-images.githubusercontent.com/25387992/108471343-8ad27100-728b-11eb-9be7-e1170c04072d.png)

**Comment by signedav** [comment]
Not sure if I understand it correctly, but I get the relation created by Qgis Model Baker 7.0. with QGIS 3.22.

![image](https://user-images.githubusercontent.com/28384354/163178707-221a31f5-1094-415f-bc5e-641173335111.png)

Is this still an issue?

**Comment by signedav** [comment]
I think it's no issue anymore. Otherwise feel free to reopen.
