### ISSUE TITLE
Table name from iliname

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#48]
ili2pg writes a comment `@iliname Table.Name` to the database schema. We could use that for the table name in QGIS. Only the last part (`Name` for the example before) as default table name.
Just like for field aliases done already.

**Comment by 3nids** [comment]
@m-kuhn can you detail "writes a comment to the database schema"? do you have an example?

**Comment by m-kuhn** [comment]
@3nids is this still on the todo list?

**Comment by signedav** [comment]
I cannot see any comments on the table `route` created with `ExceptionalLoadsRoute_LV95_V1`.
Still we could implement it by getting the layer name from the table `t_ili2db_classname`.
Should this be the way to go @m-kuhn ?

**Comment by m-kuhn** [comment]
This might be a leftover from ili2db 3. t_ili2db_classname sounds like the way to go :+1:
