### ISSUE TITLE
Create multiple relation editor widgets for same relation

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#505]
Considering this implementation https://github.com/qgis/QGIS/pull/38331 and this issue https://github.com/qgis/QGIS/issues/37675

**Comment by andreasneumann** [comment]
Here is an example model with multiple classes inheriting from the  abstract class "Raeumliches_Element" http://geo.so.ch/models/ALW/SO_ALW_Strukturverbesserungen_20190912.ili 

See also the two ER diagrams:
http://geo.so.ch/models/ALW/SO_ALW_Strukturverbesserungen_20190912_ER-Diagramm_nach_kt-erweiterung.png and http://geo.so.ch/models/ALW/SO_ALW_Strukturverbesserungen_20190912_ER-Diagramm_nach_themen.png
