### ISSUE TITLE
Relation Editor: Redesign improving the "link children dialog"

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#506]
(updated by @signedav)

At the moment this is a "edit form".
![image](https://user-images.githubusercontent.com/28384354/123684841-41ec8380-d84e-11eb-835c-d8d79f10170c.png)

You can edit those features, what does not really make sence.

It should be kind of a *search form* allowing to:
 - Create / select a list of features
 - Using a search form
 - Selecting on the canvas
 
 What else could be considered in a redesign/re-implementation of this dialog?

**Comment by signedav** [comment]
Considering the search. Won't the filtering make it? Or what else would be requested here?
![image](https://user-images.githubusercontent.com/28384354/123685371-e5d62f00-d84e-11eb-88b4-1a09f6d6b65a.png)

**Comment by signedav** [comment]
Considering select a list of features. Won't the selection here make it? Or what else would be requested here?
![image](https://user-images.githubusercontent.com/28384354/124240684-45685f00-db1b-11eb-85c2-61a42adcedf0.png)

**Comment by signedav** [comment]
Splitting this issue and close it.

See: 
Selecting on the canvas #311
Using a search form: #512
Create / select a list of features: #513

**Comment by signedav** [comment]
And reopening it. Since it could be a re-implementation of this dialog considering and resolving all the linked requests.

**Comment by signedav** [comment]
Linking Relation Editor is integrated since #643
