### ISSUE TITLE
Beautify column aliases and table names

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#52]
Attribute column labels and table names should be beautified:

Attribute col labels:
* replace "_" with blank
* replace german Umlauts "oe" --> "ö", etc.

Table names: 
* replace "_" with blank
* replace german Umlauts "oe" --> "ö", etc.
* replace small caps to large caps

Would french/english have different requirements?

**Comment by m-kuhn** [comment]
I could imagine some kind of regex machinery for this.

A list of substitutions to apply (which would probably be the same for table names and field labels), configured globally in the plugin settings and a suitable set of default options.

| Match | Replace |
|-------|---------|
| ue    | ü       |
| oe    | ö       |
| ae    | ä       |
| _     | ' '     |

Plus a checkbox to " [ ] capitalize first letter of each word"

**Comment by andreasneumann** [comment]
Your proposal sounds good. Also, to have it as a global plugin setting.

It would also be quite flexible (e.g. to create rules for another language).

Can you please implement this?

**Comment by pramisters** [comment]
Generally a good idea
The same does ili2db with the option --beautifyEnumDispName for underscores in enumeration display texts. We refrained from replacing ue, oe, ae because those character combinations are not always "Umlaute".

**Comment by 3nids** [comment]
I was thinking of another strategy here.

Instead of using simple rules, I would propose to use a **German dictionary**, which contains umlauts and capital letters for nouns. We would test all words again this dictionary to turn them correctly.

Since the dictionary is a bit heavy (~5mo), the idea is to create strategies for each language and to **download them on demand** in the plugin settings (i.e. download German strategy).
We could easily add French later on (other advantage for French is the capacity to add accents).

There would still be situations where you cannot determine the exact word (like in French: il _crée_ vs il est _créé_). But these are edges cases, and we could still add further options to provide specific translations (in sentences or context).

**Comment by m-kuhn** [comment]
@andreasneumann @pramisters I am very interested in your feedback to this proposal.

**Comment by andreasneumann** [comment]
Interesting idea. But on the other hand - data models often contains very special, dedicated terms that typically can't be found in dictionaries. Think about the QGEP data model - how many of these terms can be found in dictionaries? Or do you think about a dictionary that the Interlis community/project generator community could extend and share online? For me either way is fine - whatever is easier to implement or more flexible.

**Comment by gacarrillor** [comment]
Why don't you consider using the meta-attribute `!!@ili2db.dispName` for table and column display names?
https://github.com/opengisch/projectgenerator/issues/62#issuecomment-314451623

**Comment by andreasneumann** [comment]
@gacarrillor - yes, it is like @m-kuhn explained. As a Canton (province) we rely a lot on the upstream data models on the federal level. The federal level does not care about a nice display !!@ili2db.dispName for us - and we want to use their data models without having to modify it.

**Comment by romefi** [comment]
@m-kuhn couldn't this be solved with the metainformation provided by the toml-File?

**Comment by m-kuhn** [comment]
Yes, true. But given that it will take a while until we have a complete list of toml files including dispName for all objects, I think it could still be desirable to implement this for the time being?

**Comment by m-kuhn** [comment]
@andreasneumann since you opened the issue, what's your opinion?

**Comment by andreasneumann** [comment]
Hi, I agree with @romefi and @pramisters that this is not our top priority. As the "issue title" says, this is more about polishing (beautifying), if most other, more pressing issues are solved.

If we can support alternative column aliases with toml files this would probably solve our issues here. It would be relatively easy to share such toml files. The generic replacements tables is probably the next best approach. Not so sure about the dictionaries (size issues and probably they don't contain many terms used in data models).

**Comment by m-kuhn** [comment]
Closing for now, but might be reopened if required in the future.
