### ISSUE TITLE
t_ili_id generated even if "Import Tid erzeugen" is deselected

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#562]
When the option  "Import Tid erzeugen" is deselected, there shouldn't be any t_ili_id-column in the generated schema. But it's still there. Seems as the option don't change anything.

![image](https://user-images.githubusercontent.com/26796989/137504932-9618537d-39f3-4aa5-960f-e16aa21b1cd1.png)

Is that a bug or am I missing something?

**Comment by gacarrillor** [comment]
Does your model have any topic with the `OID AS INTERLIS.UUIDOID` instruction?

**Comment by signedav** [comment]
This function controls `--importTid` in the ili2db command and not `--createTidCol`. This is the state at least since 6.3.x 
What is the expected behavior? Thet it does not pass `--createTidCol`? If so, I need to check if this is possible.

**Comment by romefi** [comment]
Was this closed by accident?

**Comment by gacarrillor** [comment]
> > Does your model have any topic with the OID AS INTERLIS.UUIDOID instruction?
> 
> Thanks @gacarrillor, that's the reason why the t_ili_id is needed. Didn't think of that. I'll close the issue again :)

Right @romefi, the model can require it (from the ili definition itself), but if not, you can still force it from ili2db parameters.
