### ISSUE TITLE
UI is not always dark mode friendly

### ISSUE THREAD

**Issue by rbovard** [opengisch/QgisModelBaker#568]
With official *Night mapping* theme (QGIS 3.16.11)

Model Baker v6.6.4

![image](https://user-images.githubusercontent.com/4549666/137884390-94a4cc65-49e6-4d0b-a28e-1eaa479b4cfc.png)

**Comment by m-kuhn** [comment]
Cc @nirvn do you have a hint?

**Comment by signedav** [comment]
Maybe we can go for a quick solution as a first step, to have at least a readable dialog.

**Comment by gacarrillor** [comment]
Some findings:

 + [ ] Schema Import / Import data
    + [ ] Model (.ili)  icon 👁️‍🗨️️
     + [ ] Log 👁️‍🗨️️
 + [ ] Generate project
     + [ ] Configure OID generation
       +  [ ] ε button for expressions 👁️‍🗨️️ [QGIS issue]
     + [ ] Log 👁️‍🗨️️
 + [ ] Export:
     + [ ] Database file (in general, all db_panel input widgets): Path 👁️‍🗨️️
     + [ ] Log 👁️‍🗨️️
 + [ ] Dataset manager
     + [ ] Checkboxes in Manage baskets 👁️‍🗨️️ (checkboxes in other dialogs show a white thick on green background)

**Comment by signedav** [comment]
Cool. What about validator and the selector in the toolboxes (two features people use while working on the data)?

**Comment by gacarrillor** [comment]
> Cool. What about validator and the selector in the toolboxes (two features people use while working on the data)?

Just updated the diagnosis, and yes, the selector in the toolbox looks good.
