### ISSUE TITLE
Model Baker Library Package

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#579]
The question is if it makes sense to extract parts of the Model Baker into a Python (library) package. The reason is, that the requirements on the GUI part diverts from Model Baker and other applications using parts of it (like the _Asistente_-LADM-COL). To keep a common base such a package makes sense. It profits that more parties are having an eye on it and are interested to have a stable and strong back end.

After the call with Germàn we found out that the _Asistente_ uses mainly:
- libili2db functions
- generator functions
- utils

We could make a package (workingtitle: ili2dbwrapper) only for the ili2db stuff.
We could make a package (workingtitle: modelbakery) containing generator and ili2db stuff.
We could make both while modelbakery is using ili2dbwrapper. 

**Some technical research results (mainly notes to myself):**
A main change in those functions of interests are the basket integration what Asistente is using but not in the way Model Baker uses it. This should be handled "neutral" in the library and controlled from the outside. This basket handling checks are done here:
https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libqgsprojectgen/generator/generator.py#L94
and
https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libqgsprojectgen/dbconnector/db_connector.py#L192

And we check for basket layer here: https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libqgsprojectgen/generator/generator.py#L132
but this could be caught by the basket_handling. Same for check if dataset_table:
https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libqgsprojectgen/generator/generator.py#L228-L229
But those "is_..._table" should not mind, since we only set them read only considering that... 

Considering no Basket tables in the ignored table. In the get_ignored_layers the basket tables are ignored considering the `basket_handling` parameter...

Another thing is the the default `self.create_basket_col = True`  this might not be default in the library but should be in Model Baker.  So I guess a constructor parameter can do it when initializing `SchemImportconfiguration` or set it via the base-config (need to check that).

**Comment by gacarrillor** [comment]
Yes, I think that's the way to go since Model Baker plugin is growing, and it's difficult to meet all user requirements at the same time.

To build 3rd party plugins like Asistente LADM-COL, we use (and contribute to) Model Baker's core modules, but we handle specialized stuff (like baskets) in a way that we assist our users decreasing the cognitive load that is needed.

Model Baker is well suited for power users, though, so I think we (specially people trained on INTERLIS/ili2db) will continue using it's GUI part when we need to handle and tweak ili2db parameters, which is exactly what we try to hide from our end users.

**Comment by gacarrillor** [comment]
BTW, I've already borrowed some part of MB as a lib. Just the ili2db wrapper: https://github.com/SwissTierrasColombia/Asistente-LADM-COL/pull/512

**Comment by signedav** [comment]
Thanks for the info @gacarrillor and the input in the validator PR. Considering the validator it looks like we are on the same train. The validation part would be easy to put into a common library. Considering your library implementation mentioned here it seems like you did not just take the Model Baker modules but made them more slim and focused to your needs. What do I need to consider to make a library that fits for your needs? Would it be okay to make it much as possible like the current Model Baker modules, then you add the functions you need and if you need to change existing ones we can communicate that, so we can use them both?

**Comment by gacarrillor** [comment]
@signedav, as far as I remember, I just took the libili2db folder from MB and resolved import issues. But it is almost intact. From it I added the validate operation and upgrade the ili2db version.

> What do I need to consider to make a library that fits for your needs? Would it be okay to make it much as possible like the current Model Baker modules, then you add the functions you need and if you need to change existing ones we can communicate that, so we can use them both?

I'm not sure if you're referring to libili2db or to what we had talked about before (i.e., generators).
If it's the latter, I think the idea needs a bit of technical discussion, perhaps during a meeting. I remember that you were going to explore possible solutions before proceeding with a second meeting.

**Comment by gacarrillor** [comment]
I have created a "library" version of Model Baker to ship it with our [Asistente LADM-COL](https://github.com/SwissTierrasColombia/Asistente-LADM-COL/). Of course, this is to fit our own needs, but can give you an idea.

Here the commit: https://github.com/SwissTierrasColombia/Asistente-LADM-COL/pull/529/commits/e25fe2aace5d15b16820c8e934398db668cb47dc

And here how it ended up being structured: https://github.com/SwissTierrasColombia/Asistente-LADM-COL/tree/mb_lib/asistente_ladm_col/lib/model_baker_lib

**Comment by signedav** [comment]
@gacarrillor maybe you find time to checkout https://github.com/opengisch/QgisModelBakerLibrary

I decided to use a flatter structure. Subpackage `iliwrapper` contains the ili2db stuff and has no dependencies on the proj gen subpackages. The proj gen subpackages are directly inthe `modelbaker` package.

**Comment by gacarrillor** [comment]
The structure looks good @signedav
