### ISSUE TITLE
Loading of additional layer tree structures from configuration file

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#593]
It should be possible to load an additional layer tree structure (defined in a .qlr file).

This should happen before additional relations are loaded ( see also issue #589 )

As a configuration parameter the following should be possible:
- top (before any other layer)
- bottom (below any other layer)
- beforeLayer(layer_name)
- afterLayer(layer_name)

Not sure what configuration file would be best (open to discussion):
- additional entries in the layertree .yaml ?
- additional entries in the metaconfig .ini file?

Additional issue/discussion: what should happen with the layer order? Can we have parameters that help us arrange layer order as well?

**Comment by signedav** [comment]
Main importance is to load a qlr somerwhere specific in the project.

qlr's can be linked in the metaconfig file.

Another thought (not alternatively) is to be able to define datasources in the yaml as well (considering e.g. environment variables).
