### ISSUE TITLE
Loading of Project variables from configuration file

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#594]
It should be possible to add "project variables" and the associated values to the project from a usability hub configuration.

Probably it would be best to define the variable names and associated values in the metaconfig .ini-File ?

**Comment by signedav** [comment]
**Note:**

Concerns the setting in the qgs xml:
```xml
    <Variables>
      <variableNames type="QStringList">
        <value>testvariable</value>
        <value>testvariable2</value>
      </variableNames>
      <variableValues type="QStringList">
        <value>{}</value>
        <value>hello</value>
      </variableValues>
    </Variables>
```

I'll put it into projecttopping.YAML instead.

So:
metaconfig.ini > tool settings and options
projectopping.yaml > project settings and config
