### ISSUE TITLE
Create Import Tid Configuration

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#601]
![image(3)](https://user-images.githubusercontent.com/28384354/144216429-818144bc-277d-46e1-a583-b273dcaffe02.png)

The tooltip sais:
> "Creates a new column t_ili_tid in all classes, which is mandatory and should be unique, not only for across the current database, but across the whole system. Normally you should not enable this option directly, but rely on the INTERLIS model and ili2db. The former should have a line enabling OIDs (preferably with UUIDs) and the latter will make sure the database updates the new column every time a new record is created.

So one might think it's about to create the `t_ili_tid` column in the tables. But in the code we have this:

![image(2)](https://user-images.githubusercontent.com/28384354/144216411-67097f11-5dab-4963-9287-db44a0c4774d.png)

The setting "Create Import Tid" decides if `--importTid` is set in `SchemaImportConfiguration`. That's odd since it's not relevant for the Schema Import (not like `--createTidCol` what is set anyway). 

`--importTid` is considering the data import. Like `--exportTid` in the export (but this is not set by the Model Baker.

(There is another variable `with_importtid` and `with_exporttid` controlling the those parameters. I don't know why.)

So it seems that this setting in the configuration is considered in data import only. The user might think that it changes something on schema create but it doesn't.

There are several possibilities to fix that:
a. make the function control `--createTidCol` instead on schema import and `--importTid` at data import (what is not that nice, because then one checkbox would control different parameters in different cases)
b. rename the function to "Import Tid" instead (what is not that nice, when it's in the option dialog that appears for schema import).

Generally the questions are:
1. Should `--createTidCol` be configurable in Model Baker (or always set)?
2. Should `--importTid` / `--exportTid` be configurable in Model Baker (or always set when `--createTidCol` is set)?

I have the feeling that the 1. should be "yes" and 2. should be "no". But this would change the current behavior.

In the wizard I have no settings for data import. So in case we would reply 2 wiht "yes" it might need another setting in data import. And otherwise it needs to  set `--importTid` statically \*

\* same for export with `--exportTid`

**Comment by signedav** [comment]
Any thoughts on that @seralra96 Do you know the background of having the option to set (and unset) `--importTid` in the SchemaImportConfiguration?

**Comment by gacarrillor** [comment]
@signedav, here you find the background: https://github.com/opengisch/QgisModelBaker/issues/127

See also: https://github.com/opengisch/QgisModelBaker/pull/208

**Comment by signedav** [comment]
Thanks @gacarrillor 

I'm still confused. There it's about the `--importTid` that creates the column `t_ili_tid`. But that's not true. When I do a schema import without `--importTid` it doesn't change anything. `--createTidCol` is what makes the difference in schema import. And `--importTid` concerns only the data import.

**Comment by signedav** [comment]
Okay, that all makes sense now. 

People wanted the `--importTid` because they needed the stable id's and since it implied the `--createTidCol` with it in older versions, this needed to be a parameter in the schema import and the data import. So we had it configurable in both.

Later the `--createTidCol` has been introduced and is set by Model Baker by default. So the creation of the `t_ili_tid` is done always, the import of it was configurable but not the export (in export it was always `false`)

But anyway nobody complained since the import / export worked without these parameters as long as the models have stable TIDs defined.

So what we do now?
- I will keep the `--createImportTid` mandatory on schema import (on the create dialog there is still the setting that does nothing)
- I will keep in the single import dialog the possibility to set/unset the `--importTid` 
- I will make in the wizard the `--importTid`/`--exportTid` dependent on how the schema has been created (according to `t_ili2db_settings` table), what would lead to that it's always used when the schema has been created with Model Baker
