### ISSUE TITLE
No exports are made without having baskets

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#602]
***Reported issue and reproduced:***
- I import a schema of `Nutzungsplanung_V1_2` without `--createBasketCol`
- I create data in `Grundnutzung_Zonenflaeche` and I export it again. No data are exported. When I have a basket created in `t_ili2db_baskets`, then the data are exported.
- When I create a `Dokument` it's exported without basket.

My commands:
```
java -jar /home/dave/dev/opengisch/QgisModelBaker/QgisModelBaker/libili2db/bin/ili2pg-4.5.0/ili2pg-4.5.0.jar --schemaimport --dbhost localhost --dbport 5432 --dbusr postgres --dbpwd postgres --dbdatabase bakery --dbschema nutzungsplan111 --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --createUnique --createFk --createFkIdx --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createGeomIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --importTid --smart2Inheritance --strokeArcs --defaultSrsCode 2056 --models Nutzungsplanung_V1_2
```

```
java -jar /home/dave/dev/opengisch/QgisModelBaker/QgisModelBaker/libili2db/bin/ili2pg-4.5.0/ili2pg-4.5.0.jar --dbhost localhost --dbport 5432 --dbusr postgres --dbpwd postgres --dbdatabase bakery --dbschema nutzungsplan111 --export --models Nutzungsplanung_V1_2 /home/dave/testexport.xtf
```

***Found the issue:***
In the topic `BASKET OID` is defined.
```
TOPIC Geobasisdaten =
    BASKET OID AS TypeID
```
Apparently this needs a `--createBasketCol` to work properly. I deleted the definition in the model - export without basket works fine.

If found a note in https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst:
> Beim `--schemaimport` von Modellen mit erweiterten TOPICs muss die Option benutzt werden, damit die Daten korrekt exportiert werden können.

But this does not concern this situation.

**Comment by signedav** [comment]
@claeis Do I miss a part in the documentation, or is this something the documentation should be extended with?

**Comment by claeis** [comment]
TOPIC EXTENDS and BASKET OID AS in the ili-model require the use of --createBasketCol  at --schemaimport time (ili2db will check this; see also claeis/ili2db#130).

Export by --baskets or by --dataset require the use of --createBasketCol at --schemimport time

**Comment by signedav** [comment]
Exactly. Would be great when ili2db can recognize when trying to import BASKET OID without `--createBasketCol`

**Comment by signedav** [comment]
Considered in ili2db.
