### ISSUE TITLE
Opening attributeform crashes with QGIS 3.22.1 (Windows)

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#609]
We made a new schema with model `Planungszonen_LV95_V1` and generated the QGIS-project. When you try to open the attributeform of the geometry-layer, QGIS 3.22.1 crashes. Same if you try to collect a new object. You draw the geometry, terminate with right mouseclick and when the attributeform should open to fill in the values, QGIS 3.22.1 crashes.

Occured on Windows. Not sure if it is an QIGS issue or an QGIS Model Baker issue.

**Comment by m-kuhn** [comment]
Do you have an error message from the crash?

**Comment by romefi** [comment]
Not really something useful:

```
Crash ID: 9067aa2d1e11956c094d1e0c3fd3c75ff72450c8


Stack Trace


QWidget::sizePolicy :
QgsAttributeForm::init :
QgsAttributeForm::QgsAttributeForm :
QgsDualView::init :
QgsAttributeTableDialog::QgsAttributeTableDialog :
QgisApp::attributeTable :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

```

**Comment by m-kuhn** [comment]
@domi4484 can you have a look at this? (random thought that you may know something about the size policy in 3.22)

**Comment by domi4484** [comment]
@m-kuhn I quickly tried to reproduce and by me QGIS hangs forever without crashing. I could take a closer look next week

**Comment by seralra96** [comment]
I have the same error with another model but also geometry layer. Same behavior, when I finish to draw the polygon and try to open the attribute form, QGIS crashes with this message:


![image](https://user-images.githubusercontent.com/25961499/146225686-74ee0d1d-bd74-4761-ade7-863b51b289f9.png)

QGIS version: 3.22.1
QGIS Model Baker Version: 6.7.1
OS: Windows 10

**Comment by domi4484** [comment]
In recent master seems to be fixed. Can also someone else confirm that with the nightly builds it does not crash anymore?

**Comment by domi4484** [comment]
Was fixed here ([https://github.com/qgis/QGIS/pull/46287](https://github.com/qgis/QGIS/pull/46287)) and should be good again in the next QGIS point release. (@m-kuhn your random thought was quite exact 😑)
