### ISSUE TITLE
Replace qgis 3.10 with 3.22 tests

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#611]
Let's stick to supported versions

**Comment by signedav** [comment]
Ah latest is the nightly? Then we need to add 3.22, yes.

**Comment by m-kuhn** [comment]
And remove 3.10 to avoid loosing time on it (for whatever reason)?

**Comment by signedav** [comment]
Fine for me. Thought about it lately and then thought it doesn't hurt. But yes. We can remove it.
