### ISSUE TITLE
Superfluous tabs with model KbS_V1_5

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#621]
We generated a new schema and new project for Model [KbS_V1_5](http://models.geo.admin.ch/BAFU/KbS_V1_5.ili) with
[toml](https://github.com/opengisch/QgisModelBaker/files/7749968/KbS_V1_5.zip) to treat MultiPolygon as multipart-geometry. After generating project, the form for "Belasteter_Standort (Geo_Lage_Polygon)", there are lots of tabs with "zustaendigkeitskataster". Expected is only one tab.

![Screenshot 2021-12-20 170442](https://user-images.githubusercontent.com/26796989/146880789-bb571c99-96f0-42c4-b702-cee90aa1c5dc.JPG)

I took a look at the model, but couldn't figure out why there are so many tabs. Is the model just bad modeled or Model Baker not behaving the way it should?

**Comment by signedav** [comment]
Is one tab expected at all? Shouldn't it have no tab to zustaendikeitskataster since zustaendigkeitskataster is the parent (and available as relation reference in the "Allgemein" tab?

**Comment by signedav** [comment]
After a quick look it's because of the `MultilingualUri` referenced in `Zustaendigkeitskataster` but I need to analyze it deeper. I think it's a conceptional issue. Maybe Model Baker could handle it smarter.

**Comment by romefi** [comment]
That makes sense... Sadly. Maybe we could take a look on general handling of Model Baker with `Multilingual*`, which seems improvable

**Comment by signedav** [comment]
I think that when a class is associated by lots of other classes it recognizes a link-table there in every case. Maybe Model Baker can be smarter there. I'll check it out.

**Comment by romefi** [comment]
Just noticed with 

```
[KbS_V1_5.Belastete_Standorte.MultilingualUri]
ili2db.mapping = "Multilingual"
```

in toml-file, the multilingualUri is expanded and the superfluous tabs disappear.

![image](https://user-images.githubusercontent.com/26796989/166486278-8fea4dff-c820-4973-b254-c3913d766cff.png)

I close the issue, as it's solved for KbS_V1_5. With INTERLIS 2.4 base model http://[models.geo.admin.ch/CH/CHBase_Part2_LOCALISATION_V2.ili](http://models.geo.admin.ch/CH/CHBase_Part2_LOCALISATION_V2.ili) and ili2db handling it right with option `--expandMultilingual`, it should be solved sustainably.
