### ISSUE TITLE
Choosing T_basket fails with geopackage

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#622]
We generated a new project for model `Waldgrenzen_V1_2` with geopackage. When adding a new feature, the picklist of `T_basket` shows only `NULL`, even though the baskets for Baseset are defined. Same model in Postgres works fine, the Baseset-basket appears in the picklist.

![image](https://user-images.githubusercontent.com/26796989/147102239-3170a8f6-546d-4990-8539-6281a314adaa.png)

**Comment by signedav** [comment]
Located. It's because this expression is generated for the filter:
```
"topic" = 'Waldgrenzen_V1_2.Geobasisdaten' and attribute(get_feature('t_ili2db_dataset', 't_id', "dataset"), 'datasetname') != 'Catalogueset'
```
But the table is called `T_ILI2DB_DATASET` in GeoPackage (uppercase)...
