### ISSUE TITLE
stale online docu?

### ISSUE THREAD

**Issue by tpo** [opengisch/QgisModelBaker#636]
Dear OpenGisch!

[This](https://opengisch.github.io/QgisModelBaker/docs/en/user-guide.html) is the first hit on DuckDuckGo when I search for "Model Baker". That page however seems to be B0rK3n. Not sure why.

Maybe delete that page as it seems to be a duplicate of [this](https://opengisch.github.io/QgisModelBaker/user_guide/get_started/) guide page?

**Comment by signedav** [comment]
Oh yes. Thanks.
I'll have a look.
