### ISSUE TITLE
Multiple Layers with the same name created on extended Classes

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#662]
Example Model:
```
MODEL City_V1_1 (en) AT "mailto:localhost" VERSION "2021-07-20" =

  TOPIC Constructions =
    CLASS Building  =
      Name : MANDATORY TEXT*99;
    END Building;
    CLASS Street  =
      Name : MANDATORY TEXT*99;
    END Street;
    CLASS Cooperation  =
      Name : MANDATORY TEXT*99;
    END Cooperation;
  END Constructions;

END City_V1_1.
```
Extended Model:

```
MODEL DavesCity_V1_1 (en) AT "mailto:localhost" VERSION "2021-07-20" =
  IMPORTS City_V1_1;
  TOPIC Constructions EXTENDS City_V1_1.Constructions =
    CLASS Building (EXTENDED) =
      Description : TEXT*99;
    END Building;
  END Constructions;

END DavesCity_V1_1.
```
Leads to two layers with the same name: "Building"

This is not a UsabILIty Hub issue, but the current UsabILIty Hub implementation will have trouble with it.

**Comment by signedav** [comment]
Simplest solution would be to generate a super long layername as the second instance of it,  like "DavesCity_V1_1_Constructions_Building" - but probably a nicer way would be to create "Building (DavesCity_V1_1.Constructions)" and "Building (City_V1_1.Constructions)"

Another thought is to be able to name the layers over the yaml as well. A solution would be to get the "ili-layer" by it's `ili_name` and set the `layer.alias` accordingly:
```
        if "ili_name" in item_properties:
            found_layer = [layer for layer in layers if layer.ili_name == item_properties["ili_name"] and layer.geometry_column == item_properties.get("geometry_column")][0]
            layer = found_layer
            layer.alias = node_name
```

**Comment by signedav** [comment]
Independently from the thoughts in @461 I will check out the approach with "ili_name" as reference in the projecttopping file of the UsabILIty Hub. This will bring us general benefits like e.g. being able to rename layers with the topping.

**Comment by signedav** [comment]
In fact I think an implementation of `tablename` and `geometrycolumn` would make more sense than `iliname`, to support non-interlis tables as well to be found in the schema and add to the project.

**Comment by pramisters** [comment]
IMHO you don't get tables with identical names when you generate the database structure of an extended model.
Try https://models.geo.zg.ch/ARV/ZG_Nutzungsplanung_V1_1.ili and check the created table names in PostGIS.
ili2pg adds a prefix to the table names of the extended model. The prefix combines model name and topic name.

It's only Model Baker that names the two tables in the layer tree identically. 
But IMHO this issue can be closed anyway as there's no need to load the base layer to the layer tree (#461)

**Comment by signedav** [comment]
Yes. It's about the layer names (named by Model Baker) and not the table names (named by ili2db). They could have duplicates (at least as long we load the ones from the base model as well). The UsabILIty Hub solution used to identify layers by it's name, but with the rrnaming possibility identifying the layer by its `iliname` or`tablename`/`geometrycolumn` that's solved anyway.

See https://opengisch.github.io/QgisModelBaker/background_info/usabilityhub/modelbaker_integration/
