### ISSUE TITLE
Validator: allow to specify a data source (PG DB Schema) to validate

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#668]
Currently it is not possible to actively select a PG DB schema for validation (like it is possible in the XTF exporter tool)

It would be useful to have a data source selector and then model selector for validation.

**Comment by signedav** [comment]
So it will make a validation but does not offer "Open Form" / "Zoom to Coordinates", right?

**Comment by andreasneumann** [comment]
If the project doesn't contain the layers, then it won't be possible to use "Open Form" "Zoom to Coordinates".

However, if the open project contains these layers (because they have been imported with ili2db (manually, not necessarily through ModelBaker)) then it would still be nice to have this functionality. Not sure if there is a mechanism to find out if the layers that checked with Validator are present as a layer in the project?

**Comment by andreasneumann** [comment]
Currently, I can't even validate a model generated by ModelBaker from "Postgis" source (but imported into PG manually with ili2db). Validation is always greyed out (disabled).

**Comment by signedav** [comment]
To clarify: It doesn't matter for the Model Baker Validator if it's created by Model Baker or by ili2db and added manually.

I think what you experience in your described use cases is a bug or a missing part.

**Comment by signedav** [comment]
Maybe it's because of using pg-services? Then this would be the required part.

**Comment by signedav** [comment]
Oh and another thing. When the credentials are not saved in the layer (and just entered by the user in the current session). I guess this won't work neither.

**Comment by signedav** [comment]
Can you confirm that?

If it is like this, I think it would make sense to implement those bits.

If we would have those, would it still be required to have a dialog to set the DB schema?

**Comment by andreasneumann** [comment]
I believe I found out why it wasn't working.

I first have to save - and reopen - the project before the validator starts being active.

When I am simply generating the project from scratch (blank new project), validation stays inactive. When I save the project to a file and then reopen the project, validation becomes active.

Can you confirm that this might be the case?

**Comment by signedav** [comment]
I didn't experienced that. The validation should become active as soon as an "interlis-layer" (means a layer from a schema created by ili2db) is active (means selected).

**Comment by andreasneumann** [comment]
I believe I should call you on the phone and we could do a screen-sharing - so I can better explain the behaviour.

**Comment by andreasneumann** [comment]
> The validation should become active as soon as an "interlis-layer" (means a layer from a schema created by ili2db) is active (means selected).

Ah - that explains it: I didn't have a layer "activated" after project generation. Saving and reloading the project also activates the first layer by default.

That explains why it became "active" after project reload.

I can confirm now, that the data validation becomes active as soon as I activate an "Interlis layer".

**Comment by signedav** [comment]
@andreasneumann 

Before I make a time estimation I would like to know the exact requirement and list here what is working and what is not working.
- [x] validate layers (by it's selection that are not created with Model Baker works. It gets the connection to the schema and reads the ili2db metatables.
- [x] validate layers containing username/password or QGIS authentification works
- [ ] validate layers containing a service does not work yet
- [ ] validate schemas that are not in the project at all do not work yet

Am I right that you would like to have an estimate for the two points that are not working yet?

**Comment by andreasneumann** [comment]
@signedav - sorry for the delayed response

I did some tests and can confirm that the first two items already work.

It is the third item (validate layers containing a service) that we need to get implemented. We don't need the fourth item. However, the login and password is not in the service config file. It is stored in the QGIS auth config. Therefore you can't retrieve the user and pw from the service file, but you need to retrieve them from the QGIS auth config. Is this technically possible at all?

There are separate issues about the support of service names that we need to get addressed (as soon as a select a service, all other config options are greyed out - and I'm not able to specifiy an auth config or SSL mode) - I'll open a separate issue for that.

**Comment by signedav** [comment]
Okay so we forget about the option to configure the database connection in the validator for the moment and focus on the service config file. 
- [ ] validate layers containing a service (needs to get pw and user from service in get_configuration_from_layersource)
- [ ] validate layers containing a service and still read the pw and user from the QGIS auth

The use case having a service name and an QGIS auth, means in the service there are no username / password / ssl mode defined?
