### ISSUE TITLE
Usage of service name greys out all other options (like auth/login/SSL)

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#688]
As soon as I select a "service", all other options, except the "Schema" is greyed out.

We need to be able  specify SSL mode and auth config choice independently of the service config definition, as both are not contained in our service definition. We have a shared service config file for all users, thus we cannot (and don't want to) store login and pw in the service config file.

![ModelBaker_ServiceDefinition](https://user-images.githubusercontent.com/884476/165920425-2b1a1312-b8d6-4a47-bdc8-dfeb60480c36.png)

**Comment by signedav** [comment]
So the selection of  the service should:
- clean password username field if no password username is defined
- set SSL to none if no mode is defined
- keep those fields editable (where nothing is defined)

**Comment by andreasneumann** [comment]
> So the selection of the service should:
> 
>     * clean password username field if no password username is defined

yes - but normally we don't use the user/pw config, but an auth-config (see section "Authentifikationskonfiguration wählen oder anlegen").

>     * set SSL to none if no mode is defined

yes

>     * keep those fields editable (where nothing is defined)

yes
