### ISSUE TITLE
QGIS crash when Selecting data file in Modelbaker

### ISSUE THREAD

**Issue by sjib** [opengisch/QgisModelBaker#690]
## User Feedback

Selecting data file in Modelbaker

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000086e4 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.0-Tisler
QGIS code revision: 6b44a42058
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**ModelBaker**
Installierte Version | 7.1.5

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by romefi** [comment]
Does this happen when you select a file in this step in the wizzard?

![image](https://user-images.githubusercontent.com/26796989/166625851-a1dc1d06-ebb2-45e1-96ad-bd346513afc3.png)

Couldn't reproduce it. Does it crash with any file you try to add? If it only happens with a specific file, could you share the file?

**Comment by signedav** [comment]
@sjib Any news on that?

**Comment by sjib** [comment]
@signedav Yes it happened at that step.

**Comment by signedav** [comment]
When pressing to the `...` or when you choose a file there pressing `open` or when you press `+`. Can you please add the file and a gif/video?
