### ISSUE TITLE
Displayname of dataset/basket

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#696]
Not sure if there's already an issue with same topic. Anyway...

I generated a project for KbS_V1_5 and imported data for canton SH and canton TG. Now I have three baskets for `KbS_V1_5.Belastete_Standorte`.

![image](https://user-images.githubusercontent.com/26796989/170058684-fa667b2b-0df6-4c59-a210-392aa46b91d1.png)

As `topic` is the displayname for dropdown of the baskets, it's impossible to know, which basket is meant.

![image](https://user-images.githubusercontent.com/26796989/170059040-526fece1-9266-4a99-81bd-d39fe4b91daa.png)

Probalby it's better to display the value of `attachmentkey`?

Would of course affect the dropdown in the toolbar as well as the `t_basket` in objectform.

![image](https://user-images.githubusercontent.com/26796989/170060599-4966d194-babb-4e82-a0f9-3cf23be0d707.png)

**Comment by signedav** [comment]
Shouldn't in that case the datasets be 'Schaffhausen' and 'Thurgau' or what do you want to achieve? Create a new dataset containing all the data in two baskets?

**Comment by signedav** [comment]
It's not usual to have multiple baskets of the same topic in the same dataset (Baseset). You should import your data into datasets like 'Thurgau' or 'Schaffhausen'. But I see that it's what is done on default when not creating new datasets on import. Maybe it shouldn't be there. 

Anyway I'm not completely happy about this automatically created Baseset and its baskets. But I don't see another sollution to provide the users default baskets to start collecring data. Except to make another step in the wizard what I think is the step to go in the future.

**Comment by romefi** [comment]
Ok, got your point. That's actually the problem as I just clicked through the wizzard. Maybe we keep in mind to improve that in future.

**Comment by signedav** [comment]
This should be solved with something like the basket creation page #599
