### ISSUE TITLE
New Entries in t_ili2db_dataset and t_ili2db_basket should be optional

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#708]
ModelBaker automatically creates records in t_ili2db_dataset and t_ili2db_basket after schema import, without checking if the entries already exist (through an automatic import of an XTF or postscript.sql skript).

The creation of these entries should be optional, or ModelBaker should first check if entries already exist.

![image](https://user-images.githubusercontent.com/884476/177779787-5f0ea725-afd9-4440-94e8-c1f86d5327f9.png)

and

![image](https://user-images.githubusercontent.com/884476/177779826-e484117d-2096-4189-9351-fc1bac51e085.png)

In the screenshots, the blue records had been created by ModelBaker, while the other records had been previously imported through a migration SQL skript (postscript.sql).

**Comment by signedav** [comment]
Related to #599 at least to the comment here https://github.com/opengisch/QgisModelBaker/issues/599#issuecomment-1091145098

**Comment by signedav** [comment]
Solved by this https://github.com/opengisch/QgisModelBaker/pull/846
