### ISSUE TITLE
When using PG service configuration, previous settings for schema, SSL mode and auth-config are not preserved

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#709]
When using PG service configurations, settings for DB schema, SSL Mode and auth config are not preserved from one run to the next one.

![image](https://user-images.githubusercontent.com/884476/177780442-ccb2657a-5979-4f0e-9e4a-d3dc5e11e8d1.png)

**Comment by andreasneumann** [comment]
@signedav mentioned that the behaviour to preserve (store and retrieve) previous settings doesn't work yet in conjunction with PG service configurations.

**Comment by signedav** [comment]
On changing a service, the content of the service is loaded to the GUI. If something is not in the service, the field is empty and available for the user to enter content manually. This request needs to evaluate if the field is (1) not receiving content from the chosen service and (2) has had a manually entered content once before. So it should store this info in the background as it's done with "None" service. 

Not clear yet if it should write those information into the settings as well to be able to use them after restarting QGIS.
