### ISSUE TITLE
Cancel java process when closing Model Baker Wizard

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#714]
When having a java process running (ili2db) and one closes the Model Baker Wizard window. The process is still running in the background.

It should cancel the java process or even ask the user "Do you want to cancel the process?"

**Comment by sjib** [comment]
Is there a reason to not cancel the process? ili2db blocks also the files that are selected - so I would vote for just cancelling it.

**Comment by signedav** [comment]
When the user presses "No", then the Dialog would not close. Maybe needs better wording. Like:
"When Model Baker Wizard is closed, a running ili2db process will be canceled. Do you really want to do that?"

**Comment by signedav** [comment]
... and maybe even a "Cancel Process" Button would be nice. So the user does not need to restart the wizard. 

E.g. the user forgot to "Run without validation" etc...

**Comment by signedav** [comment]
The "Cancel" button is implemented here #761 but not the canceling on closing the dialog.

To solve that one should catch the `reject()` function of the wizard dialog and close all the running sessions (and processes). This is currently not prepared for that. Because we wait until the `IliExecutable.run` returns we are already "destroyed" when the QProcess is terminated by a signal. 

To solve that it would make sense to create the `SessionPanel` independently from the dialog. And display the status (e.g. progress bar) according to a signal. And maybe implement `waitForFinished()` functionality. 

I think we can offer a cost ceiling of a day for that.
