### ISSUE TITLE
Error on getting the connection parameter from layer when uri has spaces

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#730]
When having spaces in the path:
```
/home/dave/simple model_08.gpkg|layername=house
```

There are errors on every `db_utils.get_configuration_from_layersource` (as well as `get_schema_identificator_from_layersource`)

The reason is, that we pass the uri to the `QgsDataSourceUri` and later we get it again. But then it's cropped.
```
source = QgsDataSourceUri(layer.dataProvider().dataSourceUri())
dbfile = source.uri()
# dbfile is " model_08.gpkg|layername=house"
```

So the problem is in `QgsDataSourceUri::uri`? Not sure if it's an easy fix on QGIS.

A solution for Model Baker would be to pass the uri as `layer.dataProvider().dataSourceUri()` to the functions and read the dbfile from there...

**Comment by sjib** [comment]
We had a similar problem and fixed it like this: https://github.com/QGEP/qgepqwat2ili/pull/60

**Comment by signedav** [comment]
Thanks. But this is another issue. We get a wrong uri from QGIS over the API when to he sourcepath contains spaces...

**Comment by signedav** [comment]
I decided to use just the `dataProvider().dataSourceUri()` directly. First because I needed a fix anyway (because even when it would be fixed in later QGIS Releases, Model Baker should support 3.22 and possibly 3.16 as well) and second, because it does not bring an advantage over using `dataProvider().dataSourceUri()`

But I did some research and found out, that the current master acts differently than 3.22.11.

**3.22.11**
```py
>>> ayer = iface.activeLayer()
>>> source = QgsDataSourceUri(layer.dataProvider().dataSourceUri())
>>> source.uri()
" model_08.gpkg|layername='house'"
>>> source.encodedUri()
PyQt5.QtCore.QByteArray(b'model_08.gpkg%7Clayername=house')
```
Here we had no chance to get the correct filename.

**Current master 9eedb44e26028dd50a34650da41a73e23dc1d435**
```py
>>> layer = iface.activeLayer()
>>> source = QgsDataSourceUri(layer.dataProvider().dataSourceUri())
>>> source.uri()
'' 
>>> source.encodedUri()
PyQt5.QtCore.QByteArray(b'/home/cheapdave/qgis_projects/geolassets_followup/baseexporttest/simple%20model_08.gpkg%7Clayername=house')
```
Here we could get the correct path from `encodedUri()` but as I mentioned. For modelbaker the way with `dataProvider().dataSourceUri()` does it.
