### ISSUE TITLE
Metakonfiguration / Topping:  Only display The Topping Title in the Browser

### ISSUE THREAD

**Issue by threalslimtobeeee** [opengisch/QgisModelBaker#756]
I might be more user-friendly to **just** show the topping title when Browsing for Toppings/Metakonfigurationen.

e.g.

Situation:
![grafik](https://user-images.githubusercontent.com/44619605/201924270-b66b0306-8ebd-4c82-b559-3bc5b59256ab.png)

Proposal:
"Erfassung gpkg"

**Comment by signedav** [comment]
Good input. Thanks.

**Comment by signedav** [comment]
This is not an issue of the workflow wizard on create - it's already displaying the title. But the title is not that nice created by the topping exporter. So I suggest to improve the exporter by having in the title only the project name, and then in the description this text.
