### ISSUE TITLE
Toppings: Referenced Files should be selected for import automatically

### ISSUE THREAD

**Issue by threalslimtobeeee** [opengisch/QgisModelBaker#757]
Situation:

Data which is referenced in the metaconfig.ini can be selected for the import when generating a project with a topping
![grafik](https://user-images.githubusercontent.com/44619605/201926198-ced5884d-2a88-4ab4-b1e0-f92b2feec3af.png)

Proposal:
The Data which is referenced is selected by default for the import
![grafik](https://user-images.githubusercontent.com/44619605/201926386-345773e8-db4c-46b2-8565-b3e00b6d74ce.png)

**Comment by signedav** [comment]
Thanks. There are two ways to handle reference data (mostly catalgues) in UsabILIty Hub. 

1. select it in the exporter -> having it automatically added to your import session (actually what you require here)
2. have the catalogue listed in your ilidata.xml and have it visible for the specific models that require them. This works without UsabILIty Hub topping structure as well. Is kind of an additional thing - so you can even choose the catalogue from the repo when you don't choose the rest of the topping. https://opengisch.github.io/QgisModelBaker/background_info/usabilityhub/modelbaker_integration/#directly-referenced-catalogues

I think you experienced /2 but expected /1 - this is a bug  #753 that is already fixed #755 - with version 7.2.5 this should be solved.

If you want to fix your link in the metaconfig  (INI file) manually you can add `ilidata:` in front of the link to the catalogue.

**Comment by signedav** [comment]
Just seen your file in the repo. You have there this entry:

```
ch.interlis.referenceData = ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Kataloge,SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Spezies,SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Typ_Delarze
```
This should look like this:

```
ch.interlis.referenceData = ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Kataloge,ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Spezies,ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Typ_Delarze
```
3 times `ilidata:` instead of just the first time.

Did you created that with 7.2.5? If so, the bug is not properly fixed. Or you did it manually? Then check again, please. Thanks a lot.

**Comment by signedav** [comment]
I think the bug is the comma separator. It should be a semicolon. I'll have a look.

**Comment by threalslimtobeeee** [comment]
I added "ilidata:" and the semicolons. 

Now it works properly and looks like this:
`ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Kataloge;ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Spezies;ilidata:SZ_Biotopinventar_kommunal_V2_1.Erfassung.Stammdaten.Typ_Delarze`

Also, the download of the Topping is much faster now.
