### ISSUE TITLE
Toppings: Possible incompatibilities (ili2b/qgis forms)

### ISSUE THREAD

**Issue by threalslimtobeeee** [opengisch/QgisModelBaker#758]
With the possibility to adjust ili2db options during the topping export, it is possible to export layer styles and ili2db options (e.g. handling of enumerations) in the same step, which are not compatible with each other. The basic question arises, how much a person who wants to export toppings should know about ili2db and the form design in QGIS. And for whom the Topping Exporter is designed.

**Comment by signedav** [comment]
Thanks.

Did you notice, that the settings - at the moment - are only listed as an information and not adjustable (read only). Is your request to keep it like that and not make it adjustable (what could be requested in future)? 
Or not showing them at all? The reason why they are shown is for the case when the QGIS Project is based on multiple schemas (and model imports) and the user needs to choose which one should be considered.

**Comment by threalslimtobeeee** [comment]
Thanks for the clarification. I did not notice that. In my view it should be kept as an information and remain read only.
