### ISSUE TITLE
Enable Topping import for genrating projects from existing databases

### ISSUE THREAD

**Issue by threalslimtobeeee** [opengisch/QgisModelBaker#768]
Proposal:
- The import of Toppings should also be possible when generating projects from existing databases.

Pros:
- When a project is corrupt, one could easily restore them without regenerating the database and reimporting the data
- One could set up the project for different users and do not have to share projects which were probably changed by the user after they were generated

Cons:
- Compatibility-issues for users using the proposed option with a generated database which is not compatible with the database they have generated (see. #759)

This is an idea which my organization would benefit from. It must be discussed whether other users would also benefit from it, or if the dangers of incompatibilities/complexity is too big.

**Comment by signedav** [comment]
Thanks @threalslimtobeeee This idea came up already once #479 and your thoughts about the risks are very reasonable. Still I can imagine it's a valid use case.

So what we do with the risk (db-source, meta attributes, etc.)?
The most simple solution is leaving it to the user ¯\_(ツ )_/¯

Maybe the naming implying the db-source makes sense or this idea https://github.com/opengisch/QgisModelBaker/issues/479#issuecomment-1076171494 could narrow the risk. But still we cannot know if the schema has been created with what meta attributes (TOML) file.

**Comment by threalslimtobeeee** [comment]
Oh, sorry for not checking....

I think for now, "leaving it to the user" and naming conventions are viable ways.

An approach for the future could be a process, that creates an information ("log") which Topping was used to generate the database into the database itself. The generation of the project would then be restricted to that Topping. This would assume that published toppings are not changed and/or properly Versioned...

**Comment by signedav** [comment]
Yes. We could start with a "leaving it to the user" sollution and build on it when users had some (maybe bad) experiences with it.

**Comment by signedav** [comment]
Are you interrested in an estimate for that @threalslimtobeeee? As well for #756 and #759?

**Comment by threalslimtobeeee** [comment]
I will contact you via email.
