### ISSUE TITLE
Button to clear ilicache

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#776]
Lots of users struggle with the .ilicache. Either they are not aware or they don't know that there is a .ilicache which could cause some problems.

It would be fancy to have a "Clear ILI-Cache" Button in Model Baker, so users (a) know that there is a cache and (b) can empty the cache very easily without having to know how ili2db handles the cache.

E.g. like this:

![image](https://user-images.githubusercontent.com/26796989/212099698-7520ccf5-9abb-482a-824f-d9a8c9d98565.png)

**Comment by sjib** [comment]
This still leaves the question open, when I have to clear the cache. This should be documented.

**Comment by romefi** [comment]
It should be documented what the button stands for at what it does, I agree. Most problems occur when a model receives a patch change and keeps the model version. That's one major reason, to clear the cache.
