### ISSUE TITLE
modeldir for data validation

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#781]
We have a customized model folder in the settings of Model Baker, where we have an additional model for additional constraints.

At validation it says the model is not found.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/26796989/216079827-7f303ec5-f752-4205-b8f6-96bda38a48c4.png)

In the wizzard on the other hand, the model is recognized.

Does the customized model folder in the settings also apply to data validation? If not, it would be super fancy.

**Comment by signedav** [comment]
If it's missing. I agree it should not. Need to check. IMO it's a bug when it's missing.

**Comment by romefi** [comment]
@signedav Do you think this could be fixed approximatly by end of february in an new Model Baker version? We're working on a project where we would love to use data validation with an additional model which is not in an INTERLIS repository.

**Comment by signedav** [comment]
I think it's a small fix. So this is realistic.

**Comment by romefi** [comment]
Thanks. You can bill it on the support hours of Schaffhausen if necessary.

**Comment by signedav** [comment]
I had a look and found it.

But could you provide me those models? The simple test I made with a model depending on another one is not sufficient.
