### ISSUE TITLE
Problem with gpkg created with modelbaker

### ISSUE THREAD

**Issue by urskaufmann** [opengisch/QgisModelBaker#782]
Can not work with a gpkg created with modelbaker when adding additional layers to the gpkg

To reproduce:
- Drag the ili-File on QGIS (new project) and create a new gpkg and the corresponding project with modelbaker. The project works (close, open etc.)
- Add another table to the gpkg e.g. by exporting a table to the gpkg-> gpkg_plus_table
- Open the modelbaker-project or drag the gpkg_plus to a new project: must of the layers (in the example: all domain-tables) are no more valid. Valid is the table added without modelbaker and the tables, that are not domain-tables.
- Look at the gpkg: it seems ok, all data is there
-  Copy all tables in a new gpkg and drag it to a new project: all data is there, it works!

Attached the files to reproduce:
ili File: SK1_3_d_LV95.ili (a subset of VSA-DSS-mini Version 2020)
gpkg-File: sk_modelbaker.gpkg
qgs-file: mobaker.qgs
additional table: sk_t_type layer in new_table.gpkg
qpkg-File with additional table: sk_modelbaker_plus_sk_t_type.gpkg
screenshot of the crashed project

Versions
QGIS 3.28.2
Win 10
Modelbaker 7.3.2

[problem_with_gpkg_mobaker.zip](https://github.com/opengisch/QgisModelBaker/files/10561684/problem_with_gpkg_mobaker.zip)

**Comment by signedav** [comment]
Okay, I could reproduce it. Apparently only tables without geometry are affected.

1. Import this model with ili2db:
    ```
    INTERLIS 2.3;
    MODEL MostSimpleModel_V1 (de)
    AT "mailto:signedav@localhost"
    VERSION "2023-01-19" =
      TOPIC Konstruktionen = 
        CLASS Gebaeude =
            Strasse : TEXT;
        END Gebaeude;
      END Konstruktionen;
    END MostSimpleModel_V1.
    ```
    When now the project would be generated by Model Baker or with drag and drop in QGIS, everything's fine.

2. Create new Layer (with QGIS) and add a layer with or without geometry / with or without any fields to the Geopackage.

    When now the project would be generated by Model Baker or with drag and drop in QGIS, all the layers without geometry are invalid and cannot be recovered.

**Comment by signedav** [comment]
Some notes:

When a table is created, with it an `fid` is created and a table called `sqlite_sequence`. But this is done as well when I import (with drag and drop) or create (with SQL) the very same label with the ***DB Browser for SQLite*** and there, no problem occurs...

**Comment by signedav** [comment]
Opened an issue at QGIS https://github.com/qgis/QGIS/issues/51721

**Comment by signedav** [comment]
It's fixed in GDAL. See referenced QGIS issue. On further problems feel free to reopen this issue.
