### ISSUE TITLE
Nicer outputs on Java / PG errors

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#785]
On having Java not installed the user gets a JavaNotFoundError with a Python stack.
The Scram issue reported here #779 is a line at the end of the log.

Those errors could be handled nicer. With popup "Do you have Java installed? If not follow this instruction" etc..

**Comment by domi4484** [comment]
On a fresh windows installation without java it looks like that for me:

![image](https://github.com/opengisch/QgisModelBaker/assets/9881900/a13b1b48-04aa-416c-92ab-dfbe96bced7c)
