### ISSUE TITLE
Validation failed with `additionalModel`

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#789]
Wenn ich ili2db aufrufe mit `--validate` und ein `--validConfig` mitgebe, dass ein `additionalModels` enthält, dann gibt es einen Fehler:

**Configfile:**

```
["PARAMETER"]
additionalModels="SH_Pflegeplanung_Fliessgewaesser_V1_0_AddChecks"
```

**ili2db Aufruf:**

```
java -jar /home/dave/dev/opengisch/QgisModelBaker/QgisModelBaker/libs/modelbaker/iliwrapper/bin/ili2gpkg-4.10.0/ili2gpkg-4.10.0.jar --validate --dbfile /home/dave/qgis_projects/repo_validation/data2.gpkg --models SH_Pflegeplanung_Fliessgewaesser_V1_0 --modeldir "http://models.interlis.ch/;/home/dave/qgis_projects/repo_validation" --validConfig /home/dave/qgis_projects/repo_validation/SH_Pflegeplanung_Fliessgewaesser_V1_0_ValidConfig.ini
```

**Output:**

```
[...]
Info: SH_Pflegeplanung_Fliessgewaesser_V1_0.Pflegeplanung.Fauna...
Info: additional model SH_Pflegeplanung_Fliessgewaesser_V1_0_AddChecks
Error: required additional model SH_Pflegeplanung_Fliessgewaesser_V1_0_AddChecks not found
Info: second validation pass...
...validate failed
```

Währenddem ein (meines Erachtens) äquivalenter Aufruf beim ilivalidator erfolgreich das `additionalModel` findet:

**ilivalidator Aufruf:**

```
java -jar /home/dave/tools/ili2/ilivalidator/ilivalidator-1.13.0.jar --models SH_Pflegeplanung_Fliessgewaesser_V1_0 --modeldir "http://models.interlis.ch/;/home/dave/qgis_projects/repo_validation" --config /home/dave/qgis_projects/repo_validation/SH_Pflegeplanung_Fliessgewaesser_V1_0_ValidConfig.ini /home/dave/qgis_projects/repo_validation/export.xtf
```

Output:
```
[...]
Info: additional model SH_Pflegeplanung_Fliessgewaesser_V1_0_AddChecks
Info: second validation pass...
[...]
Info: ...validation done
```

**Update:**
Wenn man `--exportModels SH_Pflegeplanung_Fliessgewaesser_V1_0_AddChecks` anfügt (und somit auch `SH_Pflegeplanung_Fliessgewaesser_V1_0_AddChecks` im Schemaimport vorausgesetzt ist) scheint es das Modell zu finden  - bzw. gibt es keinen Fehler. Doch wenn man das Schema mit diesem Model erstellt und mit `--exportModels` validiert, braucht es ja die `additionalModels` nicht mehr...

Ist also `additionalModels` im ili2db nicht unterstützt oder fehlt noch eine Info im Aufruf? Fals ersteres zutrifft, dann die Frage, was ist alles im Config-File möglich, das mit ilivalidator funktioniert, nicht aber mit ili2db?

**Comment by signedav** [comment]
After this #781 your use case @romefi encountered another problem only concerning the `additionalModels`. I'll have a look at it.

**Comment by Philippluca** [comment]
@signedav ili2db beschreibt in der [User-Doc](https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst) den parameter `--exportModels`. Aus der Beschreibung lässt sich ableiten, dass ili2db bei einem Export jeweils nur die beim Schema-/Import mitgelieferten Modelle in Betracht zieht. Inwiefern dies mit der TOML-Option `additionalModels` überhaupt funktioniert bin ich mir nicht sicher. Allenfalls kannst du im TOML versuchen auch die `exportModels` entsprechend zu definieren.

**Comment by signedav** [comment]
Danke für den Input.

So wie ich `--exportModels` verstehe, definiert das in welchem "Format" die Daten exportiert / validiert werden sollen. Würde bestimmt Sinn machen, dies auch im Validator verfügbar zu haben (evtl. im Zusammenhang diesem Fix für  #665). 

In diesem Fall hier ist es so, dass das `additionalModels` zwar funktioniert mit `--exportModels`, sofern das Modell auch importiert wurde (wie du sagst), doch verstehe ich dennoch nicht, dass das `additionalModel` ansonsten nicht gefunden wird, währenddem es im ilivalidator mit einem XTF funktioniert, das ohne `--exportModels` exportiert wurde. Irgendwie nahm ich deshalb an, dass das `additionalModel` das Format von sich selbst vorgibt. Aber so weit kommt es ja gar nicht erst, da es nicht gefunden wird...

**Comment by signedav** [comment]
Danke @Philippluca 

Claude meinte ich soll einen Issue auf ili2db eröffnen. https://github.com/claeis/ili2db/issues/509 - deshalb schliess ich den hier.
