### ISSUE TITLE
Problem with encoding in wizzard

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#799]
The wizzard has a wrong encoding. Occurs to all steps in the wizzard.

![image](https://user-images.githubusercontent.com/26796989/230338232-90c1994e-c6a8-4641-8008-80d4034a471e.png)

**Comment by signedav** [comment]
When I do convert the `qm` files back to `ts` files I can see the difference:
```
$ lconvert QgisModelBaker-7_3/i18n/QgisModelBaker_de.qm -o 7_3.ts
$ lconvert QgisModelBaker-7_4/i18n/QgisModelBaker_de.qm -o 7_4.ts

$ diff 7_3.ts 7_4.ts 
[... some more]
32c28
<         <translation>Wähle zu importierende Transferdateien und Models oder erstelle eine neue Datenbank</translation>
---
>         <translation>WÃ¤hle zu importierende Transferdateien und Models oder erstelle eine neue Datenbank</translation>
[... and more]
```

@3nids since release 7.3 was before the broken transifex functionality in the qgis-plugin-ci and 7.4 was after the fix of it, I wonder if you have an idea, what the reason for this issue is?

**Comment by signedav** [comment]
Since there has not been added lots of translatable strings with the 7.4 I replaced the `i18n` of the release 7.4.2 now with the `i18n` of 7.3.2 - so the current stable release should not have the bug.

Could you reinstall it @romefi and check it out?

**Comment by romefi** [comment]
The bug is fixed, looks good in the new stable version. Thanks!

**Comment by signedav** [comment]
Thanks for confirming. Still there is a bug, as soon as we have new translations we cannot use the "old" stringset anymore...
