### ISSUE TITLE
Store path "Validator config file" in Data Validation in QGIS project

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#820]
We outsource our checks for a model to an additional model, which should only be used while checking. Therefore we'd love to save the path to "Validator config file" in the QGIS project.

![image](https://github.com/opengisch/QgisModelBaker/assets/26796989/d53662e6-cfd8-4a86-8c73-829c16bc4db9)

So we cann assure, that the user is always testing with the additional model and don't have to (a) know where the ini-file is and (b) add the ini-file each time he wants to check the data.

**Comment by signedav** [comment]
You are suggesting the QGIS Project because you want to be able to share it and to store it in the Model Baker Settings (per profile) would not help, right?

**Comment by romefi** [comment]
No, because the path is not related to the user, but to the model you're working on in the QGIS project. Each QGIS project has therefore another path to the ini-file. And there could be different users working on the same QGIS project.

**Comment by signedav** [comment]
Aight. Of course it would even in the Model Baker store this path per selected model and not in general. But yes I understand that the purpose of your request is to have it per QGIS project.

So the questions would be:

- **_Where to store it._** I see the possibility to store it as property in the project or as project variable. Pro on property is that it's hidden, pro on variable is that it's visible :-) It's always good to have transparency on such settings, but ugly if you could change it on multiple places (like the plugin and the variables).
- **_When to store it._** 1. should every config file we set on the validator be stored to the project? This could lead to troubles as well. Anyway, we would need a. an action on project store to write the validator settings to the project or b. a button (next to the configfile in the validator) "remember config" (then it's stored to the project, and on save it's there).

@domi4484 any thoughts?

**Comment by signedav** [comment]
Any feedback on that @romefi @domi4484 ? I think I would prefer it as variable and with "remember" functionality. 

Another thought: we might store it per schemaname, in case of multiple sources per QGIS project.

**Comment by romefi** [comment]
@signedav I think a variable with "remember" functionality would do it.

Also storing by schemaname is a good idea, didn't think of that.

If @domi4484 agrees on the approach, you can send me an offer. We'd love to have it asap (as usual :))

**Comment by domi4484** [comment]
I agree, with a little preference for variable over property.
I also prefer the "remember" functionality over an explicit save button
