### ISSUE TITLE
Database Settings in Export / Dataset Manager / Validator

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#847]
The current implementation is like this. When opening...
- ... Wizard > Export: We see the last used db connection
- ... Dataset Manager: We see the last used db connection
- ... Validator: We have (not editable) the db connection of the currently selected layer

![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/50b39a53-c6a3-467a-9f95-152ffa99129b)

This behavior is a little confusing. Both ways have pros and cons. Pro on the last used db connection and having it editable is that you don't need to have this schema in the current project. The con is, that you have to set it manually if it does not correspond to your current project. 

### My thoughts
I like, that we cannot edit the db-connection in the Validator. Because the results points then to the data in the current project so it would be very misleading. So I would not change there anything.

I find it confusing that I open the Dataset Manager or the Wizard > Export and it does not correspond to the schema I have in my current project (what is mostly only one), but it's fine to be able to change them.

### Question

What would be the best behavior on Dataset Manager and Wizard Export?

1. Connection should be taken over *automatically* from the currently selected layer's datasource
3. Connection should be taken over *on request* (means by button) from the currently selected layer's datasource
4. It's perfect like it is now...
5. other

Any opinions?

**Comment by webrian** [comment]
Thanks for raising this issue, some time ago I came across this, too. So in my opinion:

* Wizard > Export: connection is taken over _automatically_ from the selected layer, but the connection is still editable. So it is still possible to export from another database schema.
* Dataset Manager: connection is taken over _automatically_ from the selected layer, the connection is not editable. I guess it is not meaningful to edit datasets from a database schema which is not loaded.
* Validator: leave it as it is.

Just as a side note: it could also be handy to export data directly from the Data Validator panel (with the same settings concerning models, baskets, datasets etc.)

**Comment by signedav** [comment]
Thanks. I completely agree on your opinion.

I thought that on Dataset Manager one might need another user with more permissions. But in the end it's only creating data - the same what we do on digitizing. So this won't mind I guess.

> Just as a side note: it could also be handy to export data directly from the Data Validator panel (with the same settings concerning models, baskets, datasets etc.)

Yes, I can imagine that this would be useful. I'm just a little careful in introducing new options in the validator panel since it's growing quite fast. But the idea is good.

**Comment by signedav** [comment]
See #936
