### ISSUE TITLE
TID (OID) Manager does not open when raster layers are loaded in project

### ISSUE THREAD

**Issue by webrian** [opengisch/QgisModelBaker#849]
Thank you for releasing version 7.7.0 @signedav !

When I load a raster layer (namely a WMS layer if that matters) in a project and open the `TID (OID) Manager` , the dialog does not open, but a Python `AttributeError` is thrown:

> AttributeError: 'QgsRasterLayer' object has no attribute 'fields' 
> Traceback (most recent call last):
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\qgismodelbaker.py", line 363, in show_tidmanager_dialog
>     self.tidmanager_dlg = TIDManagerDialog(self.iface, self.iface.mainWindow())
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\tid_manager.py", line 46, in __init__
>     self.tid_configurator_panel.setup_dialog(QgsProject.instance())
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\panel\tid_configurator_panel.py", line 71, in setup_dialog
>     self._reset_tid_configuration()
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\panel\tid_configurator_panel.py", line 74, in _reset_tid_configuration
>     self.layer_tids_panel.load_tid_config(self.qgis_project)
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\panel\layer_tids_panel.py", line 257, in load_tid_config
>     self.tid_model.load_tid_config(qgis_project)
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\panel\layer_tids_panel.py", line 181, in load_tid_config
>     self.oid_settings = QgisProjectUtils(qgis_project).get_oid_settings()
>   File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libs\modelbaker\utils\qgis_utils.py", line 162, in get_oid_settings
>     fields = tree_layer.layer().fields()
> AttributeError: 'QgsRasterLayer' object has no attribute 'fields'

After removing the raster layer, the manager works again as expected.

**Comment by signedav** [comment]
Fixed in the next release https://github.com/opengisch/QgisModelBakerLibrary/pull/77
