### ISSUE TITLE
Add "Value Relation" widget for enumeration field when DB created with --createEnumTabs

### ISSUE THREAD

**Issue by webrian** [opengisch/QgisModelBaker#859]
On generating a new database, Model Baker uses per default the ili2pg option `--createEnumTabsWithId`, thus a separate table for each enumeration is created linked by a foreign key.

For several reasons we create(d) database schema (outside Model Baker) with the option `--createEnumTabs`, which creates a separate table for each enumeration as well, but _without_ foreign key.
When generating a QGIS project from such an existing database, the enumeration field is implemented as a simple "Text Edit" widget, whereas a "Value Relation" Widget is desirable.

See also this screenshot for the desirable behavior:

![image](https://github.com/opengisch/QgisModelBaker/assets/980073/737d8e7c-4529-4f6c-b9b3-ffc6e2cc499d)

Using the ili2db meta tables it _should_ be basically possible to find out the enumeration fields and the corresponding tables.

**Comment by signedav** [comment]
Related to #511

**Comment by webrian** [comment]
Ok, thanks for sharing and your preliminary work. I see, this is a issue we need to tackle on QGIS side... I know that the `attribute ( get_feature( ))` construct is too cumbersome in rule-based symbology
