### ISSUE TITLE
UsabILIty Hub / Topping Naming

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#863]
Some people complained about confusion when those names popping up. 

#### In the Schema Import Configuration
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/631fd3b4-0ca1-4120-858a-4dedd9f69d62)

#### In the Advanced Settings
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/cc256c92-9383-4e29-aa8a-b9e438da5714)

#### In the Data Import Configuration
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/acf6d5ab-9a22-4c53-9ce3-4c876d7a6da0)

#### On Project Generation 
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/43a528ee-2132-4201-a431-18f70acfed26)

#### as well in the log
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/9d54814a-371e-4175-b015-ca8aeb502de7)

#### And as UsabILIty Hub Topping Exporter
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/aa1e08f0-b528-404d-8c2a-830d919c0a13)

### As confusing it seems, the naming is clearly defined. We have:
- Metaconfiguration File (the INI file containing the ili2db settings, linking to reference data (catalogue), meta attribute files and the project topping file)
- Project Topping (the YAML file containing all the infos used for the QGIS Project and linking to the needed topping files)
- Topping Files (all the Files used in this context: The reference data (catalogue), the meta attribute file, the project topping (see above) and the topping files needed by the project topping (like qml or qlr) files.
- UsabILIty Hub the whole Ecosystem and as well the Network of ilidata files (opengisch-repo and others) and maybe future hub for non-cantonal users...

### Suggestions:
- Use the word topping only for the QGIS related files: project topping (YAML), additional topping files (files used by the project topping like QML etc)
- Use metaconfiguration, reference data, extra meta attribute file etc. no matter if they come from local system, repositories or UsabILIty Hub...
- Not mention UsabILIty Hub (because for an end user it makes no sense to make a difference if this is a file from UsabILIty Hub or another repository) - but very much hesitating. If we won't use the word in the Model Baker Plugin we shouldn't use it elsewhere. But do we want that? It described the whole solution until now quite good. But maybe it's only clear for me. Maybe it would be cool only to use it for the current models.opengis.ch Repository and in case there would be a "public" repository needed for that one...

#### In the Schema Import Configuration
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/631fd3b4-0ca1-4120-858a-4dedd9f69d62)
Here it would be only "Metaconfiguration" and "[Seach metaconfig from repository]"

#### In the Advanced Settings
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/cc256c92-9383-4e29-aa8a-b9e438da5714)
Leave it like it is.

#### In the Data Import Configuration
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/acf6d5ab-9a22-4c53-9ce3-4c876d7a6da0)
Remove "Topping" - maybe use "Referenced Data" and "[Search referenced data file from repository]"

#### On Project Generation 
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/43a528ee-2132-4201-a431-18f70acfed26)
Leave it as it is.

#### as well in the log
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/9d54814a-371e-4175-b015-ca8aeb502de7)
Change accordingly.

#### And as UsabILIty Hub Topping Exporter
![image](https://github.com/opengisch/QgisModelBaker/assets/28384354/aa1e08f0-b528-404d-8c2a-830d919c0a13)
Name it just Topping Exporter.

**Comment by signedav** [comment]
@romefi Your opinion is much appreciated.

**Comment by romefi** [comment]
@signedav sorry for my late reply. I need some more time to think this trough. I fully understand the confusion with all the labels. In particular if you're not familiar with UsabILIty Hub. Maybe there's a way to simplify it even more and make the labels more understable to what they're actually for. I'll come back to you...

**Comment by beistehen** [comment]
> ### As confusing it seems, the naming is clearly defined. We have:
> 
>  - Topping Files (all the Files used in this context: The reference data (catalogue), the meta attribute file, the project topping (see above) and the topping files needed by the project topping (like qml or qlr) files.

This is my biggest struggle: A catalogue being referenced as a Topping File. The concept of transfer data and catalogue data has nothing to do with toppings so these they shouldn't be mixed...

**Comment by signedav** [comment]
I guess you are right @beistehen Though I always thought that a catalogue is kind of a topping file when creating a schema with a model. Because it's in a way more part of the database structure than of the "Nutzdaten" and is used one time when creating the physical DB. Still, as suggested above, it might not be called topping...
