### ISSUE TITLE
warn about missing Java

### ISSUE THREAD

**Issue by 3nids** [opengisch/QgisModelBaker#872]
<img width="953" alt="image" src="https://github.com/opengisch/QgisModelBaker/assets/127259/cbeba3c4-35e0-4d5c-9ff1-d4c93740a0fc">

**Comment by webrian** [comment]
I can confirm this issue on "editing ili2db command" after one or more Model Baker runs. It doesn't happen after a QGIS restart.

**Comment by signedav** [comment]
Even if Java is installed?

Of course when Java is not installed, it should neither run into this error, but print a message...

**Comment by 3nids** [comment]
I didn't have Java installed

**Comment by webrian** [comment]
I have Java installed and _cannot_ reproduce this issue it at the moment. It's ok to me, if you close it @signedav
I'll report back as soon as I can reproduce it.
