### ISSUE TITLE
Export Data: Superuser Login required when using an Authentication Configuration

### ISSUE THREAD

**Issue by webrian** [opengisch/QgisModelBaker#905]
Is there a specific reason why a superuser login is required when using an authentication configuration?

When using a user name and password in Basic Authentication, however, no superuser login is required.

![Bildschirmfoto vom 2024-05-01 10-11-52](https://github.com/opengisch/QgisModelBaker/assets/980073/62833ffe-e01c-4e6b-a1ee-d88ce950b250)

**Comment by webrian** [comment]
No, this is about the _data export_ workflow.

Suppose I connect to the database with a user with read permission (```SELECT``` privileges) only.

**Case A**:
I connect to the database using an authentication configuration (in ```Configuration``` tab):

![Bildschirmfoto vom 2024-05-01 10-11-52](https://github.com/opengisch/QgisModelBaker/assets/980073/570d017f-22e1-4b2e-afa8-239d0053b0a5)

The wizard forces me to check ```Execute data management tasks with superuser login from settings (postgres)```, but 1. as a "normal" user I do not have superuser access to our production database 2. (and more important) it should not be necessary for an export, as no table or schema is changed. Thus no export can be done.

Whereas **case B**:
I connect to the database using Basic auth with username and password (in ```Basic``` tab):

There is no need to check ```Execute ... with superuser login ...``` and it works _anyway_ as expected:

![Bildschirmfoto vom 2024-05-06 11-21-33](https://github.com/opengisch/QgisModelBaker/assets/980073/ecc90651-2993-4456-90e7-d671cd92ae77)

![Bildschirmfoto vom 2024-05-06 11-21-56](https://github.com/opengisch/QgisModelBaker/assets/980073/2ae76542-2e50-4aaf-acb6-d148c582d637)

I don't see any reason why a superuser login is required when using the authentication configuration, but not when entering username and password. On our production database only a few users have more than read privileges on certain selected schemas.

**Comment by gacarrillor** [comment]
> I don't see any reason why a superuser login is required when using the authentication configuration, but not when entering username and password. 

@signedav, for reference, there would be a remaining question/comment by @webrian, although it's not a blocker for closing this issue:

For doing administrative tasks, should the _Use superuser_ checkbox also be required to be checked when using the `Basic` authentication tab ?
