### ISSUE TITLE
Typo 'Tranfer'

### ISSUE THREAD

**Issue by romanmeyerblch** [opengisch/QgisModelBaker#952]
Just a typo that I came across and can't unsee it anymore. Can you kindly insert an 's' in Transfer ? 

![image](https://github.com/user-attachments/assets/6ae4884b-9028-43c9-97a2-0be1e4e66f61)

(I'm posting it here mainly to get used to gitlab.com and see the process evolve.)

**Comment by signedav** [comment]
Thanks. Fixed for future releases.
