### ISSUE TITLE
Singlequotes in Basket ID

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#958]
Test with `BASKET OID = INTERLIS.UUIDOID`

**Comment by beistehen** [comment]
Additonal scenario (tested): No OID format given in INTERLIS model and manually entering a basket OID:
![grafik](https://github.com/user-attachments/assets/a4b47dde-4fa1-454a-96de-72e63cc22430)

-> leads to `BID="'basket1'"` in xtf.
