### ISSUE TITLE
Import/Export Wizard - Message "Database or schema does not exist"

### ISSUE THREAD

**Issue by hov-gl** [opengisch/QgisModelBaker#967]
While generating a QGIS Project from an existing database the log window states "Database or schema does not exist".
Schema is selectable from drop down and exists in database. Schema owner is equal to 'user name' in wizard.
If not a bug, a more specifique message would be helpful.

![image](https://github.com/user-attachments/assets/e616f749-6b64-4c15-8d63-5330c275be90)

**Comment by signedav** [comment]
Feel free to reopen when needed @hov-gl
