### ISSUE TITLE
Generate a QGIS Project: Superuser Login required when using an Authentication Configuration

### ISSUE THREAD

**Issue by webrian** [opengisch/QgisModelBaker#987]
It is basically exactly the same issue as in #905 but for the "Generate a QGIS Project from an existing database" workflow. Since the database isn't changed in this workflow there is no need for more privileges than 'SELECT' privileges on the database tables.

![Bildschirmfoto vom 2024-11-26 21-20-27](https://github.com/user-attachments/assets/38891e55-211a-4728-9669-f566e958539a)

**Comment by signedav** [comment]
Is this with 7.10?

**Comment by webrian** [comment]
Yes, tested with 7.10.3
